
/* This file is generated by bunnylib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#define BDK_ENABLE_BROKEN
#include "bdk.h"
#include "bdkalias.h"
/* enumerations from "bdkcursor.h" */
GType
bdk_cursor_type_get_type (void)
{
    static GType etype = 0;
    if (G_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BDK_X_CURSOR, "BDK_X_CURSOR", "x-cursor" },
            { BDK_ARROW, "BDK_ARROW", "arrow" },
            { BDK_BASED_ARROW_DOWN, "BDK_BASED_ARROW_DOWN", "based-arrow-down" },
            { BDK_BASED_ARROW_UP, "BDK_BASED_ARROW_UP", "based-arrow-up" },
            { BDK_BOAT, "BDK_BOAT", "boat" },
            { BDK_BOGOSITY, "BDK_BOGOSITY", "bogosity" },
            { BDK_BOTTOM_LEFT_CORNER, "BDK_BOTTOM_LEFT_CORNER", "bottom-left-corner" },
            { BDK_BOTTOM_RIGHT_CORNER, "BDK_BOTTOM_RIGHT_CORNER", "bottom-right-corner" },
            { BDK_BOTTOM_SIDE, "BDK_BOTTOM_SIDE", "bottom-side" },
            { BDK_BOTTOM_TEE, "BDK_BOTTOM_TEE", "bottom-tee" },
            { BDK_BOX_SPIRAL, "BDK_BOX_SPIRAL", "box-spiral" },
            { BDK_CENTER_PTR, "BDK_CENTER_PTR", "center-ptr" },
            { BDK_CIRCLE, "BDK_CIRCLE", "circle" },
            { BDK_CLOCK, "BDK_CLOCK", "clock" },
            { BDK_COFFEE_MUG, "BDK_COFFEE_MUG", "coffee-mug" },
            { BDK_CROSS, "BDK_CROSS", "cross" },
            { BDK_CROSS_REVERSE, "BDK_CROSS_REVERSE", "cross-reverse" },
            { BDK_CROSSHAIR, "BDK_CROSSHAIR", "crosshair" },
            { BDK_DIAMOND_CROSS, "BDK_DIAMOND_CROSS", "diamond-cross" },
            { BDK_DOT, "BDK_DOT", "dot" },
            { BDK_DOTBOX, "BDK_DOTBOX", "dotbox" },
            { BDK_DOUBLE_ARROW, "BDK_DOUBLE_ARROW", "double-arrow" },
            { BDK_DRAFT_LARGE, "BDK_DRAFT_LARGE", "draft-large" },
            { BDK_DRAFT_SMALL, "BDK_DRAFT_SMALL", "draft-small" },
            { BDK_DRAPED_BOX, "BDK_DRAPED_BOX", "draped-box" },
            { BDK_EXCHANGE, "BDK_EXCHANGE", "exchange" },
            { BDK_FLEUR, "BDK_FLEUR", "fleur" },
            { BDK_GOBBLER, "BDK_GOBBLER", "gobbler" },
            { BDK_GUMBY, "BDK_GUMBY", "gumby" },
            { BDK_HAND1, "BDK_HAND1", "hand1" },
            { BDK_HAND2, "BDK_HAND2", "hand2" },
            { BDK_HEART, "BDK_HEART", "heart" },
            { BDK_ICON, "BDK_ICON", "icon" },
            { BDK_IRON_CROSS, "BDK_IRON_CROSS", "iron-cross" },
            { BDK_LEFT_PTR, "BDK_LEFT_PTR", "left-ptr" },
            { BDK_LEFT_SIDE, "BDK_LEFT_SIDE", "left-side" },
            { BDK_LEFT_TEE, "BDK_LEFT_TEE", "left-tee" },
            { BDK_LEFTBUTTON, "BDK_LEFTBUTTON", "leftbutton" },
            { BDK_LL_ANGLE, "BDK_LL_ANGLE", "ll-angle" },
            { BDK_LR_ANGLE, "BDK_LR_ANGLE", "lr-angle" },
            { BDK_MAN, "BDK_MAN", "man" },
            { BDK_MIDDLEBUTTON, "BDK_MIDDLEBUTTON", "middlebutton" },
            { BDK_MOUSE, "BDK_MOUSE", "mouse" },
            { BDK_PENCIL, "BDK_PENCIL", "pencil" },
            { BDK_PIRATE, "BDK_PIRATE", "pirate" },
            { BDK_PLUS, "BDK_PLUS", "plus" },
            { BDK_QUESTION_ARROW, "BDK_QUESTION_ARROW", "question-arrow" },
            { BDK_RIGHT_PTR, "BDK_RIGHT_PTR", "right-ptr" },
            { BDK_RIGHT_SIDE, "BDK_RIGHT_SIDE", "right-side" },
            { BDK_RIGHT_TEE, "BDK_RIGHT_TEE", "right-tee" },
            { BDK_RIGHTBUTTON, "BDK_RIGHTBUTTON", "rightbutton" },
            { BDK_RTL_LOGO, "BDK_RTL_LOGO", "rtl-logo" },
            { BDK_SAILBOAT, "BDK_SAILBOAT", "sailboat" },
            { BDK_SB_DOWN_ARROW, "BDK_SB_DOWN_ARROW", "sb-down-arrow" },
            { BDK_SB_H_DOUBLE_ARROW, "BDK_SB_H_DOUBLE_ARROW", "sb-h-double-arrow" },
            { BDK_SB_LEFT_ARROW, "BDK_SB_LEFT_ARROW", "sb-left-arrow" },
            { BDK_SB_RIGHT_ARROW, "BDK_SB_RIGHT_ARROW", "sb-right-arrow" },
            { BDK_SB_UP_ARROW, "BDK_SB_UP_ARROW", "sb-up-arrow" },
            { BDK_SB_V_DOUBLE_ARROW, "BDK_SB_V_DOUBLE_ARROW", "sb-v-double-arrow" },
            { BDK_SHUTTLE, "BDK_SHUTTLE", "shuttle" },
            { BDK_SIZING, "BDK_SIZING", "sizing" },
            { BDK_SPIDER, "BDK_SPIDER", "spider" },
            { BDK_SPRAYCAN, "BDK_SPRAYCAN", "spraycan" },
            { BDK_STAR, "BDK_STAR", "star" },
            { BDK_TARGET, "BDK_TARGET", "target" },
            { BDK_TCROSS, "BDK_TCROSS", "tcross" },
            { BDK_TOP_LEFT_ARROW, "BDK_TOP_LEFT_ARROW", "top-left-arrow" },
            { BDK_TOP_LEFT_CORNER, "BDK_TOP_LEFT_CORNER", "top-left-corner" },
            { BDK_TOP_RIGHT_CORNER, "BDK_TOP_RIGHT_CORNER", "top-right-corner" },
            { BDK_TOP_SIDE, "BDK_TOP_SIDE", "top-side" },
            { BDK_TOP_TEE, "BDK_TOP_TEE", "top-tee" },
            { BDK_TREK, "BDK_TREK", "trek" },
            { BDK_UL_ANGLE, "BDK_UL_ANGLE", "ul-angle" },
            { BDK_UMBRELLA, "BDK_UMBRELLA", "umbrella" },
            { BDK_UR_ANGLE, "BDK_UR_ANGLE", "ur-angle" },
            { BDK_WATCH, "BDK_WATCH", "watch" },
            { BDK_XTERM, "BDK_XTERM", "xterm" },
            { BDK_LAST_CURSOR, "BDK_LAST_CURSOR", "last-cursor" },
            { BDK_BLANK_CURSOR, "BDK_BLANK_CURSOR", "blank-cursor" },
            { BDK_CURSOR_IS_PIXMAP, "BDK_CURSOR_IS_PIXMAP", "cursor-is-pixmap" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BdkCursorType"), values);
    }
    return etype;
}
/* enumerations from "bdkdnd.h" */
GType
bdk_drag_action_get_type (void)
{
    static GType etype = 0;
    if (G_UNLIKELY(etype == 0)) {
        static const GFlagsValue values[] = {
            { BDK_ACTION_DEFAULT, "BDK_ACTION_DEFAULT", "default" },
            { BDK_ACTION_COPY, "BDK_ACTION_COPY", "copy" },
            { BDK_ACTION_MOVE, "BDK_ACTION_MOVE", "move" },
            { BDK_ACTION_LINK, "BDK_ACTION_LINK", "link" },
            { BDK_ACTION_PRIVATE, "BDK_ACTION_PRIVATE", "private" },
            { BDK_ACTION_ASK, "BDK_ACTION_ASK", "ask" },
            { 0, NULL, NULL }
        };
        etype = g_flags_register_static (g_intern_static_string ("BdkDragAction"), values);
    }
    return etype;
}
GType
bdk_drag_protocol_get_type (void)
{
    static GType etype = 0;
    if (G_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BDK_DRAG_PROTO_MOTIF, "BDK_DRAG_PROTO_MOTIF", "motif" },
            { BDK_DRAG_PROTO_XDND, "BDK_DRAG_PROTO_XDND", "xdnd" },
            { BDK_DRAG_PROTO_ROOTWIN, "BDK_DRAG_PROTO_ROOTWIN", "rootwin" },
            { BDK_DRAG_PROTO_NONE, "BDK_DRAG_PROTO_NONE", "none" },
            { BDK_DRAG_PROTO_WIN32_DROPFILES, "BDK_DRAG_PROTO_WIN32_DROPFILES", "win32-dropfiles" },
            { BDK_DRAG_PROTO_OLE2, "BDK_DRAG_PROTO_OLE2", "ole2" },
            { BDK_DRAG_PROTO_LOCAL, "BDK_DRAG_PROTO_LOCAL", "local" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BdkDragProtocol"), values);
    }
    return etype;
}
/* enumerations from "bdkevents.h" */
GType
bdk_filter_return_get_type (void)
{
    static GType etype = 0;
    if (G_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BDK_FILTER_CONTINUE, "BDK_FILTER_CONTINUE", "continue" },
            { BDK_FILTER_TRANSLATE, "BDK_FILTER_TRANSLATE", "translate" },
            { BDK_FILTER_REMOVE, "BDK_FILTER_REMOVE", "remove" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BdkFilterReturn"), values);
    }
    return etype;
}
GType
bdk_event_type_get_type (void)
{
    static GType etype = 0;
    if (G_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BDK_NOTHING, "BDK_NOTHING", "nothing" },
            { BDK_DELETE, "BDK_DELETE", "delete" },
            { BDK_DESTROY, "BDK_DESTROY", "destroy" },
            { BDK_EXPOSE, "BDK_EXPOSE", "expose" },
            { BDK_MOTION_NOTIFY, "BDK_MOTION_NOTIFY", "motion-notify" },
            { BDK_BUTTON_PRESS, "BDK_BUTTON_PRESS", "button-press" },
            { BDK_2BUTTON_PRESS, "BDK_2BUTTON_PRESS", "2button-press" },
            { BDK_3BUTTON_PRESS, "BDK_3BUTTON_PRESS", "3button-press" },
            { BDK_BUTTON_RELEASE, "BDK_BUTTON_RELEASE", "button-release" },
            { BDK_KEY_PRESS, "BDK_KEY_PRESS", "key-press" },
            { BDK_KEY_RELEASE, "BDK_KEY_RELEASE", "key-release" },
            { BDK_ENTER_NOTIFY, "BDK_ENTER_NOTIFY", "enter-notify" },
            { BDK_LEAVE_NOTIFY, "BDK_LEAVE_NOTIFY", "leave-notify" },
            { BDK_FOCUS_CHANGE, "BDK_FOCUS_CHANGE", "focus-change" },
            { BDK_CONFIGURE, "BDK_CONFIGURE", "configure" },
            { BDK_MAP, "BDK_MAP", "map" },
            { BDK_UNMAP, "BDK_UNMAP", "unmap" },
            { BDK_PROPERTY_NOTIFY, "BDK_PROPERTY_NOTIFY", "property-notify" },
            { BDK_SELECTION_CLEAR, "BDK_SELECTION_CLEAR", "selection-clear" },
            { BDK_SELECTION_REQUEST, "BDK_SELECTION_REQUEST", "selection-request" },
            { BDK_SELECTION_NOTIFY, "BDK_SELECTION_NOTIFY", "selection-notify" },
            { BDK_PROXIMITY_IN, "BDK_PROXIMITY_IN", "proximity-in" },
            { BDK_PROXIMITY_OUT, "BDK_PROXIMITY_OUT", "proximity-out" },
            { BDK_DRAG_ENTER, "BDK_DRAG_ENTER", "drag-enter" },
            { BDK_DRAG_LEAVE, "BDK_DRAG_LEAVE", "drag-leave" },
            { BDK_DRAG_MOTION, "BDK_DRAG_MOTION", "drag-motion" },
            { BDK_DRAG_STATUS, "BDK_DRAG_STATUS", "drag-status" },
            { BDK_DROP_START, "BDK_DROP_START", "drop-start" },
            { BDK_DROP_FINISHED, "BDK_DROP_FINISHED", "drop-finished" },
            { BDK_CLIENT_EVENT, "BDK_CLIENT_EVENT", "client-event" },
            { BDK_VISIBILITY_NOTIFY, "BDK_VISIBILITY_NOTIFY", "visibility-notify" },
            { BDK_NO_EXPOSE, "BDK_NO_EXPOSE", "no-expose" },
            { BDK_SCROLL, "BDK_SCROLL", "scroll" },
            { BDK_WINDOW_STATE, "BDK_WINDOW_STATE", "window-state" },
            { BDK_SETTING, "BDK_SETTING", "setting" },
            { BDK_OWNER_CHANGE, "BDK_OWNER_CHANGE", "owner-change" },
            { BDK_GRAB_BROKEN, "BDK_GRAB_BROKEN", "grab-broken" },
            { BDK_DAMAGE, "BDK_DAMAGE", "damage" },
            { BDK_EVENT_LAST, "BDK_EVENT_LAST", "event-last" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BdkEventType"), values);
    }
    return etype;
}
GType
bdk_event_mask_get_type (void)
{
    static GType etype = 0;
    if (G_UNLIKELY(etype == 0)) {
        static const GFlagsValue values[] = {
            { BDK_EXPOSURE_MASK, "BDK_EXPOSURE_MASK", "exposure-mask" },
            { BDK_POINTER_MOTION_MASK, "BDK_POINTER_MOTION_MASK", "pointer-motion-mask" },
            { BDK_POINTER_MOTION_HINT_MASK, "BDK_POINTER_MOTION_HINT_MASK", "pointer-motion-hint-mask" },
            { BDK_BUTTON_MOTION_MASK, "BDK_BUTTON_MOTION_MASK", "button-motion-mask" },
            { BDK_BUTTON1_MOTION_MASK, "BDK_BUTTON1_MOTION_MASK", "button1-motion-mask" },
            { BDK_BUTTON2_MOTION_MASK, "BDK_BUTTON2_MOTION_MASK", "button2-motion-mask" },
            { BDK_BUTTON3_MOTION_MASK, "BDK_BUTTON3_MOTION_MASK", "button3-motion-mask" },
            { BDK_BUTTON_PRESS_MASK, "BDK_BUTTON_PRESS_MASK", "button-press-mask" },
            { BDK_BUTTON_RELEASE_MASK, "BDK_BUTTON_RELEASE_MASK", "button-release-mask" },
            { BDK_KEY_PRESS_MASK, "BDK_KEY_PRESS_MASK", "key-press-mask" },
            { BDK_KEY_RELEASE_MASK, "BDK_KEY_RELEASE_MASK", "key-release-mask" },
            { BDK_ENTER_NOTIFY_MASK, "BDK_ENTER_NOTIFY_MASK", "enter-notify-mask" },
            { BDK_LEAVE_NOTIFY_MASK, "BDK_LEAVE_NOTIFY_MASK", "leave-notify-mask" },
            { BDK_FOCUS_CHANGE_MASK, "BDK_FOCUS_CHANGE_MASK", "focus-change-mask" },
            { BDK_STRUCTURE_MASK, "BDK_STRUCTURE_MASK", "structure-mask" },
            { BDK_PROPERTY_CHANGE_MASK, "BDK_PROPERTY_CHANGE_MASK", "property-change-mask" },
            { BDK_VISIBILITY_NOTIFY_MASK, "BDK_VISIBILITY_NOTIFY_MASK", "visibility-notify-mask" },
            { BDK_PROXIMITY_IN_MASK, "BDK_PROXIMITY_IN_MASK", "proximity-in-mask" },
            { BDK_PROXIMITY_OUT_MASK, "BDK_PROXIMITY_OUT_MASK", "proximity-out-mask" },
            { BDK_SUBSTRUCTURE_MASK, "BDK_SUBSTRUCTURE_MASK", "substructure-mask" },
            { BDK_SCROLL_MASK, "BDK_SCROLL_MASK", "scroll-mask" },
            { BDK_ALL_EVENTS_MASK, "BDK_ALL_EVENTS_MASK", "all-events-mask" },
            { 0, NULL, NULL }
        };
        etype = g_flags_register_static (g_intern_static_string ("BdkEventMask"), values);
    }
    return etype;
}
GType
bdk_visibility_state_get_type (void)
{
    static GType etype = 0;
    if (G_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BDK_VISIBILITY_UNOBSCURED, "BDK_VISIBILITY_UNOBSCURED", "unobscured" },
            { BDK_VISIBILITY_PARTIAL, "BDK_VISIBILITY_PARTIAL", "partial" },
            { BDK_VISIBILITY_FULLY_OBSCURED, "BDK_VISIBILITY_FULLY_OBSCURED", "fully-obscured" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BdkVisibilityState"), values);
    }
    return etype;
}
GType
bdk_scroll_direction_get_type (void)
{
    static GType etype = 0;
    if (G_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BDK_SCROLL_UP, "BDK_SCROLL_UP", "up" },
            { BDK_SCROLL_DOWN, "BDK_SCROLL_DOWN", "down" },
            { BDK_SCROLL_LEFT, "BDK_SCROLL_LEFT", "left" },
            { BDK_SCROLL_RIGHT, "BDK_SCROLL_RIGHT", "right" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BdkScrollDirection"), values);
    }
    return etype;
}
GType
bdk_notify_type_get_type (void)
{
    static GType etype = 0;
    if (G_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BDK_NOTIFY_ANCESTOR, "BDK_NOTIFY_ANCESTOR", "ancestor" },
            { BDK_NOTIFY_VIRTUAL, "BDK_NOTIFY_VIRTUAL", "virtual" },
            { BDK_NOTIFY_INFERIOR, "BDK_NOTIFY_INFERIOR", "inferior" },
            { BDK_NOTIFY_NONLINEAR, "BDK_NOTIFY_NONLINEAR", "nonlinear" },
            { BDK_NOTIFY_NONLINEAR_VIRTUAL, "BDK_NOTIFY_NONLINEAR_VIRTUAL", "nonlinear-virtual" },
            { BDK_NOTIFY_UNKNOWN, "BDK_NOTIFY_UNKNOWN", "unknown" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BdkNotifyType"), values);
    }
    return etype;
}
GType
bdk_crossing_mode_get_type (void)
{
    static GType etype = 0;
    if (G_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BDK_CROSSING_NORMAL, "BDK_CROSSING_NORMAL", "normal" },
            { BDK_CROSSING_GRAB, "BDK_CROSSING_GRAB", "grab" },
            { BDK_CROSSING_UNGRAB, "BDK_CROSSING_UNGRAB", "ungrab" },
            { BDK_CROSSING_BTK_GRAB, "BDK_CROSSING_BTK_GRAB", "btk-grab" },
            { BDK_CROSSING_BTK_UNGRAB, "BDK_CROSSING_BTK_UNGRAB", "btk-ungrab" },
            { BDK_CROSSING_STATE_CHANGED, "BDK_CROSSING_STATE_CHANGED", "state-changed" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BdkCrossingMode"), values);
    }
    return etype;
}
GType
bdk_property_state_get_type (void)
{
    static GType etype = 0;
    if (G_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BDK_PROPERTY_NEW_VALUE, "BDK_PROPERTY_NEW_VALUE", "new-value" },
            { BDK_PROPERTY_DELETE, "BDK_PROPERTY_DELETE", "delete" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BdkPropertyState"), values);
    }
    return etype;
}
GType
bdk_window_state_get_type (void)
{
    static GType etype = 0;
    if (G_UNLIKELY(etype == 0)) {
        static const GFlagsValue values[] = {
            { BDK_WINDOW_STATE_WITHDRAWN, "BDK_WINDOW_STATE_WITHDRAWN", "withdrawn" },
            { BDK_WINDOW_STATE_ICONIFIED, "BDK_WINDOW_STATE_ICONIFIED", "iconified" },
            { BDK_WINDOW_STATE_MAXIMIZED, "BDK_WINDOW_STATE_MAXIMIZED", "maximized" },
            { BDK_WINDOW_STATE_STICKY, "BDK_WINDOW_STATE_STICKY", "sticky" },
            { BDK_WINDOW_STATE_FULLSCREEN, "BDK_WINDOW_STATE_FULLSCREEN", "fullscreen" },
            { BDK_WINDOW_STATE_ABOVE, "BDK_WINDOW_STATE_ABOVE", "above" },
            { BDK_WINDOW_STATE_BELOW, "BDK_WINDOW_STATE_BELOW", "below" },
            { 0, NULL, NULL }
        };
        etype = g_flags_register_static (g_intern_static_string ("BdkWindowState"), values);
    }
    return etype;
}
GType
bdk_setting_action_get_type (void)
{
    static GType etype = 0;
    if (G_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BDK_SETTING_ACTION_NEW, "BDK_SETTING_ACTION_NEW", "new" },
            { BDK_SETTING_ACTION_CHANGED, "BDK_SETTING_ACTION_CHANGED", "changed" },
            { BDK_SETTING_ACTION_DELETED, "BDK_SETTING_ACTION_DELETED", "deleted" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BdkSettingAction"), values);
    }
    return etype;
}
GType
bdk_owner_change_get_type (void)
{
    static GType etype = 0;
    if (G_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BDK_OWNER_CHANGE_NEW_OWNER, "BDK_OWNER_CHANGE_NEW_OWNER", "new-owner" },
            { BDK_OWNER_CHANGE_DESTROY, "BDK_OWNER_CHANGE_DESTROY", "destroy" },
            { BDK_OWNER_CHANGE_CLOSE, "BDK_OWNER_CHANGE_CLOSE", "close" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BdkOwnerChange"), values);
    }
    return etype;
}
/* enumerations from "bdkfont.h" */
GType
bdk_font_type_get_type (void)
{
    static GType etype = 0;
    if (G_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BDK_FONT_FONT, "BDK_FONT_FONT", "font" },
            { BDK_FONT_FONTSET, "BDK_FONT_FONTSET", "fontset" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BdkFontType"), values);
    }
    return etype;
}
/* enumerations from "bdkgc.h" */
GType
bdk_cap_style_get_type (void)
{
    static GType etype = 0;
    if (G_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BDK_CAP_NOT_LAST, "BDK_CAP_NOT_LAST", "not-last" },
            { BDK_CAP_BUTT, "BDK_CAP_BUTT", "butt" },
            { BDK_CAP_ROUND, "BDK_CAP_ROUND", "round" },
            { BDK_CAP_PROJECTING, "BDK_CAP_PROJECTING", "projecting" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BdkCapStyle"), values);
    }
    return etype;
}
GType
bdk_fill_get_type (void)
{
    static GType etype = 0;
    if (G_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BDK_SOLID, "BDK_SOLID", "solid" },
            { BDK_TILED, "BDK_TILED", "tiled" },
            { BDK_STIPPLED, "BDK_STIPPLED", "stippled" },
            { BDK_OPAQUE_STIPPLED, "BDK_OPAQUE_STIPPLED", "opaque-stippled" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BdkFill"), values);
    }
    return etype;
}
GType
bdk_function_get_type (void)
{
    static GType etype = 0;
    if (G_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BDK_COPY, "BDK_COPY", "copy" },
            { BDK_INVERT, "BDK_INVERT", "invert" },
            { BDK_XOR, "BDK_XOR", "xor" },
            { BDK_CLEAR, "BDK_CLEAR", "clear" },
            { BDK_AND, "BDK_AND", "and" },
            { BDK_AND_REVERSE, "BDK_AND_REVERSE", "and-reverse" },
            { BDK_AND_INVERT, "BDK_AND_INVERT", "and-invert" },
            { BDK_NOOP, "BDK_NOOP", "noop" },
            { BDK_OR, "BDK_OR", "or" },
            { BDK_EQUIV, "BDK_EQUIV", "equiv" },
            { BDK_OR_REVERSE, "BDK_OR_REVERSE", "or-reverse" },
            { BDK_COPY_INVERT, "BDK_COPY_INVERT", "copy-invert" },
            { BDK_OR_INVERT, "BDK_OR_INVERT", "or-invert" },
            { BDK_NAND, "BDK_NAND", "nand" },
            { BDK_NOR, "BDK_NOR", "nor" },
            { BDK_SET, "BDK_SET", "set" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BdkFunction"), values);
    }
    return etype;
}
GType
bdk_join_style_get_type (void)
{
    static GType etype = 0;
    if (G_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BDK_JOIN_MITER, "BDK_JOIN_MITER", "miter" },
            { BDK_JOIN_ROUND, "BDK_JOIN_ROUND", "round" },
            { BDK_JOIN_BEVEL, "BDK_JOIN_BEVEL", "bevel" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BdkJoinStyle"), values);
    }
    return etype;
}
GType
bdk_line_style_get_type (void)
{
    static GType etype = 0;
    if (G_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BDK_LINE_SOLID, "BDK_LINE_SOLID", "solid" },
            { BDK_LINE_ON_OFF_DASH, "BDK_LINE_ON_OFF_DASH", "on-off-dash" },
            { BDK_LINE_DOUBLE_DASH, "BDK_LINE_DOUBLE_DASH", "double-dash" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BdkLineStyle"), values);
    }
    return etype;
}
GType
bdk_subwindow_mode_get_type (void)
{
    static GType etype = 0;
    if (G_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BDK_CLIP_BY_CHILDREN, "BDK_CLIP_BY_CHILDREN", "clip-by-children" },
            { BDK_INCLUDE_INFERIORS, "BDK_INCLUDE_INFERIORS", "include-inferiors" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BdkSubwindowMode"), values);
    }
    return etype;
}
GType
bdk_gc_values_mask_get_type (void)
{
    static GType etype = 0;
    if (G_UNLIKELY(etype == 0)) {
        static const GFlagsValue values[] = {
            { BDK_GC_FOREGROUND, "BDK_GC_FOREGROUND", "foreground" },
            { BDK_GC_BACKGROUND, "BDK_GC_BACKGROUND", "background" },
            { BDK_GC_FONT, "BDK_GC_FONT", "font" },
            { BDK_GC_FUNCTION, "BDK_GC_FUNCTION", "function" },
            { BDK_GC_FILL, "BDK_GC_FILL", "fill" },
            { BDK_GC_TILE, "BDK_GC_TILE", "tile" },
            { BDK_GC_STIPPLE, "BDK_GC_STIPPLE", "stipple" },
            { BDK_GC_CLIP_MASK, "BDK_GC_CLIP_MASK", "clip-mask" },
            { BDK_GC_SUBWINDOW, "BDK_GC_SUBWINDOW", "subwindow" },
            { BDK_GC_TS_X_ORIGIN, "BDK_GC_TS_X_ORIGIN", "ts-x-origin" },
            { BDK_GC_TS_Y_ORIGIN, "BDK_GC_TS_Y_ORIGIN", "ts-y-origin" },
            { BDK_GC_CLIP_X_ORIGIN, "BDK_GC_CLIP_X_ORIGIN", "clip-x-origin" },
            { BDK_GC_CLIP_Y_ORIGIN, "BDK_GC_CLIP_Y_ORIGIN", "clip-y-origin" },
            { BDK_GC_EXPOSURES, "BDK_GC_EXPOSURES", "exposures" },
            { BDK_GC_LINE_WIDTH, "BDK_GC_LINE_WIDTH", "line-width" },
            { BDK_GC_LINE_STYLE, "BDK_GC_LINE_STYLE", "line-style" },
            { BDK_GC_CAP_STYLE, "BDK_GC_CAP_STYLE", "cap-style" },
            { BDK_GC_JOIN_STYLE, "BDK_GC_JOIN_STYLE", "join-style" },
            { 0, NULL, NULL }
        };
        etype = g_flags_register_static (g_intern_static_string ("BdkGCValuesMask"), values);
    }
    return etype;
}
/* enumerations from "bdkimage.h" */
GType
bdk_image_type_get_type (void)
{
    static GType etype = 0;
    if (G_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BDK_IMAGE_NORMAL, "BDK_IMAGE_NORMAL", "normal" },
            { BDK_IMAGE_SHARED, "BDK_IMAGE_SHARED", "shared" },
            { BDK_IMAGE_FASTEST, "BDK_IMAGE_FASTEST", "fastest" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BdkImageType"), values);
    }
    return etype;
}
/* enumerations from "bdkinput.h" */
GType
bdk_extension_mode_get_type (void)
{
    static GType etype = 0;
    if (G_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BDK_EXTENSION_EVENTS_NONE, "BDK_EXTENSION_EVENTS_NONE", "none" },
            { BDK_EXTENSION_EVENTS_ALL, "BDK_EXTENSION_EVENTS_ALL", "all" },
            { BDK_EXTENSION_EVENTS_CURSOR, "BDK_EXTENSION_EVENTS_CURSOR", "cursor" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BdkExtensionMode"), values);
    }
    return etype;
}
GType
bdk_input_source_get_type (void)
{
    static GType etype = 0;
    if (G_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BDK_SOURCE_MOUSE, "BDK_SOURCE_MOUSE", "mouse" },
            { BDK_SOURCE_PEN, "BDK_SOURCE_PEN", "pen" },
            { BDK_SOURCE_ERASER, "BDK_SOURCE_ERASER", "eraser" },
            { BDK_SOURCE_CURSOR, "BDK_SOURCE_CURSOR", "cursor" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BdkInputSource"), values);
    }
    return etype;
}
GType
bdk_input_mode_get_type (void)
{
    static GType etype = 0;
    if (G_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BDK_MODE_DISABLED, "BDK_MODE_DISABLED", "disabled" },
            { BDK_MODE_SCREEN, "BDK_MODE_SCREEN", "screen" },
            { BDK_MODE_WINDOW, "BDK_MODE_WINDOW", "window" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BdkInputMode"), values);
    }
    return etype;
}
GType
bdk_axis_use_get_type (void)
{
    static GType etype = 0;
    if (G_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BDK_AXIS_IGNORE, "BDK_AXIS_IGNORE", "ignore" },
            { BDK_AXIS_X, "BDK_AXIS_X", "x" },
            { BDK_AXIS_Y, "BDK_AXIS_Y", "y" },
            { BDK_AXIS_PRESSURE, "BDK_AXIS_PRESSURE", "pressure" },
            { BDK_AXIS_XTILT, "BDK_AXIS_XTILT", "xtilt" },
            { BDK_AXIS_YTILT, "BDK_AXIS_YTILT", "ytilt" },
            { BDK_AXIS_WHEEL, "BDK_AXIS_WHEEL", "wheel" },
            { BDK_AXIS_LAST, "BDK_AXIS_LAST", "last" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BdkAxisUse"), values);
    }
    return etype;
}
/* enumerations from "bdkproperty.h" */
GType
bdk_prop_mode_get_type (void)
{
    static GType etype = 0;
    if (G_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BDK_PROP_MODE_REPLACE, "BDK_PROP_MODE_REPLACE", "replace" },
            { BDK_PROP_MODE_PREPEND, "BDK_PROP_MODE_PREPEND", "prepend" },
            { BDK_PROP_MODE_APPEND, "BDK_PROP_MODE_APPEND", "append" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BdkPropMode"), values);
    }
    return etype;
}
/* enumerations from "bdkrebunnyion.h" */
GType
bdk_fill_rule_get_type (void)
{
    static GType etype = 0;
    if (G_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BDK_EVEN_ODD_RULE, "BDK_EVEN_ODD_RULE", "even-odd-rule" },
            { BDK_WINDING_RULE, "BDK_WINDING_RULE", "winding-rule" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BdkFillRule"), values);
    }
    return etype;
}
GType
bdk_overlap_type_get_type (void)
{
    static GType etype = 0;
    if (G_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BDK_OVERLAP_RECTANGLE_IN, "BDK_OVERLAP_RECTANGLE_IN", "in" },
            { BDK_OVERLAP_RECTANGLE_OUT, "BDK_OVERLAP_RECTANGLE_OUT", "out" },
            { BDK_OVERLAP_RECTANGLE_PART, "BDK_OVERLAP_RECTANGLE_PART", "part" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BdkOverlapType"), values);
    }
    return etype;
}
/* enumerations from "bdkrgb.h" */
GType
bdk_rgb_dither_get_type (void)
{
    static GType etype = 0;
    if (G_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BDK_RGB_DITHER_NONE, "BDK_RGB_DITHER_NONE", "none" },
            { BDK_RGB_DITHER_NORMAL, "BDK_RGB_DITHER_NORMAL", "normal" },
            { BDK_RGB_DITHER_MAX, "BDK_RGB_DITHER_MAX", "max" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BdkRgbDither"), values);
    }
    return etype;
}
/* enumerations from "bdktypes.h" */
GType
bdk_byte_order_get_type (void)
{
    static GType etype = 0;
    if (G_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BDK_LSB_FIRST, "BDK_LSB_FIRST", "lsb-first" },
            { BDK_MSB_FIRST, "BDK_MSB_FIRST", "msb-first" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BdkByteOrder"), values);
    }
    return etype;
}
GType
bdk_modifier_type_get_type (void)
{
    static GType etype = 0;
    if (G_UNLIKELY(etype == 0)) {
        static const GFlagsValue values[] = {
            { BDK_SHIFT_MASK, "BDK_SHIFT_MASK", "shift-mask" },
            { BDK_LOCK_MASK, "BDK_LOCK_MASK", "lock-mask" },
            { BDK_CONTROL_MASK, "BDK_CONTROL_MASK", "control-mask" },
            { BDK_MOD1_MASK, "BDK_MOD1_MASK", "mod1-mask" },
            { BDK_MOD2_MASK, "BDK_MOD2_MASK", "mod2-mask" },
            { BDK_MOD3_MASK, "BDK_MOD3_MASK", "mod3-mask" },
            { BDK_MOD4_MASK, "BDK_MOD4_MASK", "mod4-mask" },
            { BDK_MOD5_MASK, "BDK_MOD5_MASK", "mod5-mask" },
            { BDK_BUTTON1_MASK, "BDK_BUTTON1_MASK", "button1-mask" },
            { BDK_BUTTON2_MASK, "BDK_BUTTON2_MASK", "button2-mask" },
            { BDK_BUTTON3_MASK, "BDK_BUTTON3_MASK", "button3-mask" },
            { BDK_BUTTON4_MASK, "BDK_BUTTON4_MASK", "button4-mask" },
            { BDK_BUTTON5_MASK, "BDK_BUTTON5_MASK", "button5-mask" },
            { BDK_SUPER_MASK, "BDK_SUPER_MASK", "super-mask" },
            { BDK_HYPER_MASK, "BDK_HYPER_MASK", "hyper-mask" },
            { BDK_META_MASK, "BDK_META_MASK", "meta-mask" },
            { BDK_RELEASE_MASK, "BDK_RELEASE_MASK", "release-mask" },
            { BDK_MODIFIER_MASK, "BDK_MODIFIER_MASK", "modifier-mask" },
            { 0, NULL, NULL }
        };
        etype = g_flags_register_static (g_intern_static_string ("BdkModifierType"), values);
    }
    return etype;
}
GType
bdk_input_condition_get_type (void)
{
    static GType etype = 0;
    if (G_UNLIKELY(etype == 0)) {
        static const GFlagsValue values[] = {
            { BDK_INPUT_READ, "BDK_INPUT_READ", "read" },
            { BDK_INPUT_WRITE, "BDK_INPUT_WRITE", "write" },
            { BDK_INPUT_EXCEPTION, "BDK_INPUT_EXCEPTION", "exception" },
            { 0, NULL, NULL }
        };
        etype = g_flags_register_static (g_intern_static_string ("BdkInputCondition"), values);
    }
    return etype;
}
GType
bdk_status_get_type (void)
{
    static GType etype = 0;
    if (G_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BDK_OK, "BDK_OK", "ok" },
            { BDK_ERROR, "BDK_ERROR", "error" },
            { BDK_ERROR_PARAM, "BDK_ERROR_PARAM", "error-param" },
            { BDK_ERROR_FILE, "BDK_ERROR_FILE", "error-file" },
            { BDK_ERROR_MEM, "BDK_ERROR_MEM", "error-mem" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BdkStatus"), values);
    }
    return etype;
}
GType
bdk_grab_status_get_type (void)
{
    static GType etype = 0;
    if (G_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BDK_GRAB_SUCCESS, "BDK_GRAB_SUCCESS", "success" },
            { BDK_GRAB_ALREADY_GRABBED, "BDK_GRAB_ALREADY_GRABBED", "already-grabbed" },
            { BDK_GRAB_INVALID_TIME, "BDK_GRAB_INVALID_TIME", "invalid-time" },
            { BDK_GRAB_NOT_VIEWABLE, "BDK_GRAB_NOT_VIEWABLE", "not-viewable" },
            { BDK_GRAB_FROZEN, "BDK_GRAB_FROZEN", "frozen" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BdkGrabStatus"), values);
    }
    return etype;
}
/* enumerations from "bdkvisual.h" */
GType
bdk_visual_type_get_type (void)
{
    static GType etype = 0;
    if (G_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BDK_VISUAL_STATIC_GRAY, "BDK_VISUAL_STATIC_GRAY", "static-gray" },
            { BDK_VISUAL_GRAYSCALE, "BDK_VISUAL_GRAYSCALE", "grayscale" },
            { BDK_VISUAL_STATIC_COLOR, "BDK_VISUAL_STATIC_COLOR", "static-color" },
            { BDK_VISUAL_PSEUDO_COLOR, "BDK_VISUAL_PSEUDO_COLOR", "pseudo-color" },
            { BDK_VISUAL_TRUE_COLOR, "BDK_VISUAL_TRUE_COLOR", "true-color" },
            { BDK_VISUAL_DIRECT_COLOR, "BDK_VISUAL_DIRECT_COLOR", "direct-color" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BdkVisualType"), values);
    }
    return etype;
}
/* enumerations from "bdkwindow.h" */
GType
bdk_window_class_get_type (void)
{
    static GType etype = 0;
    if (G_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BDK_INPUT_OUTPUT, "BDK_INPUT_OUTPUT", "output" },
            { BDK_INPUT_ONLY, "BDK_INPUT_ONLY", "only" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BdkWindowClass"), values);
    }
    return etype;
}
GType
bdk_window_type_get_type (void)
{
    static GType etype = 0;
    if (G_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BDK_WINDOW_ROOT, "BDK_WINDOW_ROOT", "root" },
            { BDK_WINDOW_TOPLEVEL, "BDK_WINDOW_TOPLEVEL", "toplevel" },
            { BDK_WINDOW_CHILD, "BDK_WINDOW_CHILD", "child" },
            { BDK_WINDOW_DIALOG, "BDK_WINDOW_DIALOG", "dialog" },
            { BDK_WINDOW_TEMP, "BDK_WINDOW_TEMP", "temp" },
            { BDK_WINDOW_FOREIGN, "BDK_WINDOW_FOREIGN", "foreign" },
            { BDK_WINDOW_OFFSCREEN, "BDK_WINDOW_OFFSCREEN", "offscreen" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BdkWindowType"), values);
    }
    return etype;
}
GType
bdk_window_attributes_type_get_type (void)
{
    static GType etype = 0;
    if (G_UNLIKELY(etype == 0)) {
        static const GFlagsValue values[] = {
            { BDK_WA_TITLE, "BDK_WA_TITLE", "title" },
            { BDK_WA_X, "BDK_WA_X", "x" },
            { BDK_WA_Y, "BDK_WA_Y", "y" },
            { BDK_WA_CURSOR, "BDK_WA_CURSOR", "cursor" },
            { BDK_WA_COLORMAP, "BDK_WA_COLORMAP", "colormap" },
            { BDK_WA_VISUAL, "BDK_WA_VISUAL", "visual" },
            { BDK_WA_WMCLASS, "BDK_WA_WMCLASS", "wmclass" },
            { BDK_WA_NOREDIR, "BDK_WA_NOREDIR", "noredir" },
            { BDK_WA_TYPE_HINT, "BDK_WA_TYPE_HINT", "type-hint" },
            { 0, NULL, NULL }
        };
        etype = g_flags_register_static (g_intern_static_string ("BdkWindowAttributesType"), values);
    }
    return etype;
}
GType
bdk_window_hints_get_type (void)
{
    static GType etype = 0;
    if (G_UNLIKELY(etype == 0)) {
        static const GFlagsValue values[] = {
            { BDK_HINT_POS, "BDK_HINT_POS", "pos" },
            { BDK_HINT_MIN_SIZE, "BDK_HINT_MIN_SIZE", "min-size" },
            { BDK_HINT_MAX_SIZE, "BDK_HINT_MAX_SIZE", "max-size" },
            { BDK_HINT_BASE_SIZE, "BDK_HINT_BASE_SIZE", "base-size" },
            { BDK_HINT_ASPECT, "BDK_HINT_ASPECT", "aspect" },
            { BDK_HINT_RESIZE_INC, "BDK_HINT_RESIZE_INC", "resize-inc" },
            { BDK_HINT_WIN_GRAVITY, "BDK_HINT_WIN_GRAVITY", "win-gravity" },
            { BDK_HINT_USER_POS, "BDK_HINT_USER_POS", "user-pos" },
            { BDK_HINT_USER_SIZE, "BDK_HINT_USER_SIZE", "user-size" },
            { 0, NULL, NULL }
        };
        etype = g_flags_register_static (g_intern_static_string ("BdkWindowHints"), values);
    }
    return etype;
}
GType
bdk_window_type_hint_get_type (void)
{
    static GType etype = 0;
    if (G_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BDK_WINDOW_TYPE_HINT_NORMAL, "BDK_WINDOW_TYPE_HINT_NORMAL", "normal" },
            { BDK_WINDOW_TYPE_HINT_DIALOG, "BDK_WINDOW_TYPE_HINT_DIALOG", "dialog" },
            { BDK_WINDOW_TYPE_HINT_MENU, "BDK_WINDOW_TYPE_HINT_MENU", "menu" },
            { BDK_WINDOW_TYPE_HINT_TOOLBAR, "BDK_WINDOW_TYPE_HINT_TOOLBAR", "toolbar" },
            { BDK_WINDOW_TYPE_HINT_SPLASHSCREEN, "BDK_WINDOW_TYPE_HINT_SPLASHSCREEN", "splashscreen" },
            { BDK_WINDOW_TYPE_HINT_UTILITY, "BDK_WINDOW_TYPE_HINT_UTILITY", "utility" },
            { BDK_WINDOW_TYPE_HINT_DOCK, "BDK_WINDOW_TYPE_HINT_DOCK", "dock" },
            { BDK_WINDOW_TYPE_HINT_DESKTOP, "BDK_WINDOW_TYPE_HINT_DESKTOP", "desktop" },
            { BDK_WINDOW_TYPE_HINT_DROPDOWN_MENU, "BDK_WINDOW_TYPE_HINT_DROPDOWN_MENU", "dropdown-menu" },
            { BDK_WINDOW_TYPE_HINT_POPUP_MENU, "BDK_WINDOW_TYPE_HINT_POPUP_MENU", "popup-menu" },
            { BDK_WINDOW_TYPE_HINT_TOOLTIP, "BDK_WINDOW_TYPE_HINT_TOOLTIP", "tooltip" },
            { BDK_WINDOW_TYPE_HINT_NOTIFICATION, "BDK_WINDOW_TYPE_HINT_NOTIFICATION", "notification" },
            { BDK_WINDOW_TYPE_HINT_COMBO, "BDK_WINDOW_TYPE_HINT_COMBO", "combo" },
            { BDK_WINDOW_TYPE_HINT_DND, "BDK_WINDOW_TYPE_HINT_DND", "dnd" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BdkWindowTypeHint"), values);
    }
    return etype;
}
GType
bdk_wm_decoration_get_type (void)
{
    static GType etype = 0;
    if (G_UNLIKELY(etype == 0)) {
        static const GFlagsValue values[] = {
            { BDK_DECOR_ALL, "BDK_DECOR_ALL", "all" },
            { BDK_DECOR_BORDER, "BDK_DECOR_BORDER", "border" },
            { BDK_DECOR_RESIZEH, "BDK_DECOR_RESIZEH", "resizeh" },
            { BDK_DECOR_TITLE, "BDK_DECOR_TITLE", "title" },
            { BDK_DECOR_MENU, "BDK_DECOR_MENU", "menu" },
            { BDK_DECOR_MINIMIZE, "BDK_DECOR_MINIMIZE", "minimize" },
            { BDK_DECOR_MAXIMIZE, "BDK_DECOR_MAXIMIZE", "maximize" },
            { 0, NULL, NULL }
        };
        etype = g_flags_register_static (g_intern_static_string ("BdkWMDecoration"), values);
    }
    return etype;
}
GType
bdk_wm_function_get_type (void)
{
    static GType etype = 0;
    if (G_UNLIKELY(etype == 0)) {
        static const GFlagsValue values[] = {
            { BDK_FUNC_ALL, "BDK_FUNC_ALL", "all" },
            { BDK_FUNC_RESIZE, "BDK_FUNC_RESIZE", "resize" },
            { BDK_FUNC_MOVE, "BDK_FUNC_MOVE", "move" },
            { BDK_FUNC_MINIMIZE, "BDK_FUNC_MINIMIZE", "minimize" },
            { BDK_FUNC_MAXIMIZE, "BDK_FUNC_MAXIMIZE", "maximize" },
            { BDK_FUNC_CLOSE, "BDK_FUNC_CLOSE", "close" },
            { 0, NULL, NULL }
        };
        etype = g_flags_register_static (g_intern_static_string ("BdkWMFunction"), values);
    }
    return etype;
}
GType
bdk_gravity_get_type (void)
{
    static GType etype = 0;
    if (G_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BDK_GRAVITY_NORTH_WEST, "BDK_GRAVITY_NORTH_WEST", "north-west" },
            { BDK_GRAVITY_NORTH, "BDK_GRAVITY_NORTH", "north" },
            { BDK_GRAVITY_NORTH_EAST, "BDK_GRAVITY_NORTH_EAST", "north-east" },
            { BDK_GRAVITY_WEST, "BDK_GRAVITY_WEST", "west" },
            { BDK_GRAVITY_CENTER, "BDK_GRAVITY_CENTER", "center" },
            { BDK_GRAVITY_EAST, "BDK_GRAVITY_EAST", "east" },
            { BDK_GRAVITY_SOUTH_WEST, "BDK_GRAVITY_SOUTH_WEST", "south-west" },
            { BDK_GRAVITY_SOUTH, "BDK_GRAVITY_SOUTH", "south" },
            { BDK_GRAVITY_SOUTH_EAST, "BDK_GRAVITY_SOUTH_EAST", "south-east" },
            { BDK_GRAVITY_STATIC, "BDK_GRAVITY_STATIC", "static" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BdkGravity"), values);
    }
    return etype;
}
GType
bdk_window_edge_get_type (void)
{
    static GType etype = 0;
    if (G_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BDK_WINDOW_EDGE_NORTH_WEST, "BDK_WINDOW_EDGE_NORTH_WEST", "north-west" },
            { BDK_WINDOW_EDGE_NORTH, "BDK_WINDOW_EDGE_NORTH", "north" },
            { BDK_WINDOW_EDGE_NORTH_EAST, "BDK_WINDOW_EDGE_NORTH_EAST", "north-east" },
            { BDK_WINDOW_EDGE_WEST, "BDK_WINDOW_EDGE_WEST", "west" },
            { BDK_WINDOW_EDGE_EAST, "BDK_WINDOW_EDGE_EAST", "east" },
            { BDK_WINDOW_EDGE_SOUTH_WEST, "BDK_WINDOW_EDGE_SOUTH_WEST", "south-west" },
            { BDK_WINDOW_EDGE_SOUTH, "BDK_WINDOW_EDGE_SOUTH", "south" },
            { BDK_WINDOW_EDGE_SOUTH_EAST, "BDK_WINDOW_EDGE_SOUTH_EAST", "south-east" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BdkWindowEdge"), values);
    }
    return etype;
}
#define __BDK_ENUM_TYPES_C__
#include "bdkaliasdef.c"

/* Generated data ends here */

