
/* This file is generated by bunnylib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#if defined(BTK_DISABLE_SINGLE_INCLUDES) && !defined (__BDK_H_INSIDE__) && !defined (BDK_COMPILATION)
#error "Only <bdk/bdk.h> can be included directly."
#endif

#ifndef __BDK_ENUM_TYPES_H__
#define __BDK_ENUM_TYPES_H__

#include <bunnylib-object.h>

B_BEGIN_DECLS

/* enumerations from "bdkcursor.h" */
GType bdk_cursor_type_get_type (void) B_GNUC_CONST;
#define BDK_TYPE_CURSOR_TYPE (bdk_cursor_type_get_type ())

/* enumerations from "bdkdnd.h" */
GType bdk_drag_action_get_type (void) B_GNUC_CONST;
#define BDK_TYPE_DRAG_ACTION (bdk_drag_action_get_type ())
GType bdk_drag_protocol_get_type (void) B_GNUC_CONST;
#define BDK_TYPE_DRAG_PROTOCOL (bdk_drag_protocol_get_type ())

/* enumerations from "bdkevents.h" */
GType bdk_filter_return_get_type (void) B_GNUC_CONST;
#define BDK_TYPE_FILTER_RETURN (bdk_filter_return_get_type ())
GType bdk_event_type_get_type (void) B_GNUC_CONST;
#define BDK_TYPE_EVENT_TYPE (bdk_event_type_get_type ())
GType bdk_event_mask_get_type (void) B_GNUC_CONST;
#define BDK_TYPE_EVENT_MASK (bdk_event_mask_get_type ())
GType bdk_visibility_state_get_type (void) B_GNUC_CONST;
#define BDK_TYPE_VISIBILITY_STATE (bdk_visibility_state_get_type ())
GType bdk_scroll_direction_get_type (void) B_GNUC_CONST;
#define BDK_TYPE_SCROLL_DIRECTION (bdk_scroll_direction_get_type ())
GType bdk_notify_type_get_type (void) B_GNUC_CONST;
#define BDK_TYPE_NOTIFY_TYPE (bdk_notify_type_get_type ())
GType bdk_crossing_mode_get_type (void) B_GNUC_CONST;
#define BDK_TYPE_CROSSING_MODE (bdk_crossing_mode_get_type ())
GType bdk_property_state_get_type (void) B_GNUC_CONST;
#define BDK_TYPE_PROPERTY_STATE (bdk_property_state_get_type ())
GType bdk_window_state_get_type (void) B_GNUC_CONST;
#define BDK_TYPE_WINDOW_STATE (bdk_window_state_get_type ())
GType bdk_setting_action_get_type (void) B_GNUC_CONST;
#define BDK_TYPE_SETTING_ACTION (bdk_setting_action_get_type ())
GType bdk_owner_change_get_type (void) B_GNUC_CONST;
#define BDK_TYPE_OWNER_CHANGE (bdk_owner_change_get_type ())

/* enumerations from "bdkfont.h" */
GType bdk_font_type_get_type (void) B_GNUC_CONST;
#define BDK_TYPE_FONT_TYPE (bdk_font_type_get_type ())

/* enumerations from "bdkgc.h" */
GType bdk_cap_style_get_type (void) B_GNUC_CONST;
#define BDK_TYPE_CAP_STYLE (bdk_cap_style_get_type ())
GType bdk_fill_get_type (void) B_GNUC_CONST;
#define BDK_TYPE_FILL (bdk_fill_get_type ())
GType bdk_function_get_type (void) B_GNUC_CONST;
#define BDK_TYPE_FUNCTION (bdk_function_get_type ())
GType bdk_join_style_get_type (void) B_GNUC_CONST;
#define BDK_TYPE_JOIN_STYLE (bdk_join_style_get_type ())
GType bdk_line_style_get_type (void) B_GNUC_CONST;
#define BDK_TYPE_LINE_STYLE (bdk_line_style_get_type ())
GType bdk_subwindow_mode_get_type (void) B_GNUC_CONST;
#define BDK_TYPE_SUBWINDOW_MODE (bdk_subwindow_mode_get_type ())
GType bdk_gc_values_mask_get_type (void) B_GNUC_CONST;
#define BDK_TYPE_GC_VALUES_MASK (bdk_gc_values_mask_get_type ())

/* enumerations from "bdkimage.h" */
GType bdk_image_type_get_type (void) B_GNUC_CONST;
#define BDK_TYPE_IMAGE_TYPE (bdk_image_type_get_type ())

/* enumerations from "bdkinput.h" */
GType bdk_extension_mode_get_type (void) B_GNUC_CONST;
#define BDK_TYPE_EXTENSION_MODE (bdk_extension_mode_get_type ())
GType bdk_input_source_get_type (void) B_GNUC_CONST;
#define BDK_TYPE_INPUT_SOURCE (bdk_input_source_get_type ())
GType bdk_input_mode_get_type (void) B_GNUC_CONST;
#define BDK_TYPE_INPUT_MODE (bdk_input_mode_get_type ())
GType bdk_axis_use_get_type (void) B_GNUC_CONST;
#define BDK_TYPE_AXIS_USE (bdk_axis_use_get_type ())

/* enumerations from "bdkproperty.h" */
GType bdk_prop_mode_get_type (void) B_GNUC_CONST;
#define BDK_TYPE_PROP_MODE (bdk_prop_mode_get_type ())

/* enumerations from "bdkrebunnyion.h" */
GType bdk_fill_rule_get_type (void) B_GNUC_CONST;
#define BDK_TYPE_FILL_RULE (bdk_fill_rule_get_type ())
GType bdk_overlap_type_get_type (void) B_GNUC_CONST;
#define BDK_TYPE_OVERLAP_TYPE (bdk_overlap_type_get_type ())

/* enumerations from "bdkrgb.h" */
GType bdk_rgb_dither_get_type (void) B_GNUC_CONST;
#define BDK_TYPE_RGB_DITHER (bdk_rgb_dither_get_type ())

/* enumerations from "bdktypes.h" */
GType bdk_byte_order_get_type (void) B_GNUC_CONST;
#define BDK_TYPE_BYTE_ORDER (bdk_byte_order_get_type ())
GType bdk_modifier_type_get_type (void) B_GNUC_CONST;
#define BDK_TYPE_MODIFIER_TYPE (bdk_modifier_type_get_type ())
GType bdk_input_condition_get_type (void) B_GNUC_CONST;
#define BDK_TYPE_INPUT_CONDITION (bdk_input_condition_get_type ())
GType bdk_status_get_type (void) B_GNUC_CONST;
#define BDK_TYPE_STATUS (bdk_status_get_type ())
GType bdk_grab_status_get_type (void) B_GNUC_CONST;
#define BDK_TYPE_GRAB_STATUS (bdk_grab_status_get_type ())

/* enumerations from "bdkvisual.h" */
GType bdk_visual_type_get_type (void) B_GNUC_CONST;
#define BDK_TYPE_VISUAL_TYPE (bdk_visual_type_get_type ())

/* enumerations from "bdkwindow.h" */
GType bdk_window_class_get_type (void) B_GNUC_CONST;
#define BDK_TYPE_WINDOW_CLASS (bdk_window_class_get_type ())
GType bdk_window_type_get_type (void) B_GNUC_CONST;
#define BDK_TYPE_WINDOW_TYPE (bdk_window_type_get_type ())
GType bdk_window_attributes_type_get_type (void) B_GNUC_CONST;
#define BDK_TYPE_WINDOW_ATTRIBUTES_TYPE (bdk_window_attributes_type_get_type ())
GType bdk_window_hints_get_type (void) B_GNUC_CONST;
#define BDK_TYPE_WINDOW_HINTS (bdk_window_hints_get_type ())
GType bdk_window_type_hint_get_type (void) B_GNUC_CONST;
#define BDK_TYPE_WINDOW_TYPE_HINT (bdk_window_type_hint_get_type ())
GType bdk_wm_decoration_get_type (void) B_GNUC_CONST;
#define BDK_TYPE_WM_DECORATION (bdk_wm_decoration_get_type ())
GType bdk_wm_function_get_type (void) B_GNUC_CONST;
#define BDK_TYPE_WM_FUNCTION (bdk_wm_function_get_type ())
GType bdk_gravity_get_type (void) B_GNUC_CONST;
#define BDK_TYPE_GRAVITY (bdk_gravity_get_type ())
GType bdk_window_edge_get_type (void) B_GNUC_CONST;
#define BDK_TYPE_WINDOW_EDGE (bdk_window_edge_get_type ())
B_END_DECLS

#endif /* __BDK_ENUM_TYPES_H__ */

/* Generated data ends here */

