## Makefile for building the btk test apps with Microsoft C
## Use: nmake -f makefile.msc

## There is no install target, you have to decide where and 
## how to install for yourself.

TOP = ..\..
!INCLUDE $(TOP)/bunnylib/build/win32/make.msc

################################################################

# Possibly override versions from build/win32/module.defs
BTK_VER = 2.0
BDK_PIXBUF_VER = 2.0

BDK_LIBS = ../bdk/bdk-win32-$(BTK_VER).lib
BTK_LIBS = ../btk/btk-win32-$(BTK_VER).lib

INCLUDES = -I . -I .. -I ../bdk -I ../btk
DEPCFLAGS = $(BANGO_CFLAGS) $(BUNNYLIB_CFLAGS) $(BDK_PIXBUF_CFLAGS) \
	$(LIBICONV_CFLAGS) $(INTL_CFLAGS) $(BATK_CFLAGS) $(BAIRO_CFLAGS)
LDFLAGS = /link /machine:ix86 $(LINKDEBUG)
DEFINES = -DG_LOG_DOMAIN=\"BtkTest\" -DBTK_VERSION=\"$(BTK_VER)\"

TOUCH = copy makefile.msc+nul

!IFNDEF TESTAPP

all :	\
	..\config.h	\
	prop-editor.obj \
	testsocket_common.obj \
	all-test-apps

..\config.h : ..\config.h.win32
	copy ..\config.h.win32 ..\config.h


#
# Test programs:
#
TESTAPPS = \
#	autotestfilechooser autotestfilesystem \
#	buildertest floatingtest \
	flicker \
	objecttests \
	testaccel testactions testassistant \
	testbbox testbuttons \
	testbairo testcalendar testcellrenderertext testclientmessage testcombo testcombochange \
	testdnd \
	testellipsise testentrycompletion testentryicons \
	testfilechooser testfilechooserbutton testframe \
	testgrouping testbtk \
	testicontheme testiconview testimage testinput \
	testmenus testmountoperation testmenubars testmerge testmultidisplay testmultiscreen \
	testnouiprint testnotebookdnd \
	testoffscreen testoffscreenwindow testorientable \
	testprint \
	testrecentchooser testrecentchoosermenu testrgb testrichtext \
	testscale testselection testspinbutton \
	testtext testtoolbar testtooltips \
	testtreecolumns testtreecolumnsizing testtreeedit testtreeflow testtreefocus \
	testtreemodel testtreesort testtreeview treestoretest \
	testsocket testsocket_child teststatusicon \
	testthreads testvolumebutton testwindows testxinerama \
	simple

# syntax error : illegal character '-' in macro
#stresstest-toolbar


all-test-apps: 
	@for %d in ($(TESTAPPS)) do @nmake -nologo -f makefile.msc one-test-app THIS=%d

one-test-app:
	@nmake -nologo -f makefile.msc $(THIS).exe TESTAPP=$(THIS) EXTRA_$(THIS)=1

!ELSE

EXTRA_OBJETCS = prop-editor.obj

!IFDEF EXTRA_buildertest
EXTRA_LIBS = $(BATK_LIBS)
!ENDIF

!IFDEF EXTRA_testoffscreen
EXTRA_OBJETCS = btkoffscreenbox.obj
!ENDIF

!IFDEF EXTRA_testprint
EXTRA_OBJETCS = testprintfileoperation.obj
EXTRA_LIBS = $(BANGOBAIRO_LIBS)
!ENDIF

!IFDEF EXTRA_testnouiprint
EXTRA_LIBS = $(BANGOBAIRO_LIBS)
!ENDIF

!IFDEF EXTRA_testfilechooser
EXTRA_LIBS = gdi32.lib user32.lib shell32.lib
!ENDIF

!IFDEF EXTRA_testsocket
EXTRA_OBJETCS = testsocket_common.obj
!ENDIF

!IFDEF EXTRA_testsocket_child
EXTRA_OBJETCS = testsocket_common.obj
!ENDIF

$(TESTAPP).exe : ../btk/btk-win32-$(BTK_VER).lib $(TESTAPP).obj $(EXTRA_OBJETCS)
	$(CC) $(CFLAGS) $(TESTAPP).obj $(EXTRA_OBJETCS) $(BTK_LIBS) $(BDK_LIBS) $(BDK_PIXBUF_LIBS) \
	$(BANGO_LIBS) $(BANGOBAIRO_LIBS) $(BUNNYLIB_LIBS) $(BAIRO_LIBS) $(EXTRA_LIBS) $(LDFLAGS)

$(TESTAPP).obj : $(TESTAPP).c
	$(CC) $(CFLAGS) -c -DG_LOG_DOMAIN=\"$(TESTAPP)\" $(TESTAPP).c

!ENDIF
