.TH TESTBTK 1
.SH NAME
testbtk \- test if the Btk library is working
.SH SYNOPSIS
.B testbtk
.SH "DESCRIPTION"
testbtk is a sample program using the Btk library. It tests all the
widgets and buttons and other fun things that Btk lets you do,
and is a good example program to see how to make Btk work.
.SH BUGS
Absolutely none whatsoever.
.SH AUTHOR
Peter Mattis <petm@xcf.berkeley.edu>, 
Spencer Kimball <spencer@xcf.berkeley.edu>,
and Josh MacDonald <jmacd@xcf.berkeley.edu>
