/* This file is generated by bunnylib-genmarshal, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */
#ifndef ___BTK_MARSHAL_MARSHAL_H__
#define ___BTK_MARSHAL_MARSHAL_H__

#include <bunnylib-object.h>

G_BEGIN_DECLS

/* OBJECT:VOID (./marshalers.list:1) */
extern
void _btk_marshal_OBJECT__VOID (GClosure     *closure,
                                GValue       *return_value,
                                guint         n_param_values,
                                const GValue *param_values,
                                gpointer      invocation_hint,
                                gpointer      marshal_data);

/* VOID:ENUM,OBJECT,DOUBLE (./marshalers.list:2) */
extern
void _btk_marshal_VOID__ENUM_OBJECT_DOUBLE (GClosure     *closure,
                                            GValue       *return_value,
                                            guint         n_param_values,
                                            const GValue *param_values,
                                            gpointer      invocation_hint,
                                            gpointer      marshal_data);


G_END_DECLS

#endif /* ___BTK_MARSHAL_MARSHAL_H__ */
