
/* This file is generated by bunnylib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#include "btkwidgetprofiler.h"
/* enumerations from "btkwidgetprofiler.h" */
GType
btk_widget_profiler_report_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_WIDGET_PROFILER_REPORT_CREATE, "BTK_WIDGET_PROFILER_REPORT_CREATE", "create" },
            { BTK_WIDGET_PROFILER_REPORT_MAP, "BTK_WIDGET_PROFILER_REPORT_MAP", "map" },
            { BTK_WIDGET_PROFILER_REPORT_EXPOSE, "BTK_WIDGET_PROFILER_REPORT_EXPOSE", "expose" },
            { BTK_WIDGET_PROFILER_REPORT_DESTROY, "BTK_WIDGET_PROFILER_REPORT_DESTROY", "destroy" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkWidgetProfilerReport"), values);
    }
    return etype;
}
#define __TYPE_BUILTINS_C__

/* Generated data ends here */

