#include "btkmarshal.h"
#include "btkalias.h"
/* This file is generated by bunnylib-genmarshal, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */
#include <bunnylib-object.h>

#ifdef G_ENABLE_DEBUG
#define g_marshal_value_peek_boolean(v)  b_value_get_boolean (v)
#define g_marshal_value_peek_char(v)     b_value_get_schar (v)
#define g_marshal_value_peek_uchar(v)    b_value_get_uchar (v)
#define g_marshal_value_peek_int(v)      b_value_get_int (v)
#define g_marshal_value_peek_uint(v)     b_value_get_uint (v)
#define g_marshal_value_peek_long(v)     b_value_get_long (v)
#define g_marshal_value_peek_ulong(v)    b_value_get_ulong (v)
#define g_marshal_value_peek_int64(v)    b_value_get_int64 (v)
#define g_marshal_value_peek_uint64(v)   b_value_get_uint64 (v)
#define g_marshal_value_peek_enum(v)     b_value_get_enum (v)
#define g_marshal_value_peek_flags(v)    b_value_get_flags (v)
#define g_marshal_value_peek_float(v)    b_value_get_float (v)
#define g_marshal_value_peek_double(v)   b_value_get_double (v)
#define g_marshal_value_peek_string(v)   (char*) b_value_get_string (v)
#define g_marshal_value_peek_param(v)    b_value_get_param (v)
#define g_marshal_value_peek_boxed(v)    b_value_get_boxed (v)
#define g_marshal_value_peek_pointer(v)  b_value_get_pointer (v)
#define g_marshal_value_peek_object(v)   b_value_get_object (v)
#define g_marshal_value_peek_variant(v)  b_value_get_variant (v)
#else /* !G_ENABLE_DEBUG */
/* WARNING: This code accesses BValues directly, which is UNSUPPORTED API.
 *          Do not access BValues directly in your code. Instead, use the
 *          b_value_get_*() functions
 */
#define g_marshal_value_peek_boolean(v)  (v)->data[0].v_int
#define g_marshal_value_peek_char(v)     (v)->data[0].v_int
#define g_marshal_value_peek_uchar(v)    (v)->data[0].v_uint
#define g_marshal_value_peek_int(v)      (v)->data[0].v_int
#define g_marshal_value_peek_uint(v)     (v)->data[0].v_uint
#define g_marshal_value_peek_long(v)     (v)->data[0].v_long
#define g_marshal_value_peek_ulong(v)    (v)->data[0].v_ulong
#define g_marshal_value_peek_int64(v)    (v)->data[0].v_int64
#define g_marshal_value_peek_uint64(v)   (v)->data[0].v_uint64
#define g_marshal_value_peek_enum(v)     (v)->data[0].v_long
#define g_marshal_value_peek_flags(v)    (v)->data[0].v_ulong
#define g_marshal_value_peek_float(v)    (v)->data[0].v_float
#define g_marshal_value_peek_double(v)   (v)->data[0].v_double
#define g_marshal_value_peek_string(v)   (v)->data[0].v_pointer
#define g_marshal_value_peek_param(v)    (v)->data[0].v_pointer
#define g_marshal_value_peek_boxed(v)    (v)->data[0].v_pointer
#define g_marshal_value_peek_pointer(v)  (v)->data[0].v_pointer
#define g_marshal_value_peek_object(v)   (v)->data[0].v_pointer
#define g_marshal_value_peek_variant(v)  (v)->data[0].v_pointer
#endif /* !G_ENABLE_DEBUG */

/* BOOL:NONE (./btkmarshal.list:1) */
void
btk_marshal_BOOLEAN__VOID (GClosure     *closure,
                           BValue       *return_value,
                           guint         n_param_values,
                           const BValue *param_values,
                           gpointer      invocation_hint B_GNUC_UNUSED,
                           gpointer      marshal_data)
{
  typedef gboolean (*GMarshalFunc_BOOLEAN__VOID) (gpointer data1,
                                                  gpointer data2);
  GCClosure *cc = (GCClosure *) closure;
  gpointer data1, data2;
  GMarshalFunc_BOOLEAN__VOID callback;
  gboolean v_return;

  g_return_if_fail (return_value != NULL);
  g_return_if_fail (n_param_values == 1);

  if (G_CCLOSURE_SWAP_DATA (closure))
    {
      data1 = closure->data;
      data2 = b_value_peek_pointer (param_values + 0);
    }
  else
    {
      data1 = b_value_peek_pointer (param_values + 0);
      data2 = closure->data;
    }
  callback = (GMarshalFunc_BOOLEAN__VOID) (marshal_data ? marshal_data : cc->callback);

  v_return = callback (data1,
                       data2);

  b_value_set_boolean (return_value, v_return);
}

/* BOOL:POINTER (./btkmarshal.list:2) */
void
btk_marshal_BOOLEAN__POINTER (GClosure     *closure,
                              BValue       *return_value,
                              guint         n_param_values,
                              const BValue *param_values,
                              gpointer      invocation_hint B_GNUC_UNUSED,
                              gpointer      marshal_data)
{
  typedef gboolean (*GMarshalFunc_BOOLEAN__POINTER) (gpointer data1,
                                                     gpointer arg1,
                                                     gpointer data2);
  GCClosure *cc = (GCClosure *) closure;
  gpointer data1, data2;
  GMarshalFunc_BOOLEAN__POINTER callback;
  gboolean v_return;

  g_return_if_fail (return_value != NULL);
  g_return_if_fail (n_param_values == 2);

  if (G_CCLOSURE_SWAP_DATA (closure))
    {
      data1 = closure->data;
      data2 = b_value_peek_pointer (param_values + 0);
    }
  else
    {
      data1 = b_value_peek_pointer (param_values + 0);
      data2 = closure->data;
    }
  callback = (GMarshalFunc_BOOLEAN__POINTER) (marshal_data ? marshal_data : cc->callback);

  v_return = callback (data1,
                       g_marshal_value_peek_pointer (param_values + 1),
                       data2);

  b_value_set_boolean (return_value, v_return);
}

/* BOOL:POINTER,POINTER,INT,INT (./btkmarshal.list:3) */
void
btk_marshal_BOOLEAN__POINTER_POINTER_INT_INT (GClosure     *closure,
                                              BValue       *return_value,
                                              guint         n_param_values,
                                              const BValue *param_values,
                                              gpointer      invocation_hint B_GNUC_UNUSED,
                                              gpointer      marshal_data)
{
  typedef gboolean (*GMarshalFunc_BOOLEAN__POINTER_POINTER_INT_INT) (gpointer data1,
                                                                     gpointer arg1,
                                                                     gpointer arg2,
                                                                     gint arg3,
                                                                     gint arg4,
                                                                     gpointer data2);
  GCClosure *cc = (GCClosure *) closure;
  gpointer data1, data2;
  GMarshalFunc_BOOLEAN__POINTER_POINTER_INT_INT callback;
  gboolean v_return;

  g_return_if_fail (return_value != NULL);
  g_return_if_fail (n_param_values == 5);

  if (G_CCLOSURE_SWAP_DATA (closure))
    {
      data1 = closure->data;
      data2 = b_value_peek_pointer (param_values + 0);
    }
  else
    {
      data1 = b_value_peek_pointer (param_values + 0);
      data2 = closure->data;
    }
  callback = (GMarshalFunc_BOOLEAN__POINTER_POINTER_INT_INT) (marshal_data ? marshal_data : cc->callback);

  v_return = callback (data1,
                       g_marshal_value_peek_pointer (param_values + 1),
                       g_marshal_value_peek_pointer (param_values + 2),
                       g_marshal_value_peek_int (param_values + 3),
                       g_marshal_value_peek_int (param_values + 4),
                       data2);

  b_value_set_boolean (return_value, v_return);
}

/* BOOL:POINTER,INT,INT (./btkmarshal.list:4) */
void
btk_marshal_BOOLEAN__POINTER_INT_INT (GClosure     *closure,
                                      BValue       *return_value,
                                      guint         n_param_values,
                                      const BValue *param_values,
                                      gpointer      invocation_hint B_GNUC_UNUSED,
                                      gpointer      marshal_data)
{
  typedef gboolean (*GMarshalFunc_BOOLEAN__POINTER_INT_INT) (gpointer data1,
                                                             gpointer arg1,
                                                             gint arg2,
                                                             gint arg3,
                                                             gpointer data2);
  GCClosure *cc = (GCClosure *) closure;
  gpointer data1, data2;
  GMarshalFunc_BOOLEAN__POINTER_INT_INT callback;
  gboolean v_return;

  g_return_if_fail (return_value != NULL);
  g_return_if_fail (n_param_values == 4);

  if (G_CCLOSURE_SWAP_DATA (closure))
    {
      data1 = closure->data;
      data2 = b_value_peek_pointer (param_values + 0);
    }
  else
    {
      data1 = b_value_peek_pointer (param_values + 0);
      data2 = closure->data;
    }
  callback = (GMarshalFunc_BOOLEAN__POINTER_INT_INT) (marshal_data ? marshal_data : cc->callback);

  v_return = callback (data1,
                       g_marshal_value_peek_pointer (param_values + 1),
                       g_marshal_value_peek_int (param_values + 2),
                       g_marshal_value_peek_int (param_values + 3),
                       data2);

  b_value_set_boolean (return_value, v_return);
}

/* BOOL:POINTER,INT,INT,UINT (./btkmarshal.list:5) */
void
btk_marshal_BOOLEAN__POINTER_INT_INT_UINT (GClosure     *closure,
                                           BValue       *return_value,
                                           guint         n_param_values,
                                           const BValue *param_values,
                                           gpointer      invocation_hint B_GNUC_UNUSED,
                                           gpointer      marshal_data)
{
  typedef gboolean (*GMarshalFunc_BOOLEAN__POINTER_INT_INT_UINT) (gpointer data1,
                                                                  gpointer arg1,
                                                                  gint arg2,
                                                                  gint arg3,
                                                                  guint arg4,
                                                                  gpointer data2);
  GCClosure *cc = (GCClosure *) closure;
  gpointer data1, data2;
  GMarshalFunc_BOOLEAN__POINTER_INT_INT_UINT callback;
  gboolean v_return;

  g_return_if_fail (return_value != NULL);
  g_return_if_fail (n_param_values == 5);

  if (G_CCLOSURE_SWAP_DATA (closure))
    {
      data1 = closure->data;
      data2 = b_value_peek_pointer (param_values + 0);
    }
  else
    {
      data1 = b_value_peek_pointer (param_values + 0);
      data2 = closure->data;
    }
  callback = (GMarshalFunc_BOOLEAN__POINTER_INT_INT_UINT) (marshal_data ? marshal_data : cc->callback);

  v_return = callback (data1,
                       g_marshal_value_peek_pointer (param_values + 1),
                       g_marshal_value_peek_int (param_values + 2),
                       g_marshal_value_peek_int (param_values + 3),
                       g_marshal_value_peek_uint (param_values + 4),
                       data2);

  b_value_set_boolean (return_value, v_return);
}

/* BOOL:POINTER,STRING,STRING,POINTER (./btkmarshal.list:6) */
void
btk_marshal_BOOLEAN__POINTER_STRING_STRING_POINTER (GClosure     *closure,
                                                    BValue       *return_value,
                                                    guint         n_param_values,
                                                    const BValue *param_values,
                                                    gpointer      invocation_hint B_GNUC_UNUSED,
                                                    gpointer      marshal_data)
{
  typedef gboolean (*GMarshalFunc_BOOLEAN__POINTER_STRING_STRING_POINTER) (gpointer data1,
                                                                           gpointer arg1,
                                                                           gpointer arg2,
                                                                           gpointer arg3,
                                                                           gpointer arg4,
                                                                           gpointer data2);
  GCClosure *cc = (GCClosure *) closure;
  gpointer data1, data2;
  GMarshalFunc_BOOLEAN__POINTER_STRING_STRING_POINTER callback;
  gboolean v_return;

  g_return_if_fail (return_value != NULL);
  g_return_if_fail (n_param_values == 5);

  if (G_CCLOSURE_SWAP_DATA (closure))
    {
      data1 = closure->data;
      data2 = b_value_peek_pointer (param_values + 0);
    }
  else
    {
      data1 = b_value_peek_pointer (param_values + 0);
      data2 = closure->data;
    }
  callback = (GMarshalFunc_BOOLEAN__POINTER_STRING_STRING_POINTER) (marshal_data ? marshal_data : cc->callback);

  v_return = callback (data1,
                       g_marshal_value_peek_pointer (param_values + 1),
                       g_marshal_value_peek_string (param_values + 2),
                       g_marshal_value_peek_string (param_values + 3),
                       g_marshal_value_peek_pointer (param_values + 4),
                       data2);

  b_value_set_boolean (return_value, v_return);
}

/* ENUM:ENUM (./btkmarshal.list:7) */
void
btk_marshal_ENUM__ENUM (GClosure     *closure,
                        BValue       *return_value,
                        guint         n_param_values,
                        const BValue *param_values,
                        gpointer      invocation_hint B_GNUC_UNUSED,
                        gpointer      marshal_data)
{
  typedef gint (*GMarshalFunc_ENUM__ENUM) (gpointer data1,
                                           gint arg1,
                                           gpointer data2);
  GCClosure *cc = (GCClosure *) closure;
  gpointer data1, data2;
  GMarshalFunc_ENUM__ENUM callback;
  gint v_return;

  g_return_if_fail (return_value != NULL);
  g_return_if_fail (n_param_values == 2);

  if (G_CCLOSURE_SWAP_DATA (closure))
    {
      data1 = closure->data;
      data2 = b_value_peek_pointer (param_values + 0);
    }
  else
    {
      data1 = b_value_peek_pointer (param_values + 0);
      data2 = closure->data;
    }
  callback = (GMarshalFunc_ENUM__ENUM) (marshal_data ? marshal_data : cc->callback);

  v_return = callback (data1,
                       g_marshal_value_peek_enum (param_values + 1),
                       data2);

  b_value_set_enum (return_value, v_return);
}

/* INT:POINTER (./btkmarshal.list:8) */
void
btk_marshal_INT__POINTER (GClosure     *closure,
                          BValue       *return_value,
                          guint         n_param_values,
                          const BValue *param_values,
                          gpointer      invocation_hint B_GNUC_UNUSED,
                          gpointer      marshal_data)
{
  typedef gint (*GMarshalFunc_INT__POINTER) (gpointer data1,
                                             gpointer arg1,
                                             gpointer data2);
  GCClosure *cc = (GCClosure *) closure;
  gpointer data1, data2;
  GMarshalFunc_INT__POINTER callback;
  gint v_return;

  g_return_if_fail (return_value != NULL);
  g_return_if_fail (n_param_values == 2);

  if (G_CCLOSURE_SWAP_DATA (closure))
    {
      data1 = closure->data;
      data2 = b_value_peek_pointer (param_values + 0);
    }
  else
    {
      data1 = b_value_peek_pointer (param_values + 0);
      data2 = closure->data;
    }
  callback = (GMarshalFunc_INT__POINTER) (marshal_data ? marshal_data : cc->callback);

  v_return = callback (data1,
                       g_marshal_value_peek_pointer (param_values + 1),
                       data2);

  b_value_set_int (return_value, v_return);
}

/* INT:POINTER,CHAR,CHAR (./btkmarshal.list:9) */
void
btk_marshal_INT__POINTER_CHAR_CHAR (GClosure     *closure,
                                    BValue       *return_value,
                                    guint         n_param_values,
                                    const BValue *param_values,
                                    gpointer      invocation_hint B_GNUC_UNUSED,
                                    gpointer      marshal_data)
{
  typedef gint (*GMarshalFunc_INT__POINTER_CHAR_CHAR) (gpointer data1,
                                                       gpointer arg1,
                                                       gchar arg2,
                                                       gchar arg3,
                                                       gpointer data2);
  GCClosure *cc = (GCClosure *) closure;
  gpointer data1, data2;
  GMarshalFunc_INT__POINTER_CHAR_CHAR callback;
  gint v_return;

  g_return_if_fail (return_value != NULL);
  g_return_if_fail (n_param_values == 4);

  if (G_CCLOSURE_SWAP_DATA (closure))
    {
      data1 = closure->data;
      data2 = b_value_peek_pointer (param_values + 0);
    }
  else
    {
      data1 = b_value_peek_pointer (param_values + 0);
      data2 = closure->data;
    }
  callback = (GMarshalFunc_INT__POINTER_CHAR_CHAR) (marshal_data ? marshal_data : cc->callback);

  v_return = callback (data1,
                       g_marshal_value_peek_pointer (param_values + 1),
                       g_marshal_value_peek_char (param_values + 2),
                       g_marshal_value_peek_char (param_values + 3),
                       data2);

  b_value_set_int (return_value, v_return);
}

/* NONE:ENUM,FLOAT (./btkmarshal.list:13) */
void
btk_marshal_VOID__ENUM_FLOAT (GClosure     *closure,
                              BValue       *return_value B_GNUC_UNUSED,
                              guint         n_param_values,
                              const BValue *param_values,
                              gpointer      invocation_hint B_GNUC_UNUSED,
                              gpointer      marshal_data)
{
  typedef void (*GMarshalFunc_VOID__ENUM_FLOAT) (gpointer data1,
                                                 gint arg1,
                                                 gfloat arg2,
                                                 gpointer data2);
  GCClosure *cc = (GCClosure *) closure;
  gpointer data1, data2;
  GMarshalFunc_VOID__ENUM_FLOAT callback;

  g_return_if_fail (n_param_values == 3);

  if (G_CCLOSURE_SWAP_DATA (closure))
    {
      data1 = closure->data;
      data2 = b_value_peek_pointer (param_values + 0);
    }
  else
    {
      data1 = b_value_peek_pointer (param_values + 0);
      data2 = closure->data;
    }
  callback = (GMarshalFunc_VOID__ENUM_FLOAT) (marshal_data ? marshal_data : cc->callback);

  callback (data1,
            g_marshal_value_peek_enum (param_values + 1),
            g_marshal_value_peek_float (param_values + 2),
            data2);
}

/* NONE:ENUM,FLOAT,BOOL (./btkmarshal.list:14) */
void
btk_marshal_VOID__ENUM_FLOAT_BOOLEAN (GClosure     *closure,
                                      BValue       *return_value B_GNUC_UNUSED,
                                      guint         n_param_values,
                                      const BValue *param_values,
                                      gpointer      invocation_hint B_GNUC_UNUSED,
                                      gpointer      marshal_data)
{
  typedef void (*GMarshalFunc_VOID__ENUM_FLOAT_BOOLEAN) (gpointer data1,
                                                         gint arg1,
                                                         gfloat arg2,
                                                         gboolean arg3,
                                                         gpointer data2);
  GCClosure *cc = (GCClosure *) closure;
  gpointer data1, data2;
  GMarshalFunc_VOID__ENUM_FLOAT_BOOLEAN callback;

  g_return_if_fail (n_param_values == 4);

  if (G_CCLOSURE_SWAP_DATA (closure))
    {
      data1 = closure->data;
      data2 = b_value_peek_pointer (param_values + 0);
    }
  else
    {
      data1 = b_value_peek_pointer (param_values + 0);
      data2 = closure->data;
    }
  callback = (GMarshalFunc_VOID__ENUM_FLOAT_BOOLEAN) (marshal_data ? marshal_data : cc->callback);

  callback (data1,
            g_marshal_value_peek_enum (param_values + 1),
            g_marshal_value_peek_float (param_values + 2),
            g_marshal_value_peek_boolean (param_values + 3),
            data2);
}

/* NONE:INT,INT (./btkmarshal.list:16) */
void
btk_marshal_VOID__INT_INT (GClosure     *closure,
                           BValue       *return_value B_GNUC_UNUSED,
                           guint         n_param_values,
                           const BValue *param_values,
                           gpointer      invocation_hint B_GNUC_UNUSED,
                           gpointer      marshal_data)
{
  typedef void (*GMarshalFunc_VOID__INT_INT) (gpointer data1,
                                              gint arg1,
                                              gint arg2,
                                              gpointer data2);
  GCClosure *cc = (GCClosure *) closure;
  gpointer data1, data2;
  GMarshalFunc_VOID__INT_INT callback;

  g_return_if_fail (n_param_values == 3);

  if (G_CCLOSURE_SWAP_DATA (closure))
    {
      data1 = closure->data;
      data2 = b_value_peek_pointer (param_values + 0);
    }
  else
    {
      data1 = b_value_peek_pointer (param_values + 0);
      data2 = closure->data;
    }
  callback = (GMarshalFunc_VOID__INT_INT) (marshal_data ? marshal_data : cc->callback);

  callback (data1,
            g_marshal_value_peek_int (param_values + 1),
            g_marshal_value_peek_int (param_values + 2),
            data2);
}

/* NONE:INT,INT,POINTER (./btkmarshal.list:17) */
void
btk_marshal_VOID__INT_INT_POINTER (GClosure     *closure,
                                   BValue       *return_value B_GNUC_UNUSED,
                                   guint         n_param_values,
                                   const BValue *param_values,
                                   gpointer      invocation_hint B_GNUC_UNUSED,
                                   gpointer      marshal_data)
{
  typedef void (*GMarshalFunc_VOID__INT_INT_POINTER) (gpointer data1,
                                                      gint arg1,
                                                      gint arg2,
                                                      gpointer arg3,
                                                      gpointer data2);
  GCClosure *cc = (GCClosure *) closure;
  gpointer data1, data2;
  GMarshalFunc_VOID__INT_INT_POINTER callback;

  g_return_if_fail (n_param_values == 4);

  if (G_CCLOSURE_SWAP_DATA (closure))
    {
      data1 = closure->data;
      data2 = b_value_peek_pointer (param_values + 0);
    }
  else
    {
      data1 = b_value_peek_pointer (param_values + 0);
      data2 = closure->data;
    }
  callback = (GMarshalFunc_VOID__INT_INT_POINTER) (marshal_data ? marshal_data : cc->callback);

  callback (data1,
            g_marshal_value_peek_int (param_values + 1),
            g_marshal_value_peek_int (param_values + 2),
            g_marshal_value_peek_pointer (param_values + 3),
            data2);
}

/* NONE:POINTER,INT (./btkmarshal.list:21) */
void
btk_marshal_VOID__POINTER_INT (GClosure     *closure,
                               BValue       *return_value B_GNUC_UNUSED,
                               guint         n_param_values,
                               const BValue *param_values,
                               gpointer      invocation_hint B_GNUC_UNUSED,
                               gpointer      marshal_data)
{
  typedef void (*GMarshalFunc_VOID__POINTER_INT) (gpointer data1,
                                                  gpointer arg1,
                                                  gint arg2,
                                                  gpointer data2);
  GCClosure *cc = (GCClosure *) closure;
  gpointer data1, data2;
  GMarshalFunc_VOID__POINTER_INT callback;

  g_return_if_fail (n_param_values == 3);

  if (G_CCLOSURE_SWAP_DATA (closure))
    {
      data1 = closure->data;
      data2 = b_value_peek_pointer (param_values + 0);
    }
  else
    {
      data1 = b_value_peek_pointer (param_values + 0);
      data2 = closure->data;
    }
  callback = (GMarshalFunc_VOID__POINTER_INT) (marshal_data ? marshal_data : cc->callback);

  callback (data1,
            g_marshal_value_peek_pointer (param_values + 1),
            g_marshal_value_peek_int (param_values + 2),
            data2);
}

/* NONE:POINTER,POINTER (./btkmarshal.list:22) */
void
btk_marshal_VOID__POINTER_POINTER (GClosure     *closure,
                                   BValue       *return_value B_GNUC_UNUSED,
                                   guint         n_param_values,
                                   const BValue *param_values,
                                   gpointer      invocation_hint B_GNUC_UNUSED,
                                   gpointer      marshal_data)
{
  typedef void (*GMarshalFunc_VOID__POINTER_POINTER) (gpointer data1,
                                                      gpointer arg1,
                                                      gpointer arg2,
                                                      gpointer data2);
  GCClosure *cc = (GCClosure *) closure;
  gpointer data1, data2;
  GMarshalFunc_VOID__POINTER_POINTER callback;

  g_return_if_fail (n_param_values == 3);

  if (G_CCLOSURE_SWAP_DATA (closure))
    {
      data1 = closure->data;
      data2 = b_value_peek_pointer (param_values + 0);
    }
  else
    {
      data1 = b_value_peek_pointer (param_values + 0);
      data2 = closure->data;
    }
  callback = (GMarshalFunc_VOID__POINTER_POINTER) (marshal_data ? marshal_data : cc->callback);

  callback (data1,
            g_marshal_value_peek_pointer (param_values + 1),
            g_marshal_value_peek_pointer (param_values + 2),
            data2);
}

/* NONE:POINTER,POINTER,POINTER (./btkmarshal.list:23) */
void
btk_marshal_VOID__POINTER_POINTER_POINTER (GClosure     *closure,
                                           BValue       *return_value B_GNUC_UNUSED,
                                           guint         n_param_values,
                                           const BValue *param_values,
                                           gpointer      invocation_hint B_GNUC_UNUSED,
                                           gpointer      marshal_data)
{
  typedef void (*GMarshalFunc_VOID__POINTER_POINTER_POINTER) (gpointer data1,
                                                              gpointer arg1,
                                                              gpointer arg2,
                                                              gpointer arg3,
                                                              gpointer data2);
  GCClosure *cc = (GCClosure *) closure;
  gpointer data1, data2;
  GMarshalFunc_VOID__POINTER_POINTER_POINTER callback;

  g_return_if_fail (n_param_values == 4);

  if (G_CCLOSURE_SWAP_DATA (closure))
    {
      data1 = closure->data;
      data2 = b_value_peek_pointer (param_values + 0);
    }
  else
    {
      data1 = b_value_peek_pointer (param_values + 0);
      data2 = closure->data;
    }
  callback = (GMarshalFunc_VOID__POINTER_POINTER_POINTER) (marshal_data ? marshal_data : cc->callback);

  callback (data1,
            g_marshal_value_peek_pointer (param_values + 1),
            g_marshal_value_peek_pointer (param_values + 2),
            g_marshal_value_peek_pointer (param_values + 3),
            data2);
}

/* NONE:POINTER,STRING,STRING (./btkmarshal.list:24) */
void
btk_marshal_VOID__POINTER_STRING_STRING (GClosure     *closure,
                                         BValue       *return_value B_GNUC_UNUSED,
                                         guint         n_param_values,
                                         const BValue *param_values,
                                         gpointer      invocation_hint B_GNUC_UNUSED,
                                         gpointer      marshal_data)
{
  typedef void (*GMarshalFunc_VOID__POINTER_STRING_STRING) (gpointer data1,
                                                            gpointer arg1,
                                                            gpointer arg2,
                                                            gpointer arg3,
                                                            gpointer data2);
  GCClosure *cc = (GCClosure *) closure;
  gpointer data1, data2;
  GMarshalFunc_VOID__POINTER_STRING_STRING callback;

  g_return_if_fail (n_param_values == 4);

  if (G_CCLOSURE_SWAP_DATA (closure))
    {
      data1 = closure->data;
      data2 = b_value_peek_pointer (param_values + 0);
    }
  else
    {
      data1 = b_value_peek_pointer (param_values + 0);
      data2 = closure->data;
    }
  callback = (GMarshalFunc_VOID__POINTER_STRING_STRING) (marshal_data ? marshal_data : cc->callback);

  callback (data1,
            g_marshal_value_peek_pointer (param_values + 1),
            g_marshal_value_peek_string (param_values + 2),
            g_marshal_value_peek_string (param_values + 3),
            data2);
}

/* NONE:POINTER,UINT (./btkmarshal.list:25) */
void
btk_marshal_VOID__POINTER_UINT (GClosure     *closure,
                                BValue       *return_value B_GNUC_UNUSED,
                                guint         n_param_values,
                                const BValue *param_values,
                                gpointer      invocation_hint B_GNUC_UNUSED,
                                gpointer      marshal_data)
{
  typedef void (*GMarshalFunc_VOID__POINTER_UINT) (gpointer data1,
                                                   gpointer arg1,
                                                   guint arg2,
                                                   gpointer data2);
  GCClosure *cc = (GCClosure *) closure;
  gpointer data1, data2;
  GMarshalFunc_VOID__POINTER_UINT callback;

  g_return_if_fail (n_param_values == 3);

  if (G_CCLOSURE_SWAP_DATA (closure))
    {
      data1 = closure->data;
      data2 = b_value_peek_pointer (param_values + 0);
    }
  else
    {
      data1 = b_value_peek_pointer (param_values + 0);
      data2 = closure->data;
    }
  callback = (GMarshalFunc_VOID__POINTER_UINT) (marshal_data ? marshal_data : cc->callback);

  callback (data1,
            g_marshal_value_peek_pointer (param_values + 1),
            g_marshal_value_peek_uint (param_values + 2),
            data2);
}

/* NONE:POINTER,UINT,ENUM (./btkmarshal.list:26) */
void
btk_marshal_VOID__POINTER_UINT_ENUM (GClosure     *closure,
                                     BValue       *return_value B_GNUC_UNUSED,
                                     guint         n_param_values,
                                     const BValue *param_values,
                                     gpointer      invocation_hint B_GNUC_UNUSED,
                                     gpointer      marshal_data)
{
  typedef void (*GMarshalFunc_VOID__POINTER_UINT_ENUM) (gpointer data1,
                                                        gpointer arg1,
                                                        guint arg2,
                                                        gint arg3,
                                                        gpointer data2);
  GCClosure *cc = (GCClosure *) closure;
  gpointer data1, data2;
  GMarshalFunc_VOID__POINTER_UINT_ENUM callback;

  g_return_if_fail (n_param_values == 4);

  if (G_CCLOSURE_SWAP_DATA (closure))
    {
      data1 = closure->data;
      data2 = b_value_peek_pointer (param_values + 0);
    }
  else
    {
      data1 = b_value_peek_pointer (param_values + 0);
      data2 = closure->data;
    }
  callback = (GMarshalFunc_VOID__POINTER_UINT_ENUM) (marshal_data ? marshal_data : cc->callback);

  callback (data1,
            g_marshal_value_peek_pointer (param_values + 1),
            g_marshal_value_peek_uint (param_values + 2),
            g_marshal_value_peek_enum (param_values + 3),
            data2);
}

/* NONE:POINTER,POINTER,UINT,UINT (./btkmarshal.list:27) */
void
btk_marshal_VOID__POINTER_POINTER_UINT_UINT (GClosure     *closure,
                                             BValue       *return_value B_GNUC_UNUSED,
                                             guint         n_param_values,
                                             const BValue *param_values,
                                             gpointer      invocation_hint B_GNUC_UNUSED,
                                             gpointer      marshal_data)
{
  typedef void (*GMarshalFunc_VOID__POINTER_POINTER_UINT_UINT) (gpointer data1,
                                                                gpointer arg1,
                                                                gpointer arg2,
                                                                guint arg3,
                                                                guint arg4,
                                                                gpointer data2);
  GCClosure *cc = (GCClosure *) closure;
  gpointer data1, data2;
  GMarshalFunc_VOID__POINTER_POINTER_UINT_UINT callback;

  g_return_if_fail (n_param_values == 5);

  if (G_CCLOSURE_SWAP_DATA (closure))
    {
      data1 = closure->data;
      data2 = b_value_peek_pointer (param_values + 0);
    }
  else
    {
      data1 = b_value_peek_pointer (param_values + 0);
      data2 = closure->data;
    }
  callback = (GMarshalFunc_VOID__POINTER_POINTER_UINT_UINT) (marshal_data ? marshal_data : cc->callback);

  callback (data1,
            g_marshal_value_peek_pointer (param_values + 1),
            g_marshal_value_peek_pointer (param_values + 2),
            g_marshal_value_peek_uint (param_values + 3),
            g_marshal_value_peek_uint (param_values + 4),
            data2);
}

/* NONE:POINTER,INT,INT,POINTER,UINT,UINT (./btkmarshal.list:28) */
void
btk_marshal_VOID__POINTER_INT_INT_POINTER_UINT_UINT (GClosure     *closure,
                                                     BValue       *return_value B_GNUC_UNUSED,
                                                     guint         n_param_values,
                                                     const BValue *param_values,
                                                     gpointer      invocation_hint B_GNUC_UNUSED,
                                                     gpointer      marshal_data)
{
  typedef void (*GMarshalFunc_VOID__POINTER_INT_INT_POINTER_UINT_UINT) (gpointer data1,
                                                                        gpointer arg1,
                                                                        gint arg2,
                                                                        gint arg3,
                                                                        gpointer arg4,
                                                                        guint arg5,
                                                                        guint arg6,
                                                                        gpointer data2);
  GCClosure *cc = (GCClosure *) closure;
  gpointer data1, data2;
  GMarshalFunc_VOID__POINTER_INT_INT_POINTER_UINT_UINT callback;

  g_return_if_fail (n_param_values == 7);

  if (G_CCLOSURE_SWAP_DATA (closure))
    {
      data1 = closure->data;
      data2 = b_value_peek_pointer (param_values + 0);
    }
  else
    {
      data1 = b_value_peek_pointer (param_values + 0);
      data2 = closure->data;
    }
  callback = (GMarshalFunc_VOID__POINTER_INT_INT_POINTER_UINT_UINT) (marshal_data ? marshal_data : cc->callback);

  callback (data1,
            g_marshal_value_peek_pointer (param_values + 1),
            g_marshal_value_peek_int (param_values + 2),
            g_marshal_value_peek_int (param_values + 3),
            g_marshal_value_peek_pointer (param_values + 4),
            g_marshal_value_peek_uint (param_values + 5),
            g_marshal_value_peek_uint (param_values + 6),
            data2);
}

/* NONE:POINTER,UINT,UINT (./btkmarshal.list:29) */
void
btk_marshal_VOID__POINTER_UINT_UINT (GClosure     *closure,
                                     BValue       *return_value B_GNUC_UNUSED,
                                     guint         n_param_values,
                                     const BValue *param_values,
                                     gpointer      invocation_hint B_GNUC_UNUSED,
                                     gpointer      marshal_data)
{
  typedef void (*GMarshalFunc_VOID__POINTER_UINT_UINT) (gpointer data1,
                                                        gpointer arg1,
                                                        guint arg2,
                                                        guint arg3,
                                                        gpointer data2);
  GCClosure *cc = (GCClosure *) closure;
  gpointer data1, data2;
  GMarshalFunc_VOID__POINTER_UINT_UINT callback;

  g_return_if_fail (n_param_values == 4);

  if (G_CCLOSURE_SWAP_DATA (closure))
    {
      data1 = closure->data;
      data2 = b_value_peek_pointer (param_values + 0);
    }
  else
    {
      data1 = b_value_peek_pointer (param_values + 0);
      data2 = closure->data;
    }
  callback = (GMarshalFunc_VOID__POINTER_UINT_UINT) (marshal_data ? marshal_data : cc->callback);

  callback (data1,
            g_marshal_value_peek_pointer (param_values + 1),
            g_marshal_value_peek_uint (param_values + 2),
            g_marshal_value_peek_uint (param_values + 3),
            data2);
}

/* NONE:STRING,INT,POINTER (./btkmarshal.list:32) */
void
btk_marshal_VOID__STRING_INT_POINTER (GClosure     *closure,
                                      BValue       *return_value B_GNUC_UNUSED,
                                      guint         n_param_values,
                                      const BValue *param_values,
                                      gpointer      invocation_hint B_GNUC_UNUSED,
                                      gpointer      marshal_data)
{
  typedef void (*GMarshalFunc_VOID__STRING_INT_POINTER) (gpointer data1,
                                                         gpointer arg1,
                                                         gint arg2,
                                                         gpointer arg3,
                                                         gpointer data2);
  GCClosure *cc = (GCClosure *) closure;
  gpointer data1, data2;
  GMarshalFunc_VOID__STRING_INT_POINTER callback;

  g_return_if_fail (n_param_values == 4);

  if (G_CCLOSURE_SWAP_DATA (closure))
    {
      data1 = closure->data;
      data2 = b_value_peek_pointer (param_values + 0);
    }
  else
    {
      data1 = b_value_peek_pointer (param_values + 0);
      data2 = closure->data;
    }
  callback = (GMarshalFunc_VOID__STRING_INT_POINTER) (marshal_data ? marshal_data : cc->callback);

  callback (data1,
            g_marshal_value_peek_string (param_values + 1),
            g_marshal_value_peek_int (param_values + 2),
            g_marshal_value_peek_pointer (param_values + 3),
            data2);
}

/* NONE:UINT,POINTER,UINT,ENUM,ENUM,POINTER (./btkmarshal.list:34) */
void
btk_marshal_VOID__UINT_POINTER_UINT_ENUM_ENUM_POINTER (GClosure     *closure,
                                                       BValue       *return_value B_GNUC_UNUSED,
                                                       guint         n_param_values,
                                                       const BValue *param_values,
                                                       gpointer      invocation_hint B_GNUC_UNUSED,
                                                       gpointer      marshal_data)
{
  typedef void (*GMarshalFunc_VOID__UINT_POINTER_UINT_ENUM_ENUM_POINTER) (gpointer data1,
                                                                          guint arg1,
                                                                          gpointer arg2,
                                                                          guint arg3,
                                                                          gint arg4,
                                                                          gint arg5,
                                                                          gpointer arg6,
                                                                          gpointer data2);
  GCClosure *cc = (GCClosure *) closure;
  gpointer data1, data2;
  GMarshalFunc_VOID__UINT_POINTER_UINT_ENUM_ENUM_POINTER callback;

  g_return_if_fail (n_param_values == 7);

  if (G_CCLOSURE_SWAP_DATA (closure))
    {
      data1 = closure->data;
      data2 = b_value_peek_pointer (param_values + 0);
    }
  else
    {
      data1 = b_value_peek_pointer (param_values + 0);
      data2 = closure->data;
    }
  callback = (GMarshalFunc_VOID__UINT_POINTER_UINT_ENUM_ENUM_POINTER) (marshal_data ? marshal_data : cc->callback);

  callback (data1,
            g_marshal_value_peek_uint (param_values + 1),
            g_marshal_value_peek_pointer (param_values + 2),
            g_marshal_value_peek_uint (param_values + 3),
            g_marshal_value_peek_enum (param_values + 4),
            g_marshal_value_peek_enum (param_values + 5),
            g_marshal_value_peek_pointer (param_values + 6),
            data2);
}

/* NONE:UINT,POINTER,UINT,UINT,ENUM (./btkmarshal.list:35) */
void
btk_marshal_VOID__UINT_POINTER_UINT_UINT_ENUM (GClosure     *closure,
                                               BValue       *return_value B_GNUC_UNUSED,
                                               guint         n_param_values,
                                               const BValue *param_values,
                                               gpointer      invocation_hint B_GNUC_UNUSED,
                                               gpointer      marshal_data)
{
  typedef void (*GMarshalFunc_VOID__UINT_POINTER_UINT_UINT_ENUM) (gpointer data1,
                                                                  guint arg1,
                                                                  gpointer arg2,
                                                                  guint arg3,
                                                                  guint arg4,
                                                                  gint arg5,
                                                                  gpointer data2);
  GCClosure *cc = (GCClosure *) closure;
  gpointer data1, data2;
  GMarshalFunc_VOID__UINT_POINTER_UINT_UINT_ENUM callback;

  g_return_if_fail (n_param_values == 6);

  if (G_CCLOSURE_SWAP_DATA (closure))
    {
      data1 = closure->data;
      data2 = b_value_peek_pointer (param_values + 0);
    }
  else
    {
      data1 = b_value_peek_pointer (param_values + 0);
      data2 = closure->data;
    }
  callback = (GMarshalFunc_VOID__UINT_POINTER_UINT_UINT_ENUM) (marshal_data ? marshal_data : cc->callback);

  callback (data1,
            g_marshal_value_peek_uint (param_values + 1),
            g_marshal_value_peek_pointer (param_values + 2),
            g_marshal_value_peek_uint (param_values + 3),
            g_marshal_value_peek_uint (param_values + 4),
            g_marshal_value_peek_enum (param_values + 5),
            data2);
}

/* NONE:UINT,STRING (./btkmarshal.list:36) */
void
btk_marshal_VOID__UINT_STRING (GClosure     *closure,
                               BValue       *return_value B_GNUC_UNUSED,
                               guint         n_param_values,
                               const BValue *param_values,
                               gpointer      invocation_hint B_GNUC_UNUSED,
                               gpointer      marshal_data)
{
  typedef void (*GMarshalFunc_VOID__UINT_STRING) (gpointer data1,
                                                  guint arg1,
                                                  gpointer arg2,
                                                  gpointer data2);
  GCClosure *cc = (GCClosure *) closure;
  gpointer data1, data2;
  GMarshalFunc_VOID__UINT_STRING callback;

  g_return_if_fail (n_param_values == 3);

  if (G_CCLOSURE_SWAP_DATA (closure))
    {
      data1 = closure->data;
      data2 = b_value_peek_pointer (param_values + 0);
    }
  else
    {
      data1 = b_value_peek_pointer (param_values + 0);
      data2 = closure->data;
    }
  callback = (GMarshalFunc_VOID__UINT_STRING) (marshal_data ? marshal_data : cc->callback);

  callback (data1,
            g_marshal_value_peek_uint (param_values + 1),
            g_marshal_value_peek_string (param_values + 2),
            data2);
}

#define __btk_marshal_MARSHAL_C__
#include "btkaliasdef.c"
