
/* This file is generated by bunnylib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#undef BTK_DISABLE_DEPRECATED
#define BTK_ENABLE_BROKEN
#include "btk.h"
#include "btkprivate.h"
#include "btkalias.h"
/* enumerations from "btkaccelgroup.h" */
GType
btk_accel_flags_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GFlagsValue values[] = {
            { BTK_ACCEL_VISIBLE, "BTK_ACCEL_VISIBLE", "visible" },
            { BTK_ACCEL_LOCKED, "BTK_ACCEL_LOCKED", "locked" },
            { BTK_ACCEL_MASK, "BTK_ACCEL_MASK", "mask" },
            { 0, NULL, NULL }
        };
        etype = g_flags_register_static (g_intern_static_string ("BtkAccelFlags"), values);
    }
    return etype;
}
/* enumerations from "btkassistant.h" */
GType
btk_assistant_page_type_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_ASSISTANT_PAGE_CONTENT, "BTK_ASSISTANT_PAGE_CONTENT", "content" },
            { BTK_ASSISTANT_PAGE_INTRO, "BTK_ASSISTANT_PAGE_INTRO", "intro" },
            { BTK_ASSISTANT_PAGE_CONFIRM, "BTK_ASSISTANT_PAGE_CONFIRM", "confirm" },
            { BTK_ASSISTANT_PAGE_SUMMARY, "BTK_ASSISTANT_PAGE_SUMMARY", "summary" },
            { BTK_ASSISTANT_PAGE_PROGRESS, "BTK_ASSISTANT_PAGE_PROGRESS", "progress" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkAssistantPageType"), values);
    }
    return etype;
}
/* enumerations from "btkbuilder.h" */
GType
btk_builder_error_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_BUILDER_ERROR_INVALID_TYPE_FUNCTION, "BTK_BUILDER_ERROR_INVALID_TYPE_FUNCTION", "invalid-type-function" },
            { BTK_BUILDER_ERROR_UNHANDLED_TAG, "BTK_BUILDER_ERROR_UNHANDLED_TAG", "unhandled-tag" },
            { BTK_BUILDER_ERROR_MISSING_ATTRIBUTE, "BTK_BUILDER_ERROR_MISSING_ATTRIBUTE", "missing-attribute" },
            { BTK_BUILDER_ERROR_INVALID_ATTRIBUTE, "BTK_BUILDER_ERROR_INVALID_ATTRIBUTE", "invalid-attribute" },
            { BTK_BUILDER_ERROR_INVALID_TAG, "BTK_BUILDER_ERROR_INVALID_TAG", "invalid-tag" },
            { BTK_BUILDER_ERROR_MISSING_PROPERTY_VALUE, "BTK_BUILDER_ERROR_MISSING_PROPERTY_VALUE", "missing-property-value" },
            { BTK_BUILDER_ERROR_INVALID_VALUE, "BTK_BUILDER_ERROR_INVALID_VALUE", "invalid-value" },
            { BTK_BUILDER_ERROR_VERSION_MISMATCH, "BTK_BUILDER_ERROR_VERSION_MISMATCH", "version-mismatch" },
            { BTK_BUILDER_ERROR_DUPLICATE_ID, "BTK_BUILDER_ERROR_DUPLICATE_ID", "duplicate-id" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkBuilderError"), values);
    }
    return etype;
}
/* enumerations from "btkcalendar.h" */
GType
btk_calendar_display_options_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GFlagsValue values[] = {
            { BTK_CALENDAR_SHOW_HEADING, "BTK_CALENDAR_SHOW_HEADING", "show-heading" },
            { BTK_CALENDAR_SHOW_DAY_NAMES, "BTK_CALENDAR_SHOW_DAY_NAMES", "show-day-names" },
            { BTK_CALENDAR_NO_MONTH_CHANGE, "BTK_CALENDAR_NO_MONTH_CHANGE", "no-month-change" },
            { BTK_CALENDAR_SHOW_WEEK_NUMBERS, "BTK_CALENDAR_SHOW_WEEK_NUMBERS", "show-week-numbers" },
            { BTK_CALENDAR_WEEK_START_MONDAY, "BTK_CALENDAR_WEEK_START_MONDAY", "week-start-monday" },
            { BTK_CALENDAR_SHOW_DETAILS, "BTK_CALENDAR_SHOW_DETAILS", "show-details" },
            { 0, NULL, NULL }
        };
        etype = g_flags_register_static (g_intern_static_string ("BtkCalendarDisplayOptions"), values);
    }
    return etype;
}
/* enumerations from "btkcellrenderer.h" */
GType
btk_cell_renderer_state_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GFlagsValue values[] = {
            { BTK_CELL_RENDERER_SELECTED, "BTK_CELL_RENDERER_SELECTED", "selected" },
            { BTK_CELL_RENDERER_PRELIT, "BTK_CELL_RENDERER_PRELIT", "prelit" },
            { BTK_CELL_RENDERER_INSENSITIVE, "BTK_CELL_RENDERER_INSENSITIVE", "insensitive" },
            { BTK_CELL_RENDERER_SORTED, "BTK_CELL_RENDERER_SORTED", "sorted" },
            { BTK_CELL_RENDERER_FOCUSED, "BTK_CELL_RENDERER_FOCUSED", "focused" },
            { 0, NULL, NULL }
        };
        etype = g_flags_register_static (g_intern_static_string ("BtkCellRendererState"), values);
    }
    return etype;
}
GType
btk_cell_renderer_mode_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_CELL_RENDERER_MODE_INERT, "BTK_CELL_RENDERER_MODE_INERT", "inert" },
            { BTK_CELL_RENDERER_MODE_ACTIVATABLE, "BTK_CELL_RENDERER_MODE_ACTIVATABLE", "activatable" },
            { BTK_CELL_RENDERER_MODE_EDITABLE, "BTK_CELL_RENDERER_MODE_EDITABLE", "editable" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkCellRendererMode"), values);
    }
    return etype;
}
/* enumerations from "btkcellrendereraccel.h" */
GType
btk_cell_renderer_accel_mode_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_CELL_RENDERER_ACCEL_MODE_BTK, "BTK_CELL_RENDERER_ACCEL_MODE_BTK", "btk" },
            { BTK_CELL_RENDERER_ACCEL_MODE_OTHER, "BTK_CELL_RENDERER_ACCEL_MODE_OTHER", "other" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkCellRendererAccelMode"), values);
    }
    return etype;
}
/* enumerations from "btkclist.h" */
GType
btk_cell_type_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_CELL_EMPTY, "BTK_CELL_EMPTY", "empty" },
            { BTK_CELL_TEXT, "BTK_CELL_TEXT", "text" },
            { BTK_CELL_PIXMAP, "BTK_CELL_PIXMAP", "pixmap" },
            { BTK_CELL_PIXTEXT, "BTK_CELL_PIXTEXT", "pixtext" },
            { BTK_CELL_WIDGET, "BTK_CELL_WIDGET", "widget" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkCellType"), values);
    }
    return etype;
}
GType
btk_clist_drag_pos_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_CLIST_DRAG_NONE, "BTK_CLIST_DRAG_NONE", "none" },
            { BTK_CLIST_DRAG_BEFORE, "BTK_CLIST_DRAG_BEFORE", "before" },
            { BTK_CLIST_DRAG_INTO, "BTK_CLIST_DRAG_INTO", "into" },
            { BTK_CLIST_DRAG_AFTER, "BTK_CLIST_DRAG_AFTER", "after" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkCListDragPos"), values);
    }
    return etype;
}
GType
btk_button_action_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GFlagsValue values[] = {
            { BTK_BUTTON_IGNORED, "BTK_BUTTON_IGNORED", "ignored" },
            { BTK_BUTTON_SELECTS, "BTK_BUTTON_SELECTS", "selects" },
            { BTK_BUTTON_DRAGS, "BTK_BUTTON_DRAGS", "drags" },
            { BTK_BUTTON_EXPANDS, "BTK_BUTTON_EXPANDS", "expands" },
            { 0, NULL, NULL }
        };
        etype = g_flags_register_static (g_intern_static_string ("BtkButtonAction"), values);
    }
    return etype;
}
/* enumerations from "btkctree.h" */
GType
btk_ctree_pos_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_CTREE_POS_BEFORE, "BTK_CTREE_POS_BEFORE", "before" },
            { BTK_CTREE_POS_AS_CHILD, "BTK_CTREE_POS_AS_CHILD", "as-child" },
            { BTK_CTREE_POS_AFTER, "BTK_CTREE_POS_AFTER", "after" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkCTreePos"), values);
    }
    return etype;
}
GType
btk_ctree_line_style_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_CTREE_LINES_NONE, "BTK_CTREE_LINES_NONE", "none" },
            { BTK_CTREE_LINES_SOLID, "BTK_CTREE_LINES_SOLID", "solid" },
            { BTK_CTREE_LINES_DOTTED, "BTK_CTREE_LINES_DOTTED", "dotted" },
            { BTK_CTREE_LINES_TABBED, "BTK_CTREE_LINES_TABBED", "tabbed" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkCTreeLineStyle"), values);
    }
    return etype;
}
GType
btk_ctree_expander_style_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_CTREE_EXPANDER_NONE, "BTK_CTREE_EXPANDER_NONE", "none" },
            { BTK_CTREE_EXPANDER_SQUARE, "BTK_CTREE_EXPANDER_SQUARE", "square" },
            { BTK_CTREE_EXPANDER_TRIANGLE, "BTK_CTREE_EXPANDER_TRIANGLE", "triangle" },
            { BTK_CTREE_EXPANDER_CIRCULAR, "BTK_CTREE_EXPANDER_CIRCULAR", "circular" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkCTreeExpanderStyle"), values);
    }
    return etype;
}
GType
btk_ctree_expansion_type_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_CTREE_EXPANSION_EXPAND, "BTK_CTREE_EXPANSION_EXPAND", "expand" },
            { BTK_CTREE_EXPANSION_EXPAND_RECURSIVE, "BTK_CTREE_EXPANSION_EXPAND_RECURSIVE", "expand-recursive" },
            { BTK_CTREE_EXPANSION_COLLAPSE, "BTK_CTREE_EXPANSION_COLLAPSE", "collapse" },
            { BTK_CTREE_EXPANSION_COLLAPSE_RECURSIVE, "BTK_CTREE_EXPANSION_COLLAPSE_RECURSIVE", "collapse-recursive" },
            { BTK_CTREE_EXPANSION_TOGGLE, "BTK_CTREE_EXPANSION_TOGGLE", "toggle" },
            { BTK_CTREE_EXPANSION_TOGGLE_RECURSIVE, "BTK_CTREE_EXPANSION_TOGGLE_RECURSIVE", "toggle-recursive" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkCTreeExpansionType"), values);
    }
    return etype;
}
/* enumerations from "btkdebug.h" */
GType
btk_debug_flag_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GFlagsValue values[] = {
            { BTK_DEBUG_MISC, "BTK_DEBUG_MISC", "misc" },
            { BTK_DEBUG_PLUGSOCKET, "BTK_DEBUG_PLUGSOCKET", "plugsocket" },
            { BTK_DEBUG_TEXT, "BTK_DEBUG_TEXT", "text" },
            { BTK_DEBUG_TREE, "BTK_DEBUG_TREE", "tree" },
            { BTK_DEBUG_UPDATES, "BTK_DEBUG_UPDATES", "updates" },
            { BTK_DEBUG_KEYBINDINGS, "BTK_DEBUG_KEYBINDINGS", "keybindings" },
            { BTK_DEBUG_MULTIHEAD, "BTK_DEBUG_MULTIHEAD", "multihead" },
            { BTK_DEBUG_MODULES, "BTK_DEBUG_MODULES", "modules" },
            { BTK_DEBUG_GEOMETRY, "BTK_DEBUG_GEOMETRY", "geometry" },
            { BTK_DEBUG_ICONTHEME, "BTK_DEBUG_ICONTHEME", "icontheme" },
            { BTK_DEBUG_PRINTING, "BTK_DEBUG_PRINTING", "printing" },
            { BTK_DEBUG_BUILDER, "BTK_DEBUG_BUILDER", "builder" },
            { 0, NULL, NULL }
        };
        etype = g_flags_register_static (g_intern_static_string ("BtkDebugFlag"), values);
    }
    return etype;
}
/* enumerations from "btkdialog.h" */
GType
btk_dialog_flags_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GFlagsValue values[] = {
            { BTK_DIALOG_MODAL, "BTK_DIALOG_MODAL", "modal" },
            { BTK_DIALOG_DESTROY_WITH_PARENT, "BTK_DIALOG_DESTROY_WITH_PARENT", "destroy-with-parent" },
            { BTK_DIALOG_NO_SEPARATOR, "BTK_DIALOG_NO_SEPARATOR", "no-separator" },
            { 0, NULL, NULL }
        };
        etype = g_flags_register_static (g_intern_static_string ("BtkDialogFlags"), values);
    }
    return etype;
}
GType
btk_response_type_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_RESPONSE_NONE, "BTK_RESPONSE_NONE", "none" },
            { BTK_RESPONSE_REJECT, "BTK_RESPONSE_REJECT", "reject" },
            { BTK_RESPONSE_ACCEPT, "BTK_RESPONSE_ACCEPT", "accept" },
            { BTK_RESPONSE_DELETE_EVENT, "BTK_RESPONSE_DELETE_EVENT", "delete-event" },
            { BTK_RESPONSE_OK, "BTK_RESPONSE_OK", "ok" },
            { BTK_RESPONSE_CANCEL, "BTK_RESPONSE_CANCEL", "cancel" },
            { BTK_RESPONSE_CLOSE, "BTK_RESPONSE_CLOSE", "close" },
            { BTK_RESPONSE_YES, "BTK_RESPONSE_YES", "yes" },
            { BTK_RESPONSE_NO, "BTK_RESPONSE_NO", "no" },
            { BTK_RESPONSE_APPLY, "BTK_RESPONSE_APPLY", "apply" },
            { BTK_RESPONSE_HELP, "BTK_RESPONSE_HELP", "help" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkResponseType"), values);
    }
    return etype;
}
/* enumerations from "btkdnd.h" */
GType
btk_dest_defaults_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GFlagsValue values[] = {
            { BTK_DEST_DEFAULT_MOTION, "BTK_DEST_DEFAULT_MOTION", "motion" },
            { BTK_DEST_DEFAULT_HIGHLIGHT, "BTK_DEST_DEFAULT_HIGHLIGHT", "highlight" },
            { BTK_DEST_DEFAULT_DROP, "BTK_DEST_DEFAULT_DROP", "drop" },
            { BTK_DEST_DEFAULT_ALL, "BTK_DEST_DEFAULT_ALL", "all" },
            { 0, NULL, NULL }
        };
        etype = g_flags_register_static (g_intern_static_string ("BtkDestDefaults"), values);
    }
    return etype;
}
GType
btk_target_flags_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GFlagsValue values[] = {
            { BTK_TARGET_SAME_APP, "BTK_TARGET_SAME_APP", "same-app" },
            { BTK_TARGET_SAME_WIDGET, "BTK_TARGET_SAME_WIDGET", "same-widget" },
            { BTK_TARGET_OTHER_APP, "BTK_TARGET_OTHER_APP", "other-app" },
            { BTK_TARGET_OTHER_WIDGET, "BTK_TARGET_OTHER_WIDGET", "other-widget" },
            { 0, NULL, NULL }
        };
        etype = g_flags_register_static (g_intern_static_string ("BtkTargetFlags"), values);
    }
    return etype;
}
/* enumerations from "btkentry.h" */
GType
btk_entry_icon_position_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_ENTRY_ICON_PRIMARY, "BTK_ENTRY_ICON_PRIMARY", "primary" },
            { BTK_ENTRY_ICON_SECONDARY, "BTK_ENTRY_ICON_SECONDARY", "secondary" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkEntryIconPosition"), values);
    }
    return etype;
}
/* enumerations from "btkenums.h" */
GType
btk_anchor_type_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_ANCHOR_CENTER, "BTK_ANCHOR_CENTER", "center" },
            { BTK_ANCHOR_NORTH, "BTK_ANCHOR_NORTH", "north" },
            { BTK_ANCHOR_NORTH_WEST, "BTK_ANCHOR_NORTH_WEST", "north-west" },
            { BTK_ANCHOR_NORTH_EAST, "BTK_ANCHOR_NORTH_EAST", "north-east" },
            { BTK_ANCHOR_SOUTH, "BTK_ANCHOR_SOUTH", "south" },
            { BTK_ANCHOR_SOUTH_WEST, "BTK_ANCHOR_SOUTH_WEST", "south-west" },
            { BTK_ANCHOR_SOUTH_EAST, "BTK_ANCHOR_SOUTH_EAST", "south-east" },
            { BTK_ANCHOR_WEST, "BTK_ANCHOR_WEST", "west" },
            { BTK_ANCHOR_EAST, "BTK_ANCHOR_EAST", "east" },
            { BTK_ANCHOR_N, "BTK_ANCHOR_N", "n" },
            { BTK_ANCHOR_NW, "BTK_ANCHOR_NW", "nw" },
            { BTK_ANCHOR_NE, "BTK_ANCHOR_NE", "ne" },
            { BTK_ANCHOR_S, "BTK_ANCHOR_S", "s" },
            { BTK_ANCHOR_SW, "BTK_ANCHOR_SW", "sw" },
            { BTK_ANCHOR_SE, "BTK_ANCHOR_SE", "se" },
            { BTK_ANCHOR_W, "BTK_ANCHOR_W", "w" },
            { BTK_ANCHOR_E, "BTK_ANCHOR_E", "e" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkAnchorType"), values);
    }
    return etype;
}
GType
btk_arrow_placement_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_ARROWS_BOTH, "BTK_ARROWS_BOTH", "both" },
            { BTK_ARROWS_START, "BTK_ARROWS_START", "start" },
            { BTK_ARROWS_END, "BTK_ARROWS_END", "end" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkArrowPlacement"), values);
    }
    return etype;
}
GType
btk_arrow_type_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_ARROW_UP, "BTK_ARROW_UP", "up" },
            { BTK_ARROW_DOWN, "BTK_ARROW_DOWN", "down" },
            { BTK_ARROW_LEFT, "BTK_ARROW_LEFT", "left" },
            { BTK_ARROW_RIGHT, "BTK_ARROW_RIGHT", "right" },
            { BTK_ARROW_NONE, "BTK_ARROW_NONE", "none" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkArrowType"), values);
    }
    return etype;
}
GType
btk_attach_options_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GFlagsValue values[] = {
            { BTK_EXPAND, "BTK_EXPAND", "expand" },
            { BTK_SHRINK, "BTK_SHRINK", "shrink" },
            { BTK_FILL, "BTK_FILL", "fill" },
            { 0, NULL, NULL }
        };
        etype = g_flags_register_static (g_intern_static_string ("BtkAttachOptions"), values);
    }
    return etype;
}
GType
btk_button_box_style_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_BUTTONBOX_DEFAULT_STYLE, "BTK_BUTTONBOX_DEFAULT_STYLE", "default-style" },
            { BTK_BUTTONBOX_SPREAD, "BTK_BUTTONBOX_SPREAD", "spread" },
            { BTK_BUTTONBOX_EDGE, "BTK_BUTTONBOX_EDGE", "edge" },
            { BTK_BUTTONBOX_START, "BTK_BUTTONBOX_START", "start" },
            { BTK_BUTTONBOX_END, "BTK_BUTTONBOX_END", "end" },
            { BTK_BUTTONBOX_CENTER, "BTK_BUTTONBOX_CENTER", "center" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkButtonBoxStyle"), values);
    }
    return etype;
}
GType
btk_curve_type_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_CURVE_TYPE_LINEAR, "BTK_CURVE_TYPE_LINEAR", "linear" },
            { BTK_CURVE_TYPE_SPLINE, "BTK_CURVE_TYPE_SPLINE", "spline" },
            { BTK_CURVE_TYPE_FREE, "BTK_CURVE_TYPE_FREE", "free" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkCurveType"), values);
    }
    return etype;
}
GType
btk_delete_type_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_DELETE_CHARS, "BTK_DELETE_CHARS", "chars" },
            { BTK_DELETE_WORD_ENDS, "BTK_DELETE_WORD_ENDS", "word-ends" },
            { BTK_DELETE_WORDS, "BTK_DELETE_WORDS", "words" },
            { BTK_DELETE_DISPLAY_LINES, "BTK_DELETE_DISPLAY_LINES", "display-lines" },
            { BTK_DELETE_DISPLAY_LINE_ENDS, "BTK_DELETE_DISPLAY_LINE_ENDS", "display-line-ends" },
            { BTK_DELETE_PARAGRAPH_ENDS, "BTK_DELETE_PARAGRAPH_ENDS", "paragraph-ends" },
            { BTK_DELETE_PARAGRAPHS, "BTK_DELETE_PARAGRAPHS", "paragraphs" },
            { BTK_DELETE_WHITESPACE, "BTK_DELETE_WHITESPACE", "whitespace" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkDeleteType"), values);
    }
    return etype;
}
GType
btk_direction_type_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_DIR_TAB_FORWARD, "BTK_DIR_TAB_FORWARD", "tab-forward" },
            { BTK_DIR_TAB_BACKWARD, "BTK_DIR_TAB_BACKWARD", "tab-backward" },
            { BTK_DIR_UP, "BTK_DIR_UP", "up" },
            { BTK_DIR_DOWN, "BTK_DIR_DOWN", "down" },
            { BTK_DIR_LEFT, "BTK_DIR_LEFT", "left" },
            { BTK_DIR_RIGHT, "BTK_DIR_RIGHT", "right" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkDirectionType"), values);
    }
    return etype;
}
GType
btk_expander_style_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_EXPANDER_COLLAPSED, "BTK_EXPANDER_COLLAPSED", "collapsed" },
            { BTK_EXPANDER_SEMI_COLLAPSED, "BTK_EXPANDER_SEMI_COLLAPSED", "semi-collapsed" },
            { BTK_EXPANDER_SEMI_EXPANDED, "BTK_EXPANDER_SEMI_EXPANDED", "semi-expanded" },
            { BTK_EXPANDER_EXPANDED, "BTK_EXPANDER_EXPANDED", "expanded" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkExpanderStyle"), values);
    }
    return etype;
}
GType
btk_icon_size_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_ICON_SIZE_INVALID, "BTK_ICON_SIZE_INVALID", "invalid" },
            { BTK_ICON_SIZE_MENU, "BTK_ICON_SIZE_MENU", "menu" },
            { BTK_ICON_SIZE_SMALL_TOOLBAR, "BTK_ICON_SIZE_SMALL_TOOLBAR", "small-toolbar" },
            { BTK_ICON_SIZE_LARGE_TOOLBAR, "BTK_ICON_SIZE_LARGE_TOOLBAR", "large-toolbar" },
            { BTK_ICON_SIZE_BUTTON, "BTK_ICON_SIZE_BUTTON", "button" },
            { BTK_ICON_SIZE_DND, "BTK_ICON_SIZE_DND", "dnd" },
            { BTK_ICON_SIZE_DIALOG, "BTK_ICON_SIZE_DIALOG", "dialog" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkIconSize"), values);
    }
    return etype;
}
GType
btk_sensitivity_type_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_SENSITIVITY_AUTO, "BTK_SENSITIVITY_AUTO", "auto" },
            { BTK_SENSITIVITY_ON, "BTK_SENSITIVITY_ON", "on" },
            { BTK_SENSITIVITY_OFF, "BTK_SENSITIVITY_OFF", "off" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkSensitivityType"), values);
    }
    return etype;
}
GType
btk_side_type_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_SIDE_TOP, "BTK_SIDE_TOP", "top" },
            { BTK_SIDE_BOTTOM, "BTK_SIDE_BOTTOM", "bottom" },
            { BTK_SIDE_LEFT, "BTK_SIDE_LEFT", "left" },
            { BTK_SIDE_RIGHT, "BTK_SIDE_RIGHT", "right" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkSideType"), values);
    }
    return etype;
}
GType
btk_text_direction_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_TEXT_DIR_NONE, "BTK_TEXT_DIR_NONE", "none" },
            { BTK_TEXT_DIR_LTR, "BTK_TEXT_DIR_LTR", "ltr" },
            { BTK_TEXT_DIR_RTL, "BTK_TEXT_DIR_RTL", "rtl" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkTextDirection"), values);
    }
    return etype;
}
GType
btk_justification_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_JUSTIFY_LEFT, "BTK_JUSTIFY_LEFT", "left" },
            { BTK_JUSTIFY_RIGHT, "BTK_JUSTIFY_RIGHT", "right" },
            { BTK_JUSTIFY_CENTER, "BTK_JUSTIFY_CENTER", "center" },
            { BTK_JUSTIFY_FILL, "BTK_JUSTIFY_FILL", "fill" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkJustification"), values);
    }
    return etype;
}
GType
btk_match_type_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_MATCH_ALL, "BTK_MATCH_ALL", "all" },
            { BTK_MATCH_ALL_TAIL, "BTK_MATCH_ALL_TAIL", "all-tail" },
            { BTK_MATCH_HEAD, "BTK_MATCH_HEAD", "head" },
            { BTK_MATCH_TAIL, "BTK_MATCH_TAIL", "tail" },
            { BTK_MATCH_EXACT, "BTK_MATCH_EXACT", "exact" },
            { BTK_MATCH_LAST, "BTK_MATCH_LAST", "last" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkMatchType"), values);
    }
    return etype;
}
GType
btk_menu_direction_type_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_MENU_DIR_PARENT, "BTK_MENU_DIR_PARENT", "parent" },
            { BTK_MENU_DIR_CHILD, "BTK_MENU_DIR_CHILD", "child" },
            { BTK_MENU_DIR_NEXT, "BTK_MENU_DIR_NEXT", "next" },
            { BTK_MENU_DIR_PREV, "BTK_MENU_DIR_PREV", "prev" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkMenuDirectionType"), values);
    }
    return etype;
}
GType
btk_message_type_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_MESSAGE_INFO, "BTK_MESSAGE_INFO", "info" },
            { BTK_MESSAGE_WARNING, "BTK_MESSAGE_WARNING", "warning" },
            { BTK_MESSAGE_QUESTION, "BTK_MESSAGE_QUESTION", "question" },
            { BTK_MESSAGE_ERROR, "BTK_MESSAGE_ERROR", "error" },
            { BTK_MESSAGE_OTHER, "BTK_MESSAGE_OTHER", "other" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkMessageType"), values);
    }
    return etype;
}
GType
btk_metric_type_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_PIXELS, "BTK_PIXELS", "pixels" },
            { BTK_INCHES, "BTK_INCHES", "inches" },
            { BTK_CENTIMETERS, "BTK_CENTIMETERS", "centimeters" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkMetricType"), values);
    }
    return etype;
}
GType
btk_movement_step_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_MOVEMENT_LOGICAL_POSITIONS, "BTK_MOVEMENT_LOGICAL_POSITIONS", "logical-positions" },
            { BTK_MOVEMENT_VISUAL_POSITIONS, "BTK_MOVEMENT_VISUAL_POSITIONS", "visual-positions" },
            { BTK_MOVEMENT_WORDS, "BTK_MOVEMENT_WORDS", "words" },
            { BTK_MOVEMENT_DISPLAY_LINES, "BTK_MOVEMENT_DISPLAY_LINES", "display-lines" },
            { BTK_MOVEMENT_DISPLAY_LINE_ENDS, "BTK_MOVEMENT_DISPLAY_LINE_ENDS", "display-line-ends" },
            { BTK_MOVEMENT_PARAGRAPHS, "BTK_MOVEMENT_PARAGRAPHS", "paragraphs" },
            { BTK_MOVEMENT_PARAGRAPH_ENDS, "BTK_MOVEMENT_PARAGRAPH_ENDS", "paragraph-ends" },
            { BTK_MOVEMENT_PAGES, "BTK_MOVEMENT_PAGES", "pages" },
            { BTK_MOVEMENT_BUFFER_ENDS, "BTK_MOVEMENT_BUFFER_ENDS", "buffer-ends" },
            { BTK_MOVEMENT_HORIZONTAL_PAGES, "BTK_MOVEMENT_HORIZONTAL_PAGES", "horizontal-pages" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkMovementStep"), values);
    }
    return etype;
}
GType
btk_scroll_step_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_SCROLL_STEPS, "BTK_SCROLL_STEPS", "steps" },
            { BTK_SCROLL_PAGES, "BTK_SCROLL_PAGES", "pages" },
            { BTK_SCROLL_ENDS, "BTK_SCROLL_ENDS", "ends" },
            { BTK_SCROLL_HORIZONTAL_STEPS, "BTK_SCROLL_HORIZONTAL_STEPS", "horizontal-steps" },
            { BTK_SCROLL_HORIZONTAL_PAGES, "BTK_SCROLL_HORIZONTAL_PAGES", "horizontal-pages" },
            { BTK_SCROLL_HORIZONTAL_ENDS, "BTK_SCROLL_HORIZONTAL_ENDS", "horizontal-ends" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkScrollStep"), values);
    }
    return etype;
}
GType
btk_orientation_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_ORIENTATION_HORIZONTAL, "BTK_ORIENTATION_HORIZONTAL", "horizontal" },
            { BTK_ORIENTATION_VERTICAL, "BTK_ORIENTATION_VERTICAL", "vertical" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkOrientation"), values);
    }
    return etype;
}
GType
btk_corner_type_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_CORNER_TOP_LEFT, "BTK_CORNER_TOP_LEFT", "top-left" },
            { BTK_CORNER_BOTTOM_LEFT, "BTK_CORNER_BOTTOM_LEFT", "bottom-left" },
            { BTK_CORNER_TOP_RIGHT, "BTK_CORNER_TOP_RIGHT", "top-right" },
            { BTK_CORNER_BOTTOM_RIGHT, "BTK_CORNER_BOTTOM_RIGHT", "bottom-right" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkCornerType"), values);
    }
    return etype;
}
GType
btk_pack_type_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_PACK_START, "BTK_PACK_START", "start" },
            { BTK_PACK_END, "BTK_PACK_END", "end" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkPackType"), values);
    }
    return etype;
}
GType
btk_path_priority_type_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_PATH_PRIO_LOWEST, "BTK_PATH_PRIO_LOWEST", "lowest" },
            { BTK_PATH_PRIO_BTK, "BTK_PATH_PRIO_BTK", "btk" },
            { BTK_PATH_PRIO_APPLICATION, "BTK_PATH_PRIO_APPLICATION", "application" },
            { BTK_PATH_PRIO_THEME, "BTK_PATH_PRIO_THEME", "theme" },
            { BTK_PATH_PRIO_RC, "BTK_PATH_PRIO_RC", "rc" },
            { BTK_PATH_PRIO_HIGHEST, "BTK_PATH_PRIO_HIGHEST", "highest" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkPathPriorityType"), values);
    }
    return etype;
}
GType
btk_path_type_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_PATH_WIDGET, "BTK_PATH_WIDGET", "widget" },
            { BTK_PATH_WIDGET_CLASS, "BTK_PATH_WIDGET_CLASS", "widget-class" },
            { BTK_PATH_CLASS, "BTK_PATH_CLASS", "class" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkPathType"), values);
    }
    return etype;
}
GType
btk_policy_type_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_POLICY_ALWAYS, "BTK_POLICY_ALWAYS", "always" },
            { BTK_POLICY_AUTOMATIC, "BTK_POLICY_AUTOMATIC", "automatic" },
            { BTK_POLICY_NEVER, "BTK_POLICY_NEVER", "never" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkPolicyType"), values);
    }
    return etype;
}
GType
btk_position_type_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_POS_LEFT, "BTK_POS_LEFT", "left" },
            { BTK_POS_RIGHT, "BTK_POS_RIGHT", "right" },
            { BTK_POS_TOP, "BTK_POS_TOP", "top" },
            { BTK_POS_BOTTOM, "BTK_POS_BOTTOM", "bottom" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkPositionType"), values);
    }
    return etype;
}
GType
btk_preview_type_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_PREVIEW_COLOR, "BTK_PREVIEW_COLOR", "color" },
            { BTK_PREVIEW_GRAYSCALE, "BTK_PREVIEW_GRAYSCALE", "grayscale" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkPreviewType"), values);
    }
    return etype;
}
GType
btk_relief_style_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_RELIEF_NORMAL, "BTK_RELIEF_NORMAL", "normal" },
            { BTK_RELIEF_HALF, "BTK_RELIEF_HALF", "half" },
            { BTK_RELIEF_NONE, "BTK_RELIEF_NONE", "none" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkReliefStyle"), values);
    }
    return etype;
}
GType
btk_resize_mode_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_RESIZE_PARENT, "BTK_RESIZE_PARENT", "parent" },
            { BTK_RESIZE_QUEUE, "BTK_RESIZE_QUEUE", "queue" },
            { BTK_RESIZE_IMMEDIATE, "BTK_RESIZE_IMMEDIATE", "immediate" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkResizeMode"), values);
    }
    return etype;
}
GType
btk_signal_run_type_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GFlagsValue values[] = {
            { BTK_RUN_FIRST, "BTK_RUN_FIRST", "first" },
            { BTK_RUN_LAST, "BTK_RUN_LAST", "last" },
            { BTK_RUN_BOTH, "BTK_RUN_BOTH", "both" },
            { BTK_RUN_NO_RECURSE, "BTK_RUN_NO_RECURSE", "no-recurse" },
            { BTK_RUN_ACTION, "BTK_RUN_ACTION", "action" },
            { BTK_RUN_NO_HOOKS, "BTK_RUN_NO_HOOKS", "no-hooks" },
            { 0, NULL, NULL }
        };
        etype = g_flags_register_static (g_intern_static_string ("BtkSignalRunType"), values);
    }
    return etype;
}
GType
btk_scroll_type_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_SCROLL_NONE, "BTK_SCROLL_NONE", "none" },
            { BTK_SCROLL_JUMP, "BTK_SCROLL_JUMP", "jump" },
            { BTK_SCROLL_STEP_BACKWARD, "BTK_SCROLL_STEP_BACKWARD", "step-backward" },
            { BTK_SCROLL_STEP_FORWARD, "BTK_SCROLL_STEP_FORWARD", "step-forward" },
            { BTK_SCROLL_PAGE_BACKWARD, "BTK_SCROLL_PAGE_BACKWARD", "page-backward" },
            { BTK_SCROLL_PAGE_FORWARD, "BTK_SCROLL_PAGE_FORWARD", "page-forward" },
            { BTK_SCROLL_STEP_UP, "BTK_SCROLL_STEP_UP", "step-up" },
            { BTK_SCROLL_STEP_DOWN, "BTK_SCROLL_STEP_DOWN", "step-down" },
            { BTK_SCROLL_PAGE_UP, "BTK_SCROLL_PAGE_UP", "page-up" },
            { BTK_SCROLL_PAGE_DOWN, "BTK_SCROLL_PAGE_DOWN", "page-down" },
            { BTK_SCROLL_STEP_LEFT, "BTK_SCROLL_STEP_LEFT", "step-left" },
            { BTK_SCROLL_STEP_RIGHT, "BTK_SCROLL_STEP_RIGHT", "step-right" },
            { BTK_SCROLL_PAGE_LEFT, "BTK_SCROLL_PAGE_LEFT", "page-left" },
            { BTK_SCROLL_PAGE_RIGHT, "BTK_SCROLL_PAGE_RIGHT", "page-right" },
            { BTK_SCROLL_START, "BTK_SCROLL_START", "start" },
            { BTK_SCROLL_END, "BTK_SCROLL_END", "end" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkScrollType"), values);
    }
    return etype;
}
GType
btk_selection_mode_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_SELECTION_NONE, "BTK_SELECTION_NONE", "none" },
            { BTK_SELECTION_SINGLE, "BTK_SELECTION_SINGLE", "single" },
            { BTK_SELECTION_BROWSE, "BTK_SELECTION_BROWSE", "browse" },
            { BTK_SELECTION_MULTIPLE, "BTK_SELECTION_MULTIPLE", "multiple" },
            { BTK_SELECTION_EXTENDED, "BTK_SELECTION_EXTENDED", "extended" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkSelectionMode"), values);
    }
    return etype;
}
GType
btk_shadow_type_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_SHADOW_NONE, "BTK_SHADOW_NONE", "none" },
            { BTK_SHADOW_IN, "BTK_SHADOW_IN", "in" },
            { BTK_SHADOW_OUT, "BTK_SHADOW_OUT", "out" },
            { BTK_SHADOW_ETCHED_IN, "BTK_SHADOW_ETCHED_IN", "etched-in" },
            { BTK_SHADOW_ETCHED_OUT, "BTK_SHADOW_ETCHED_OUT", "etched-out" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkShadowType"), values);
    }
    return etype;
}
GType
btk_state_type_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_STATE_NORMAL, "BTK_STATE_NORMAL", "normal" },
            { BTK_STATE_ACTIVE, "BTK_STATE_ACTIVE", "active" },
            { BTK_STATE_PRELIGHT, "BTK_STATE_PRELIGHT", "prelight" },
            { BTK_STATE_SELECTED, "BTK_STATE_SELECTED", "selected" },
            { BTK_STATE_INSENSITIVE, "BTK_STATE_INSENSITIVE", "insensitive" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkStateType"), values);
    }
    return etype;
}
GType
btk_submenu_direction_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_DIRECTION_LEFT, "BTK_DIRECTION_LEFT", "left" },
            { BTK_DIRECTION_RIGHT, "BTK_DIRECTION_RIGHT", "right" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkSubmenuDirection"), values);
    }
    return etype;
}
GType
btk_submenu_placement_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_TOP_BOTTOM, "BTK_TOP_BOTTOM", "top-bottom" },
            { BTK_LEFT_RIGHT, "BTK_LEFT_RIGHT", "left-right" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkSubmenuPlacement"), values);
    }
    return etype;
}
GType
btk_toolbar_style_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_TOOLBAR_ICONS, "BTK_TOOLBAR_ICONS", "icons" },
            { BTK_TOOLBAR_TEXT, "BTK_TOOLBAR_TEXT", "text" },
            { BTK_TOOLBAR_BOTH, "BTK_TOOLBAR_BOTH", "both" },
            { BTK_TOOLBAR_BOTH_HORIZ, "BTK_TOOLBAR_BOTH_HORIZ", "both-horiz" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkToolbarStyle"), values);
    }
    return etype;
}
GType
btk_update_type_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_UPDATE_CONTINUOUS, "BTK_UPDATE_CONTINUOUS", "continuous" },
            { BTK_UPDATE_DISCONTINUOUS, "BTK_UPDATE_DISCONTINUOUS", "discontinuous" },
            { BTK_UPDATE_DELAYED, "BTK_UPDATE_DELAYED", "delayed" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkUpdateType"), values);
    }
    return etype;
}
GType
btk_visibility_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_VISIBILITY_NONE, "BTK_VISIBILITY_NONE", "none" },
            { BTK_VISIBILITY_PARTIAL, "BTK_VISIBILITY_PARTIAL", "partial" },
            { BTK_VISIBILITY_FULL, "BTK_VISIBILITY_FULL", "full" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkVisibility"), values);
    }
    return etype;
}
GType
btk_window_position_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_WIN_POS_NONE, "BTK_WIN_POS_NONE", "none" },
            { BTK_WIN_POS_CENTER, "BTK_WIN_POS_CENTER", "center" },
            { BTK_WIN_POS_MOUSE, "BTK_WIN_POS_MOUSE", "mouse" },
            { BTK_WIN_POS_CENTER_ALWAYS, "BTK_WIN_POS_CENTER_ALWAYS", "center-always" },
            { BTK_WIN_POS_CENTER_ON_PARENT, "BTK_WIN_POS_CENTER_ON_PARENT", "center-on-parent" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkWindowPosition"), values);
    }
    return etype;
}
GType
btk_window_type_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_WINDOW_TOPLEVEL, "BTK_WINDOW_TOPLEVEL", "toplevel" },
            { BTK_WINDOW_POPUP, "BTK_WINDOW_POPUP", "popup" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkWindowType"), values);
    }
    return etype;
}
GType
btk_wrap_mode_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_WRAP_NONE, "BTK_WRAP_NONE", "none" },
            { BTK_WRAP_CHAR, "BTK_WRAP_CHAR", "char" },
            { BTK_WRAP_WORD, "BTK_WRAP_WORD", "word" },
            { BTK_WRAP_WORD_CHAR, "BTK_WRAP_WORD_CHAR", "word-char" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkWrapMode"), values);
    }
    return etype;
}
GType
btk_sort_type_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_SORT_ASCENDING, "BTK_SORT_ASCENDING", "ascending" },
            { BTK_SORT_DESCENDING, "BTK_SORT_DESCENDING", "descending" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkSortType"), values);
    }
    return etype;
}
GType
btk_im_preedit_style_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_IM_PREEDIT_NOTHING, "BTK_IM_PREEDIT_NOTHING", "nothing" },
            { BTK_IM_PREEDIT_CALLBACK, "BTK_IM_PREEDIT_CALLBACK", "callback" },
            { BTK_IM_PREEDIT_NONE, "BTK_IM_PREEDIT_NONE", "none" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkIMPreeditStyle"), values);
    }
    return etype;
}
GType
btk_im_status_style_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_IM_STATUS_NOTHING, "BTK_IM_STATUS_NOTHING", "nothing" },
            { BTK_IM_STATUS_CALLBACK, "BTK_IM_STATUS_CALLBACK", "callback" },
            { BTK_IM_STATUS_NONE, "BTK_IM_STATUS_NONE", "none" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkIMStatusStyle"), values);
    }
    return etype;
}
GType
btk_pack_direction_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_PACK_DIRECTION_LTR, "BTK_PACK_DIRECTION_LTR", "ltr" },
            { BTK_PACK_DIRECTION_RTL, "BTK_PACK_DIRECTION_RTL", "rtl" },
            { BTK_PACK_DIRECTION_TTB, "BTK_PACK_DIRECTION_TTB", "ttb" },
            { BTK_PACK_DIRECTION_BTT, "BTK_PACK_DIRECTION_BTT", "btt" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkPackDirection"), values);
    }
    return etype;
}
GType
btk_print_pages_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_PRINT_PAGES_ALL, "BTK_PRINT_PAGES_ALL", "all" },
            { BTK_PRINT_PAGES_CURRENT, "BTK_PRINT_PAGES_CURRENT", "current" },
            { BTK_PRINT_PAGES_RANGES, "BTK_PRINT_PAGES_RANGES", "ranges" },
            { BTK_PRINT_PAGES_SELECTION, "BTK_PRINT_PAGES_SELECTION", "selection" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkPrintPages"), values);
    }
    return etype;
}
GType
btk_page_set_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_PAGE_SET_ALL, "BTK_PAGE_SET_ALL", "all" },
            { BTK_PAGE_SET_EVEN, "BTK_PAGE_SET_EVEN", "even" },
            { BTK_PAGE_SET_ODD, "BTK_PAGE_SET_ODD", "odd" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkPageSet"), values);
    }
    return etype;
}
GType
btk_number_up_layout_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_NUMBER_UP_LAYOUT_LEFT_TO_RIGHT_TOP_TO_BOTTOM, "BTK_NUMBER_UP_LAYOUT_LEFT_TO_RIGHT_TOP_TO_BOTTOM", "lrtb" },
            { BTK_NUMBER_UP_LAYOUT_LEFT_TO_RIGHT_BOTTOM_TO_TOP, "BTK_NUMBER_UP_LAYOUT_LEFT_TO_RIGHT_BOTTOM_TO_TOP", "lrbt" },
            { BTK_NUMBER_UP_LAYOUT_RIGHT_TO_LEFT_TOP_TO_BOTTOM, "BTK_NUMBER_UP_LAYOUT_RIGHT_TO_LEFT_TOP_TO_BOTTOM", "rltb" },
            { BTK_NUMBER_UP_LAYOUT_RIGHT_TO_LEFT_BOTTOM_TO_TOP, "BTK_NUMBER_UP_LAYOUT_RIGHT_TO_LEFT_BOTTOM_TO_TOP", "rlbt" },
            { BTK_NUMBER_UP_LAYOUT_TOP_TO_BOTTOM_LEFT_TO_RIGHT, "BTK_NUMBER_UP_LAYOUT_TOP_TO_BOTTOM_LEFT_TO_RIGHT", "tblr" },
            { BTK_NUMBER_UP_LAYOUT_TOP_TO_BOTTOM_RIGHT_TO_LEFT, "BTK_NUMBER_UP_LAYOUT_TOP_TO_BOTTOM_RIGHT_TO_LEFT", "tbrl" },
            { BTK_NUMBER_UP_LAYOUT_BOTTOM_TO_TOP_LEFT_TO_RIGHT, "BTK_NUMBER_UP_LAYOUT_BOTTOM_TO_TOP_LEFT_TO_RIGHT", "btlr" },
            { BTK_NUMBER_UP_LAYOUT_BOTTOM_TO_TOP_RIGHT_TO_LEFT, "BTK_NUMBER_UP_LAYOUT_BOTTOM_TO_TOP_RIGHT_TO_LEFT", "btrl" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkNumberUpLayout"), values);
    }
    return etype;
}
GType
btk_page_orientation_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_PAGE_ORIENTATION_PORTRAIT, "BTK_PAGE_ORIENTATION_PORTRAIT", "portrait" },
            { BTK_PAGE_ORIENTATION_LANDSCAPE, "BTK_PAGE_ORIENTATION_LANDSCAPE", "landscape" },
            { BTK_PAGE_ORIENTATION_REVERSE_PORTRAIT, "BTK_PAGE_ORIENTATION_REVERSE_PORTRAIT", "reverse-portrait" },
            { BTK_PAGE_ORIENTATION_REVERSE_LANDSCAPE, "BTK_PAGE_ORIENTATION_REVERSE_LANDSCAPE", "reverse-landscape" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkPageOrientation"), values);
    }
    return etype;
}
GType
btk_print_quality_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_PRINT_QUALITY_LOW, "BTK_PRINT_QUALITY_LOW", "low" },
            { BTK_PRINT_QUALITY_NORMAL, "BTK_PRINT_QUALITY_NORMAL", "normal" },
            { BTK_PRINT_QUALITY_HIGH, "BTK_PRINT_QUALITY_HIGH", "high" },
            { BTK_PRINT_QUALITY_DRAFT, "BTK_PRINT_QUALITY_DRAFT", "draft" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkPrintQuality"), values);
    }
    return etype;
}
GType
btk_print_duplex_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_PRINT_DUPLEX_SIMPLEX, "BTK_PRINT_DUPLEX_SIMPLEX", "simplex" },
            { BTK_PRINT_DUPLEX_HORIZONTAL, "BTK_PRINT_DUPLEX_HORIZONTAL", "horizontal" },
            { BTK_PRINT_DUPLEX_VERTICAL, "BTK_PRINT_DUPLEX_VERTICAL", "vertical" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkPrintDuplex"), values);
    }
    return etype;
}
GType
btk_unit_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_UNIT_PIXEL, "BTK_UNIT_PIXEL", "pixel" },
            { BTK_UNIT_POINTS, "BTK_UNIT_POINTS", "points" },
            { BTK_UNIT_INCH, "BTK_UNIT_INCH", "inch" },
            { BTK_UNIT_MM, "BTK_UNIT_MM", "mm" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkUnit"), values);
    }
    return etype;
}
GType
btk_tree_view_grid_lines_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_TREE_VIEW_GRID_LINES_NONE, "BTK_TREE_VIEW_GRID_LINES_NONE", "none" },
            { BTK_TREE_VIEW_GRID_LINES_HORIZONTAL, "BTK_TREE_VIEW_GRID_LINES_HORIZONTAL", "horizontal" },
            { BTK_TREE_VIEW_GRID_LINES_VERTICAL, "BTK_TREE_VIEW_GRID_LINES_VERTICAL", "vertical" },
            { BTK_TREE_VIEW_GRID_LINES_BOTH, "BTK_TREE_VIEW_GRID_LINES_BOTH", "both" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkTreeViewGridLines"), values);
    }
    return etype;
}
GType
btk_drag_result_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_DRAG_RESULT_SUCCESS, "BTK_DRAG_RESULT_SUCCESS", "success" },
            { BTK_DRAG_RESULT_NO_TARGET, "BTK_DRAG_RESULT_NO_TARGET", "no-target" },
            { BTK_DRAG_RESULT_USER_CANCELLED, "BTK_DRAG_RESULT_USER_CANCELLED", "user-cancelled" },
            { BTK_DRAG_RESULT_TIMEOUT_EXPIRED, "BTK_DRAG_RESULT_TIMEOUT_EXPIRED", "timeout-expired" },
            { BTK_DRAG_RESULT_GRAB_BROKEN, "BTK_DRAG_RESULT_GRAB_BROKEN", "grab-broken" },
            { BTK_DRAG_RESULT_ERROR, "BTK_DRAG_RESULT_ERROR", "error" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkDragResult"), values);
    }
    return etype;
}
/* enumerations from "btkfilechooser.h" */
GType
btk_file_chooser_action_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_FILE_CHOOSER_ACTION_OPEN, "BTK_FILE_CHOOSER_ACTION_OPEN", "open" },
            { BTK_FILE_CHOOSER_ACTION_SAVE, "BTK_FILE_CHOOSER_ACTION_SAVE", "save" },
            { BTK_FILE_CHOOSER_ACTION_SELECT_FOLDER, "BTK_FILE_CHOOSER_ACTION_SELECT_FOLDER", "select-folder" },
            { BTK_FILE_CHOOSER_ACTION_CREATE_FOLDER, "BTK_FILE_CHOOSER_ACTION_CREATE_FOLDER", "create-folder" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkFileChooserAction"), values);
    }
    return etype;
}
GType
btk_file_chooser_confirmation_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_FILE_CHOOSER_CONFIRMATION_CONFIRM, "BTK_FILE_CHOOSER_CONFIRMATION_CONFIRM", "confirm" },
            { BTK_FILE_CHOOSER_CONFIRMATION_ACCEPT_FILENAME, "BTK_FILE_CHOOSER_CONFIRMATION_ACCEPT_FILENAME", "accept-filename" },
            { BTK_FILE_CHOOSER_CONFIRMATION_SELECT_AGAIN, "BTK_FILE_CHOOSER_CONFIRMATION_SELECT_AGAIN", "select-again" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkFileChooserConfirmation"), values);
    }
    return etype;
}
GType
btk_file_chooser_error_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_FILE_CHOOSER_ERROR_NONEXISTENT, "BTK_FILE_CHOOSER_ERROR_NONEXISTENT", "nonexistent" },
            { BTK_FILE_CHOOSER_ERROR_BAD_FILENAME, "BTK_FILE_CHOOSER_ERROR_BAD_FILENAME", "bad-filename" },
            { BTK_FILE_CHOOSER_ERROR_ALREADY_EXISTS, "BTK_FILE_CHOOSER_ERROR_ALREADY_EXISTS", "already-exists" },
            { BTK_FILE_CHOOSER_ERROR_INCOMPLETE_HOSTNAME, "BTK_FILE_CHOOSER_ERROR_INCOMPLETE_HOSTNAME", "incomplete-hostname" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkFileChooserError"), values);
    }
    return etype;
}
/* enumerations from "btkfilefilter.h" */
GType
btk_file_filter_flags_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GFlagsValue values[] = {
            { BTK_FILE_FILTER_FILENAME, "BTK_FILE_FILTER_FILENAME", "filename" },
            { BTK_FILE_FILTER_URI, "BTK_FILE_FILTER_URI", "uri" },
            { BTK_FILE_FILTER_DISPLAY_NAME, "BTK_FILE_FILTER_DISPLAY_NAME", "display-name" },
            { BTK_FILE_FILTER_MIME_TYPE, "BTK_FILE_FILTER_MIME_TYPE", "mime-type" },
            { 0, NULL, NULL }
        };
        etype = g_flags_register_static (g_intern_static_string ("BtkFileFilterFlags"), values);
    }
    return etype;
}
/* enumerations from "btkicontheme.h" */
GType
btk_icon_lookup_flags_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GFlagsValue values[] = {
            { BTK_ICON_LOOKUP_NO_SVG, "BTK_ICON_LOOKUP_NO_SVG", "no-svg" },
            { BTK_ICON_LOOKUP_FORCE_SVG, "BTK_ICON_LOOKUP_FORCE_SVG", "force-svg" },
            { BTK_ICON_LOOKUP_USE_BUILTIN, "BTK_ICON_LOOKUP_USE_BUILTIN", "use-builtin" },
            { BTK_ICON_LOOKUP_GENERIC_FALLBACK, "BTK_ICON_LOOKUP_GENERIC_FALLBACK", "generic-fallback" },
            { BTK_ICON_LOOKUP_FORCE_SIZE, "BTK_ICON_LOOKUP_FORCE_SIZE", "force-size" },
            { 0, NULL, NULL }
        };
        etype = g_flags_register_static (g_intern_static_string ("BtkIconLookupFlags"), values);
    }
    return etype;
}
GType
btk_icon_theme_error_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_ICON_THEME_NOT_FOUND, "BTK_ICON_THEME_NOT_FOUND", "not-found" },
            { BTK_ICON_THEME_FAILED, "BTK_ICON_THEME_FAILED", "failed" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkIconThemeError"), values);
    }
    return etype;
}
/* enumerations from "btkiconview.h" */
GType
btk_icon_view_drop_position_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_ICON_VIEW_NO_DROP, "BTK_ICON_VIEW_NO_DROP", "no-drop" },
            { BTK_ICON_VIEW_DROP_INTO, "BTK_ICON_VIEW_DROP_INTO", "drop-into" },
            { BTK_ICON_VIEW_DROP_LEFT, "BTK_ICON_VIEW_DROP_LEFT", "drop-left" },
            { BTK_ICON_VIEW_DROP_RIGHT, "BTK_ICON_VIEW_DROP_RIGHT", "drop-right" },
            { BTK_ICON_VIEW_DROP_ABOVE, "BTK_ICON_VIEW_DROP_ABOVE", "drop-above" },
            { BTK_ICON_VIEW_DROP_BELOW, "BTK_ICON_VIEW_DROP_BELOW", "drop-below" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkIconViewDropPosition"), values);
    }
    return etype;
}
/* enumerations from "btkimage.h" */
GType
btk_image_type_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_IMAGE_EMPTY, "BTK_IMAGE_EMPTY", "empty" },
            { BTK_IMAGE_PIXMAP, "BTK_IMAGE_PIXMAP", "pixmap" },
            { BTK_IMAGE_IMAGE, "BTK_IMAGE_IMAGE", "image" },
            { BTK_IMAGE_PIXBUF, "BTK_IMAGE_PIXBUF", "pixbuf" },
            { BTK_IMAGE_STOCK, "BTK_IMAGE_STOCK", "stock" },
            { BTK_IMAGE_ICON_SET, "BTK_IMAGE_ICON_SET", "icon-set" },
            { BTK_IMAGE_ANIMATION, "BTK_IMAGE_ANIMATION", "animation" },
            { BTK_IMAGE_ICON_NAME, "BTK_IMAGE_ICON_NAME", "icon-name" },
            { BTK_IMAGE_GICON, "BTK_IMAGE_GICON", "gicon" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkImageType"), values);
    }
    return etype;
}
/* enumerations from "btkmessagedialog.h" */
GType
btk_buttons_type_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_BUTTONS_NONE, "BTK_BUTTONS_NONE", "none" },
            { BTK_BUTTONS_OK, "BTK_BUTTONS_OK", "ok" },
            { BTK_BUTTONS_CLOSE, "BTK_BUTTONS_CLOSE", "close" },
            { BTK_BUTTONS_CANCEL, "BTK_BUTTONS_CANCEL", "cancel" },
            { BTK_BUTTONS_YES_NO, "BTK_BUTTONS_YES_NO", "yes-no" },
            { BTK_BUTTONS_OK_CANCEL, "BTK_BUTTONS_OK_CANCEL", "ok-cancel" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkButtonsType"), values);
    }
    return etype;
}
/* enumerations from "btknotebook.h" */
GType
btk_notebook_tab_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_NOTEBOOK_TAB_FIRST, "BTK_NOTEBOOK_TAB_FIRST", "first" },
            { BTK_NOTEBOOK_TAB_LAST, "BTK_NOTEBOOK_TAB_LAST", "last" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkNotebookTab"), values);
    }
    return etype;
}
/* enumerations from "btkobject.h" */
GType
btk_object_flags_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GFlagsValue values[] = {
            { BTK_IN_DESTRUCTION, "BTK_IN_DESTRUCTION", "in-destruction" },
            { BTK_FLOATING, "BTK_FLOATING", "floating" },
            { BTK_RESERVED_1, "BTK_RESERVED_1", "reserved-1" },
            { BTK_RESERVED_2, "BTK_RESERVED_2", "reserved-2" },
            { 0, NULL, NULL }
        };
        etype = g_flags_register_static (g_intern_static_string ("BtkObjectFlags"), values);
    }
    return etype;
}
GType
btk_arg_flags_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GFlagsValue values[] = {
            { BTK_ARG_READABLE, "BTK_ARG_READABLE", "readable" },
            { BTK_ARG_WRITABLE, "BTK_ARG_WRITABLE", "writable" },
            { BTK_ARG_CONSTRUCT, "BTK_ARG_CONSTRUCT", "construct" },
            { BTK_ARG_CONSTRUCT_ONLY, "BTK_ARG_CONSTRUCT_ONLY", "construct-only" },
            { BTK_ARG_CHILD_ARG, "BTK_ARG_CHILD_ARG", "child-arg" },
            { 0, NULL, NULL }
        };
        etype = g_flags_register_static (g_intern_static_string ("BtkArgFlags"), values);
    }
    return etype;
}
/* enumerations from "btkprintoperation.h" */
GType
btk_print_status_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_PRINT_STATUS_INITIAL, "BTK_PRINT_STATUS_INITIAL", "initial" },
            { BTK_PRINT_STATUS_PREPARING, "BTK_PRINT_STATUS_PREPARING", "preparing" },
            { BTK_PRINT_STATUS_GENERATING_DATA, "BTK_PRINT_STATUS_GENERATING_DATA", "generating-data" },
            { BTK_PRINT_STATUS_SENDING_DATA, "BTK_PRINT_STATUS_SENDING_DATA", "sending-data" },
            { BTK_PRINT_STATUS_PENDING, "BTK_PRINT_STATUS_PENDING", "pending" },
            { BTK_PRINT_STATUS_PENDING_ISSUE, "BTK_PRINT_STATUS_PENDING_ISSUE", "pending-issue" },
            { BTK_PRINT_STATUS_PRINTING, "BTK_PRINT_STATUS_PRINTING", "printing" },
            { BTK_PRINT_STATUS_FINISHED, "BTK_PRINT_STATUS_FINISHED", "finished" },
            { BTK_PRINT_STATUS_FINISHED_ABORTED, "BTK_PRINT_STATUS_FINISHED_ABORTED", "finished-aborted" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkPrintStatus"), values);
    }
    return etype;
}
GType
btk_print_operation_result_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_PRINT_OPERATION_RESULT_ERROR, "BTK_PRINT_OPERATION_RESULT_ERROR", "error" },
            { BTK_PRINT_OPERATION_RESULT_APPLY, "BTK_PRINT_OPERATION_RESULT_APPLY", "apply" },
            { BTK_PRINT_OPERATION_RESULT_CANCEL, "BTK_PRINT_OPERATION_RESULT_CANCEL", "cancel" },
            { BTK_PRINT_OPERATION_RESULT_IN_PROGRESS, "BTK_PRINT_OPERATION_RESULT_IN_PROGRESS", "in-progress" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkPrintOperationResult"), values);
    }
    return etype;
}
GType
btk_print_operation_action_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_PRINT_OPERATION_ACTION_PRINT_DIALOG, "BTK_PRINT_OPERATION_ACTION_PRINT_DIALOG", "print-dialog" },
            { BTK_PRINT_OPERATION_ACTION_PRINT, "BTK_PRINT_OPERATION_ACTION_PRINT", "print" },
            { BTK_PRINT_OPERATION_ACTION_PREVIEW, "BTK_PRINT_OPERATION_ACTION_PREVIEW", "preview" },
            { BTK_PRINT_OPERATION_ACTION_EXPORT, "BTK_PRINT_OPERATION_ACTION_EXPORT", "export" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkPrintOperationAction"), values);
    }
    return etype;
}
GType
btk_print_error_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_PRINT_ERROR_GENERAL, "BTK_PRINT_ERROR_GENERAL", "general" },
            { BTK_PRINT_ERROR_INTERNAL_ERROR, "BTK_PRINT_ERROR_INTERNAL_ERROR", "internal-error" },
            { BTK_PRINT_ERROR_NOMEM, "BTK_PRINT_ERROR_NOMEM", "nomem" },
            { BTK_PRINT_ERROR_INVALID_FILE, "BTK_PRINT_ERROR_INVALID_FILE", "invalid-file" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkPrintError"), values);
    }
    return etype;
}
/* enumerations from "btkprivate.h" */
GType
btk_private_flags_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GFlagsValue values[] = {
            { PRIVATE_BTK_USER_STYLE, "PRIVATE_BTK_USER_STYLE", "user-style" },
            { PRIVATE_BTK_RESIZE_PENDING, "PRIVATE_BTK_RESIZE_PENDING", "resize-pending" },
            { PRIVATE_BTK_HAS_POINTER, "PRIVATE_BTK_HAS_POINTER", "has-pointer" },
            { PRIVATE_BTK_SHADOWED, "PRIVATE_BTK_SHADOWED", "shadowed" },
            { PRIVATE_BTK_HAS_SHAPE_MASK, "PRIVATE_BTK_HAS_SHAPE_MASK", "has-shape-mask" },
            { PRIVATE_BTK_IN_REPARENT, "PRIVATE_BTK_IN_REPARENT", "in-reparent" },
            { PRIVATE_BTK_DIRECTION_SET, "PRIVATE_BTK_DIRECTION_SET", "direction-set" },
            { PRIVATE_BTK_DIRECTION_LTR, "PRIVATE_BTK_DIRECTION_LTR", "direction-ltr" },
            { PRIVATE_BTK_ANCHORED, "PRIVATE_BTK_ANCHORED", "anchored" },
            { PRIVATE_BTK_CHILD_VISIBLE, "PRIVATE_BTK_CHILD_VISIBLE", "child-visible" },
            { PRIVATE_BTK_REDRAW_ON_ALLOC, "PRIVATE_BTK_REDRAW_ON_ALLOC", "redraw-on-alloc" },
            { PRIVATE_BTK_ALLOC_NEEDED, "PRIVATE_BTK_ALLOC_NEEDED", "alloc-needed" },
            { PRIVATE_BTK_REQUEST_NEEDED, "PRIVATE_BTK_REQUEST_NEEDED", "request-needed" },
            { 0, NULL, NULL }
        };
        etype = g_flags_register_static (g_intern_static_string ("BtkPrivateFlags"), values);
    }
    return etype;
}
/* enumerations from "btkprogressbar.h" */
GType
btk_progress_bar_style_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_PROGRESS_CONTINUOUS, "BTK_PROGRESS_CONTINUOUS", "continuous" },
            { BTK_PROGRESS_DISCRETE, "BTK_PROGRESS_DISCRETE", "discrete" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkProgressBarStyle"), values);
    }
    return etype;
}
GType
btk_progress_bar_orientation_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_PROGRESS_LEFT_TO_RIGHT, "BTK_PROGRESS_LEFT_TO_RIGHT", "left-to-right" },
            { BTK_PROGRESS_RIGHT_TO_LEFT, "BTK_PROGRESS_RIGHT_TO_LEFT", "right-to-left" },
            { BTK_PROGRESS_BOTTOM_TO_TOP, "BTK_PROGRESS_BOTTOM_TO_TOP", "bottom-to-top" },
            { BTK_PROGRESS_TOP_TO_BOTTOM, "BTK_PROGRESS_TOP_TO_BOTTOM", "top-to-bottom" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkProgressBarOrientation"), values);
    }
    return etype;
}
/* enumerations from "btkrc.h" */
GType
btk_rc_flags_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GFlagsValue values[] = {
            { BTK_RC_FG, "BTK_RC_FG", "fg" },
            { BTK_RC_BG, "BTK_RC_BG", "bg" },
            { BTK_RC_TEXT, "BTK_RC_TEXT", "text" },
            { BTK_RC_BASE, "BTK_RC_BASE", "base" },
            { 0, NULL, NULL }
        };
        etype = g_flags_register_static (g_intern_static_string ("BtkRcFlags"), values);
    }
    return etype;
}
GType
btk_rc_token_type_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_RC_TOKEN_INVALID, "BTK_RC_TOKEN_INVALID", "invalid" },
            { BTK_RC_TOKEN_INCLUDE, "BTK_RC_TOKEN_INCLUDE", "include" },
            { BTK_RC_TOKEN_NORMAL, "BTK_RC_TOKEN_NORMAL", "normal" },
            { BTK_RC_TOKEN_ACTIVE, "BTK_RC_TOKEN_ACTIVE", "active" },
            { BTK_RC_TOKEN_PRELIGHT, "BTK_RC_TOKEN_PRELIGHT", "prelight" },
            { BTK_RC_TOKEN_SELECTED, "BTK_RC_TOKEN_SELECTED", "selected" },
            { BTK_RC_TOKEN_INSENSITIVE, "BTK_RC_TOKEN_INSENSITIVE", "insensitive" },
            { BTK_RC_TOKEN_FG, "BTK_RC_TOKEN_FG", "fg" },
            { BTK_RC_TOKEN_BG, "BTK_RC_TOKEN_BG", "bg" },
            { BTK_RC_TOKEN_TEXT, "BTK_RC_TOKEN_TEXT", "text" },
            { BTK_RC_TOKEN_BASE, "BTK_RC_TOKEN_BASE", "base" },
            { BTK_RC_TOKEN_XTHICKNESS, "BTK_RC_TOKEN_XTHICKNESS", "xthickness" },
            { BTK_RC_TOKEN_YTHICKNESS, "BTK_RC_TOKEN_YTHICKNESS", "ythickness" },
            { BTK_RC_TOKEN_FONT, "BTK_RC_TOKEN_FONT", "font" },
            { BTK_RC_TOKEN_FONTSET, "BTK_RC_TOKEN_FONTSET", "fontset" },
            { BTK_RC_TOKEN_FONT_NAME, "BTK_RC_TOKEN_FONT_NAME", "font-name" },
            { BTK_RC_TOKEN_BG_PIXMAP, "BTK_RC_TOKEN_BG_PIXMAP", "bg-pixmap" },
            { BTK_RC_TOKEN_PIXMAP_PATH, "BTK_RC_TOKEN_PIXMAP_PATH", "pixmap-path" },
            { BTK_RC_TOKEN_STYLE, "BTK_RC_TOKEN_STYLE", "style" },
            { BTK_RC_TOKEN_BINDING, "BTK_RC_TOKEN_BINDING", "binding" },
            { BTK_RC_TOKEN_BIND, "BTK_RC_TOKEN_BIND", "bind" },
            { BTK_RC_TOKEN_WIDGET, "BTK_RC_TOKEN_WIDGET", "widget" },
            { BTK_RC_TOKEN_WIDGET_CLASS, "BTK_RC_TOKEN_WIDGET_CLASS", "widget-class" },
            { BTK_RC_TOKEN_CLASS, "BTK_RC_TOKEN_CLASS", "class" },
            { BTK_RC_TOKEN_LOWEST, "BTK_RC_TOKEN_LOWEST", "lowest" },
            { BTK_RC_TOKEN_BTK, "BTK_RC_TOKEN_BTK", "btk" },
            { BTK_RC_TOKEN_APPLICATION, "BTK_RC_TOKEN_APPLICATION", "application" },
            { BTK_RC_TOKEN_THEME, "BTK_RC_TOKEN_THEME", "theme" },
            { BTK_RC_TOKEN_RC, "BTK_RC_TOKEN_RC", "rc" },
            { BTK_RC_TOKEN_HIGHEST, "BTK_RC_TOKEN_HIGHEST", "highest" },
            { BTK_RC_TOKEN_ENGINE, "BTK_RC_TOKEN_ENGINE", "engine" },
            { BTK_RC_TOKEN_MODULE_PATH, "BTK_RC_TOKEN_MODULE_PATH", "module-path" },
            { BTK_RC_TOKEN_IM_MODULE_PATH, "BTK_RC_TOKEN_IM_MODULE_PATH", "im-module-path" },
            { BTK_RC_TOKEN_IM_MODULE_FILE, "BTK_RC_TOKEN_IM_MODULE_FILE", "im-module-file" },
            { BTK_RC_TOKEN_STOCK, "BTK_RC_TOKEN_STOCK", "stock" },
            { BTK_RC_TOKEN_LTR, "BTK_RC_TOKEN_LTR", "ltr" },
            { BTK_RC_TOKEN_RTL, "BTK_RC_TOKEN_RTL", "rtl" },
            { BTK_RC_TOKEN_COLOR, "BTK_RC_TOKEN_COLOR", "color" },
            { BTK_RC_TOKEN_UNBIND, "BTK_RC_TOKEN_UNBIND", "unbind" },
            { BTK_RC_TOKEN_LAST, "BTK_RC_TOKEN_LAST", "last" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkRcTokenType"), values);
    }
    return etype;
}
/* enumerations from "btkrecentchooser.h" */
GType
btk_recent_sort_type_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_RECENT_SORT_NONE, "BTK_RECENT_SORT_NONE", "none" },
            { BTK_RECENT_SORT_MRU, "BTK_RECENT_SORT_MRU", "mru" },
            { BTK_RECENT_SORT_LRU, "BTK_RECENT_SORT_LRU", "lru" },
            { BTK_RECENT_SORT_CUSTOM, "BTK_RECENT_SORT_CUSTOM", "custom" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkRecentSortType"), values);
    }
    return etype;
}
GType
btk_recent_chooser_error_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_RECENT_CHOOSER_ERROR_NOT_FOUND, "BTK_RECENT_CHOOSER_ERROR_NOT_FOUND", "not-found" },
            { BTK_RECENT_CHOOSER_ERROR_INVALID_URI, "BTK_RECENT_CHOOSER_ERROR_INVALID_URI", "invalid-uri" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkRecentChooserError"), values);
    }
    return etype;
}
/* enumerations from "btkrecentfilter.h" */
GType
btk_recent_filter_flags_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GFlagsValue values[] = {
            { BTK_RECENT_FILTER_URI, "BTK_RECENT_FILTER_URI", "uri" },
            { BTK_RECENT_FILTER_DISPLAY_NAME, "BTK_RECENT_FILTER_DISPLAY_NAME", "display-name" },
            { BTK_RECENT_FILTER_MIME_TYPE, "BTK_RECENT_FILTER_MIME_TYPE", "mime-type" },
            { BTK_RECENT_FILTER_APPLICATION, "BTK_RECENT_FILTER_APPLICATION", "application" },
            { BTK_RECENT_FILTER_GROUP, "BTK_RECENT_FILTER_GROUP", "group" },
            { BTK_RECENT_FILTER_AGE, "BTK_RECENT_FILTER_AGE", "age" },
            { 0, NULL, NULL }
        };
        etype = g_flags_register_static (g_intern_static_string ("BtkRecentFilterFlags"), values);
    }
    return etype;
}
/* enumerations from "btkrecentmanager.h" */
GType
btk_recent_manager_error_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_RECENT_MANAGER_ERROR_NOT_FOUND, "BTK_RECENT_MANAGER_ERROR_NOT_FOUND", "not-found" },
            { BTK_RECENT_MANAGER_ERROR_INVALID_URI, "BTK_RECENT_MANAGER_ERROR_INVALID_URI", "invalid-uri" },
            { BTK_RECENT_MANAGER_ERROR_INVALID_ENCODING, "BTK_RECENT_MANAGER_ERROR_INVALID_ENCODING", "invalid-encoding" },
            { BTK_RECENT_MANAGER_ERROR_NOT_REGISTERED, "BTK_RECENT_MANAGER_ERROR_NOT_REGISTERED", "not-registered" },
            { BTK_RECENT_MANAGER_ERROR_READ, "BTK_RECENT_MANAGER_ERROR_READ", "read" },
            { BTK_RECENT_MANAGER_ERROR_WRITE, "BTK_RECENT_MANAGER_ERROR_WRITE", "write" },
            { BTK_RECENT_MANAGER_ERROR_UNKNOWN, "BTK_RECENT_MANAGER_ERROR_UNKNOWN", "unknown" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkRecentManagerError"), values);
    }
    return etype;
}
/* enumerations from "btksizegroup.h" */
GType
btk_size_group_mode_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_SIZE_GROUP_NONE, "BTK_SIZE_GROUP_NONE", "none" },
            { BTK_SIZE_GROUP_HORIZONTAL, "BTK_SIZE_GROUP_HORIZONTAL", "horizontal" },
            { BTK_SIZE_GROUP_VERTICAL, "BTK_SIZE_GROUP_VERTICAL", "vertical" },
            { BTK_SIZE_GROUP_BOTH, "BTK_SIZE_GROUP_BOTH", "both" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkSizeGroupMode"), values);
    }
    return etype;
}
/* enumerations from "btkspinbutton.h" */
GType
btk_spin_button_update_policy_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_UPDATE_ALWAYS, "BTK_UPDATE_ALWAYS", "always" },
            { BTK_UPDATE_IF_VALID, "BTK_UPDATE_IF_VALID", "if-valid" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkSpinButtonUpdatePolicy"), values);
    }
    return etype;
}
GType
btk_spin_type_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_SPIN_STEP_FORWARD, "BTK_SPIN_STEP_FORWARD", "step-forward" },
            { BTK_SPIN_STEP_BACKWARD, "BTK_SPIN_STEP_BACKWARD", "step-backward" },
            { BTK_SPIN_PAGE_FORWARD, "BTK_SPIN_PAGE_FORWARD", "page-forward" },
            { BTK_SPIN_PAGE_BACKWARD, "BTK_SPIN_PAGE_BACKWARD", "page-backward" },
            { BTK_SPIN_HOME, "BTK_SPIN_HOME", "home" },
            { BTK_SPIN_END, "BTK_SPIN_END", "end" },
            { BTK_SPIN_USER_DEFINED, "BTK_SPIN_USER_DEFINED", "user-defined" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkSpinType"), values);
    }
    return etype;
}
/* enumerations from "btktextbuffer.h" */
GType
btk_text_buffer_target_info_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_TEXT_BUFFER_TARGET_INFO_BUFFER_CONTENTS, "BTK_TEXT_BUFFER_TARGET_INFO_BUFFER_CONTENTS", "buffer-contents" },
            { BTK_TEXT_BUFFER_TARGET_INFO_RICH_TEXT, "BTK_TEXT_BUFFER_TARGET_INFO_RICH_TEXT", "rich-text" },
            { BTK_TEXT_BUFFER_TARGET_INFO_TEXT, "BTK_TEXT_BUFFER_TARGET_INFO_TEXT", "text" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkTextBufferTargetInfo"), values);
    }
    return etype;
}
/* enumerations from "btktextiter.h" */
GType
btk_text_search_flags_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GFlagsValue values[] = {
            { BTK_TEXT_SEARCH_VISIBLE_ONLY, "BTK_TEXT_SEARCH_VISIBLE_ONLY", "visible-only" },
            { BTK_TEXT_SEARCH_TEXT_ONLY, "BTK_TEXT_SEARCH_TEXT_ONLY", "text-only" },
            { 0, NULL, NULL }
        };
        etype = g_flags_register_static (g_intern_static_string ("BtkTextSearchFlags"), values);
    }
    return etype;
}
/* enumerations from "btktextview.h" */
GType
btk_text_window_type_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_TEXT_WINDOW_PRIVATE, "BTK_TEXT_WINDOW_PRIVATE", "private" },
            { BTK_TEXT_WINDOW_WIDGET, "BTK_TEXT_WINDOW_WIDGET", "widget" },
            { BTK_TEXT_WINDOW_TEXT, "BTK_TEXT_WINDOW_TEXT", "text" },
            { BTK_TEXT_WINDOW_LEFT, "BTK_TEXT_WINDOW_LEFT", "left" },
            { BTK_TEXT_WINDOW_RIGHT, "BTK_TEXT_WINDOW_RIGHT", "right" },
            { BTK_TEXT_WINDOW_TOP, "BTK_TEXT_WINDOW_TOP", "top" },
            { BTK_TEXT_WINDOW_BOTTOM, "BTK_TEXT_WINDOW_BOTTOM", "bottom" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkTextWindowType"), values);
    }
    return etype;
}
/* enumerations from "btktoolbar.h" */
GType
btk_toolbar_child_type_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_TOOLBAR_CHILD_SPACE, "BTK_TOOLBAR_CHILD_SPACE", "space" },
            { BTK_TOOLBAR_CHILD_BUTTON, "BTK_TOOLBAR_CHILD_BUTTON", "button" },
            { BTK_TOOLBAR_CHILD_TOGGLEBUTTON, "BTK_TOOLBAR_CHILD_TOGGLEBUTTON", "togglebutton" },
            { BTK_TOOLBAR_CHILD_RADIOBUTTON, "BTK_TOOLBAR_CHILD_RADIOBUTTON", "radiobutton" },
            { BTK_TOOLBAR_CHILD_WIDGET, "BTK_TOOLBAR_CHILD_WIDGET", "widget" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkToolbarChildType"), values);
    }
    return etype;
}
GType
btk_toolbar_space_style_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_TOOLBAR_SPACE_EMPTY, "BTK_TOOLBAR_SPACE_EMPTY", "empty" },
            { BTK_TOOLBAR_SPACE_LINE, "BTK_TOOLBAR_SPACE_LINE", "line" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkToolbarSpaceStyle"), values);
    }
    return etype;
}
/* enumerations from "btktoolpalette.h" */
GType
btk_tool_palette_drag_targets_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GFlagsValue values[] = {
            { BTK_TOOL_PALETTE_DRAG_ITEMS, "BTK_TOOL_PALETTE_DRAG_ITEMS", "items" },
            { BTK_TOOL_PALETTE_DRAG_GROUPS, "BTK_TOOL_PALETTE_DRAG_GROUPS", "groups" },
            { 0, NULL, NULL }
        };
        etype = g_flags_register_static (g_intern_static_string ("BtkToolPaletteDragTargets"), values);
    }
    return etype;
}
/* enumerations from "btktree.h" */
GType
btk_tree_view_mode_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_TREE_VIEW_LINE, "BTK_TREE_VIEW_LINE", "line" },
            { BTK_TREE_VIEW_ITEM, "BTK_TREE_VIEW_ITEM", "item" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkTreeViewMode"), values);
    }
    return etype;
}
/* enumerations from "btktreemodel.h" */
GType
btk_tree_model_flags_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GFlagsValue values[] = {
            { BTK_TREE_MODEL_ITERS_PERSIST, "BTK_TREE_MODEL_ITERS_PERSIST", "iters-persist" },
            { BTK_TREE_MODEL_LIST_ONLY, "BTK_TREE_MODEL_LIST_ONLY", "list-only" },
            { 0, NULL, NULL }
        };
        etype = g_flags_register_static (g_intern_static_string ("BtkTreeModelFlags"), values);
    }
    return etype;
}
/* enumerations from "btktreeview.h" */
GType
btk_tree_view_drop_position_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_TREE_VIEW_DROP_BEFORE, "BTK_TREE_VIEW_DROP_BEFORE", "before" },
            { BTK_TREE_VIEW_DROP_AFTER, "BTK_TREE_VIEW_DROP_AFTER", "after" },
            { BTK_TREE_VIEW_DROP_INTO_OR_BEFORE, "BTK_TREE_VIEW_DROP_INTO_OR_BEFORE", "into-or-before" },
            { BTK_TREE_VIEW_DROP_INTO_OR_AFTER, "BTK_TREE_VIEW_DROP_INTO_OR_AFTER", "into-or-after" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkTreeViewDropPosition"), values);
    }
    return etype;
}
/* enumerations from "btktreeviewcolumn.h" */
GType
btk_tree_view_column_sizing_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_TREE_VIEW_COLUMN_GROW_ONLY, "BTK_TREE_VIEW_COLUMN_GROW_ONLY", "grow-only" },
            { BTK_TREE_VIEW_COLUMN_AUTOSIZE, "BTK_TREE_VIEW_COLUMN_AUTOSIZE", "autosize" },
            { BTK_TREE_VIEW_COLUMN_FIXED, "BTK_TREE_VIEW_COLUMN_FIXED", "fixed" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkTreeViewColumnSizing"), values);
    }
    return etype;
}
/* enumerations from "btkuimanager.h" */
GType
btk_ui_manager_item_type_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GFlagsValue values[] = {
            { BTK_UI_MANAGER_AUTO, "BTK_UI_MANAGER_AUTO", "auto" },
            { BTK_UI_MANAGER_MENUBAR, "BTK_UI_MANAGER_MENUBAR", "menubar" },
            { BTK_UI_MANAGER_MENU, "BTK_UI_MANAGER_MENU", "menu" },
            { BTK_UI_MANAGER_TOOLBAR, "BTK_UI_MANAGER_TOOLBAR", "toolbar" },
            { BTK_UI_MANAGER_PLACEHOLDER, "BTK_UI_MANAGER_PLACEHOLDER", "placeholder" },
            { BTK_UI_MANAGER_POPUP, "BTK_UI_MANAGER_POPUP", "popup" },
            { BTK_UI_MANAGER_MENUITEM, "BTK_UI_MANAGER_MENUITEM", "menuitem" },
            { BTK_UI_MANAGER_TOOLITEM, "BTK_UI_MANAGER_TOOLITEM", "toolitem" },
            { BTK_UI_MANAGER_SEPARATOR, "BTK_UI_MANAGER_SEPARATOR", "separator" },
            { BTK_UI_MANAGER_ACCELERATOR, "BTK_UI_MANAGER_ACCELERATOR", "accelerator" },
            { BTK_UI_MANAGER_POPUP_WITH_ACCELS, "BTK_UI_MANAGER_POPUP_WITH_ACCELS", "popup-with-accels" },
            { 0, NULL, NULL }
        };
        etype = g_flags_register_static (g_intern_static_string ("BtkUIManagerItemType"), values);
    }
    return etype;
}
/* enumerations from "btkwidget.h" */
GType
btk_widget_flags_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GFlagsValue values[] = {
            { BTK_TOPLEVEL, "BTK_TOPLEVEL", "toplevel" },
            { BTK_NO_WINDOW, "BTK_NO_WINDOW", "no-window" },
            { BTK_REALIZED, "BTK_REALIZED", "realized" },
            { BTK_MAPPED, "BTK_MAPPED", "mapped" },
            { BTK_VISIBLE, "BTK_VISIBLE", "visible" },
            { BTK_SENSITIVE, "BTK_SENSITIVE", "sensitive" },
            { BTK_PARENT_SENSITIVE, "BTK_PARENT_SENSITIVE", "parent-sensitive" },
            { BTK_CAN_FOCUS, "BTK_CAN_FOCUS", "can-focus" },
            { BTK_HAS_FOCUS, "BTK_HAS_FOCUS", "has-focus" },
            { BTK_CAN_DEFAULT, "BTK_CAN_DEFAULT", "can-default" },
            { BTK_HAS_DEFAULT, "BTK_HAS_DEFAULT", "has-default" },
            { BTK_HAS_GRAB, "BTK_HAS_GRAB", "has-grab" },
            { BTK_RC_STYLE, "BTK_RC_STYLE", "rc-style" },
            { BTK_COMPOSITE_CHILD, "BTK_COMPOSITE_CHILD", "composite-child" },
            { BTK_NO_REPARENT, "BTK_NO_REPARENT", "no-reparent" },
            { BTK_APP_PAINTABLE, "BTK_APP_PAINTABLE", "app-paintable" },
            { BTK_RECEIVES_DEFAULT, "BTK_RECEIVES_DEFAULT", "receives-default" },
            { BTK_DOUBLE_BUFFERED, "BTK_DOUBLE_BUFFERED", "double-buffered" },
            { BTK_NO_SHOW_ALL, "BTK_NO_SHOW_ALL", "no-show-all" },
            { 0, NULL, NULL }
        };
        etype = g_flags_register_static (g_intern_static_string ("BtkWidgetFlags"), values);
    }
    return etype;
}
GType
btk_widget_help_type_get_type (void)
{
    static GType etype = 0;
    if (B_UNLIKELY(etype == 0)) {
        static const GEnumValue values[] = {
            { BTK_WIDGET_HELP_TOOLTIP, "BTK_WIDGET_HELP_TOOLTIP", "tooltip" },
            { BTK_WIDGET_HELP_WHATS_THIS, "BTK_WIDGET_HELP_WHATS_THIS", "whats-this" },
            { 0, NULL, NULL }
        };
        etype = g_enum_register_static (g_intern_static_string ("BtkWidgetHelpType"), values);
    }
    return etype;
}
#define __BTK_TYPE_BUILTINS_C__
#include "btkaliasdef.c"

/* Generated data ends here */

