
/* This file is generated by bunnylib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#if defined(BTK_DISABLE_SINGLE_INCLUDES) && !defined (__BTK_H_INSIDE__) && !defined (BTK_COMPILATION)
#error "Only <btk/btk.h> can be included directly."
#endif

#ifndef __BTK_TYPE_BUILTINS_H__
#define __BTK_TYPE_BUILTINS_H__

#include <bunnylib-object.h>

B_BEGIN_DECLS

/* enumerations from "btkaccelgroup.h" */
GType btk_accel_flags_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_ACCEL_FLAGS (btk_accel_flags_get_type ())

/* enumerations from "btkassistant.h" */
GType btk_assistant_page_type_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_ASSISTANT_PAGE_TYPE (btk_assistant_page_type_get_type ())

/* enumerations from "btkbuilder.h" */
GType btk_builder_error_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_BUILDER_ERROR (btk_builder_error_get_type ())

/* enumerations from "btkcalendar.h" */
GType btk_calendar_display_options_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_CALENDAR_DISPLAY_OPTIONS (btk_calendar_display_options_get_type ())

/* enumerations from "btkcellrenderer.h" */
GType btk_cell_renderer_state_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_CELL_RENDERER_STATE (btk_cell_renderer_state_get_type ())
GType btk_cell_renderer_mode_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_CELL_RENDERER_MODE (btk_cell_renderer_mode_get_type ())

/* enumerations from "btkcellrendereraccel.h" */
GType btk_cell_renderer_accel_mode_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_CELL_RENDERER_ACCEL_MODE (btk_cell_renderer_accel_mode_get_type ())

/* enumerations from "btkclist.h" */
GType btk_cell_type_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_CELL_TYPE (btk_cell_type_get_type ())
GType btk_clist_drag_pos_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_CLIST_DRAG_POS (btk_clist_drag_pos_get_type ())
GType btk_button_action_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_BUTTON_ACTION (btk_button_action_get_type ())

/* enumerations from "btkctree.h" */
GType btk_ctree_pos_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_CTREE_POS (btk_ctree_pos_get_type ())
GType btk_ctree_line_style_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_CTREE_LINE_STYLE (btk_ctree_line_style_get_type ())
GType btk_ctree_expander_style_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_CTREE_EXPANDER_STYLE (btk_ctree_expander_style_get_type ())
GType btk_ctree_expansion_type_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_CTREE_EXPANSION_TYPE (btk_ctree_expansion_type_get_type ())

/* enumerations from "btkdebug.h" */
GType btk_debug_flag_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_DEBUG_FLAG (btk_debug_flag_get_type ())

/* enumerations from "btkdialog.h" */
GType btk_dialog_flags_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_DIALOG_FLAGS (btk_dialog_flags_get_type ())
GType btk_response_type_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_RESPONSE_TYPE (btk_response_type_get_type ())

/* enumerations from "btkdnd.h" */
GType btk_dest_defaults_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_DEST_DEFAULTS (btk_dest_defaults_get_type ())
GType btk_target_flags_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_TARGET_FLAGS (btk_target_flags_get_type ())

/* enumerations from "btkentry.h" */
GType btk_entry_icon_position_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_ENTRY_ICON_POSITION (btk_entry_icon_position_get_type ())

/* enumerations from "btkenums.h" */
GType btk_anchor_type_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_ANCHOR_TYPE (btk_anchor_type_get_type ())
GType btk_arrow_placement_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_ARROW_PLACEMENT (btk_arrow_placement_get_type ())
GType btk_arrow_type_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_ARROW_TYPE (btk_arrow_type_get_type ())
GType btk_attach_options_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_ATTACH_OPTIONS (btk_attach_options_get_type ())
GType btk_button_box_style_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_BUTTON_BOX_STYLE (btk_button_box_style_get_type ())
GType btk_curve_type_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_CURVE_TYPE (btk_curve_type_get_type ())
GType btk_delete_type_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_DELETE_TYPE (btk_delete_type_get_type ())
GType btk_direction_type_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_DIRECTION_TYPE (btk_direction_type_get_type ())
GType btk_expander_style_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_EXPANDER_STYLE (btk_expander_style_get_type ())
GType btk_icon_size_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_ICON_SIZE (btk_icon_size_get_type ())
GType btk_sensitivity_type_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_SENSITIVITY_TYPE (btk_sensitivity_type_get_type ())
GType btk_side_type_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_SIDE_TYPE (btk_side_type_get_type ())
GType btk_text_direction_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_TEXT_DIRECTION (btk_text_direction_get_type ())
GType btk_justification_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_JUSTIFICATION (btk_justification_get_type ())
GType btk_match_type_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_MATCH_TYPE (btk_match_type_get_type ())
GType btk_menu_direction_type_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_MENU_DIRECTION_TYPE (btk_menu_direction_type_get_type ())
GType btk_message_type_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_MESSAGE_TYPE (btk_message_type_get_type ())
GType btk_metric_type_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_METRIC_TYPE (btk_metric_type_get_type ())
GType btk_movement_step_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_MOVEMENT_STEP (btk_movement_step_get_type ())
GType btk_scroll_step_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_SCROLL_STEP (btk_scroll_step_get_type ())
GType btk_orientation_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_ORIENTATION (btk_orientation_get_type ())
GType btk_corner_type_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_CORNER_TYPE (btk_corner_type_get_type ())
GType btk_pack_type_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_PACK_TYPE (btk_pack_type_get_type ())
GType btk_path_priority_type_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_PATH_PRIORITY_TYPE (btk_path_priority_type_get_type ())
GType btk_path_type_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_PATH_TYPE (btk_path_type_get_type ())
GType btk_policy_type_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_POLICY_TYPE (btk_policy_type_get_type ())
GType btk_position_type_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_POSITION_TYPE (btk_position_type_get_type ())
GType btk_preview_type_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_PREVIEW_TYPE (btk_preview_type_get_type ())
GType btk_relief_style_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_RELIEF_STYLE (btk_relief_style_get_type ())
GType btk_resize_mode_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_RESIZE_MODE (btk_resize_mode_get_type ())
GType btk_signal_run_type_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_SIGNAL_RUN_TYPE (btk_signal_run_type_get_type ())
GType btk_scroll_type_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_SCROLL_TYPE (btk_scroll_type_get_type ())
GType btk_selection_mode_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_SELECTION_MODE (btk_selection_mode_get_type ())
GType btk_shadow_type_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_SHADOW_TYPE (btk_shadow_type_get_type ())
GType btk_state_type_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_STATE_TYPE (btk_state_type_get_type ())
GType btk_submenu_direction_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_SUBMENU_DIRECTION (btk_submenu_direction_get_type ())
GType btk_submenu_placement_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_SUBMENU_PLACEMENT (btk_submenu_placement_get_type ())
GType btk_toolbar_style_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_TOOLBAR_STYLE (btk_toolbar_style_get_type ())
GType btk_update_type_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_UPDATE_TYPE (btk_update_type_get_type ())
GType btk_visibility_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_VISIBILITY (btk_visibility_get_type ())
GType btk_window_position_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_WINDOW_POSITION (btk_window_position_get_type ())
GType btk_window_type_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_WINDOW_TYPE (btk_window_type_get_type ())
GType btk_wrap_mode_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_WRAP_MODE (btk_wrap_mode_get_type ())
GType btk_sort_type_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_SORT_TYPE (btk_sort_type_get_type ())
GType btk_im_preedit_style_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_IM_PREEDIT_STYLE (btk_im_preedit_style_get_type ())
GType btk_im_status_style_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_IM_STATUS_STYLE (btk_im_status_style_get_type ())
GType btk_pack_direction_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_PACK_DIRECTION (btk_pack_direction_get_type ())
GType btk_print_pages_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_PRINT_PAGES (btk_print_pages_get_type ())
GType btk_page_set_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_PAGE_SET (btk_page_set_get_type ())
GType btk_number_up_layout_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_NUMBER_UP_LAYOUT (btk_number_up_layout_get_type ())
GType btk_page_orientation_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_PAGE_ORIENTATION (btk_page_orientation_get_type ())
GType btk_print_quality_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_PRINT_QUALITY (btk_print_quality_get_type ())
GType btk_print_duplex_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_PRINT_DUPLEX (btk_print_duplex_get_type ())
GType btk_unit_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_UNIT (btk_unit_get_type ())
GType btk_tree_view_grid_lines_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_TREE_VIEW_GRID_LINES (btk_tree_view_grid_lines_get_type ())
GType btk_drag_result_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_DRAG_RESULT (btk_drag_result_get_type ())

/* enumerations from "btkfilechooser.h" */
GType btk_file_chooser_action_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_FILE_CHOOSER_ACTION (btk_file_chooser_action_get_type ())
GType btk_file_chooser_confirmation_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_FILE_CHOOSER_CONFIRMATION (btk_file_chooser_confirmation_get_type ())
GType btk_file_chooser_error_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_FILE_CHOOSER_ERROR (btk_file_chooser_error_get_type ())

/* enumerations from "btkfilefilter.h" */
GType btk_file_filter_flags_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_FILE_FILTER_FLAGS (btk_file_filter_flags_get_type ())

/* enumerations from "btkicontheme.h" */
GType btk_icon_lookup_flags_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_ICON_LOOKUP_FLAGS (btk_icon_lookup_flags_get_type ())
GType btk_icon_theme_error_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_ICON_THEME_ERROR (btk_icon_theme_error_get_type ())

/* enumerations from "btkiconview.h" */
GType btk_icon_view_drop_position_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_ICON_VIEW_DROP_POSITION (btk_icon_view_drop_position_get_type ())

/* enumerations from "btkimage.h" */
GType btk_image_type_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_IMAGE_TYPE (btk_image_type_get_type ())

/* enumerations from "btkmessagedialog.h" */
GType btk_buttons_type_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_BUTTONS_TYPE (btk_buttons_type_get_type ())

/* enumerations from "btknotebook.h" */
GType btk_notebook_tab_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_NOTEBOOK_TAB (btk_notebook_tab_get_type ())

/* enumerations from "btkobject.h" */
GType btk_object_flags_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_OBJECT_FLAGS (btk_object_flags_get_type ())
GType btk_arg_flags_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_ARG_FLAGS (btk_arg_flags_get_type ())

/* enumerations from "btkprintoperation.h" */
GType btk_print_status_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_PRINT_STATUS (btk_print_status_get_type ())
GType btk_print_operation_result_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_PRINT_OPERATION_RESULT (btk_print_operation_result_get_type ())
GType btk_print_operation_action_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_PRINT_OPERATION_ACTION (btk_print_operation_action_get_type ())
GType btk_print_error_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_PRINT_ERROR (btk_print_error_get_type ())

/* enumerations from "btkprivate.h" */
GType btk_private_flags_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_PRIVATE_FLAGS (btk_private_flags_get_type ())

/* enumerations from "btkprogressbar.h" */
GType btk_progress_bar_style_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_PROGRESS_BAR_STYLE (btk_progress_bar_style_get_type ())
GType btk_progress_bar_orientation_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_PROGRESS_BAR_ORIENTATION (btk_progress_bar_orientation_get_type ())

/* enumerations from "btkrc.h" */
GType btk_rc_flags_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_RC_FLAGS (btk_rc_flags_get_type ())
GType btk_rc_token_type_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_RC_TOKEN_TYPE (btk_rc_token_type_get_type ())

/* enumerations from "btkrecentchooser.h" */
GType btk_recent_sort_type_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_RECENT_SORT_TYPE (btk_recent_sort_type_get_type ())
GType btk_recent_chooser_error_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_RECENT_CHOOSER_ERROR (btk_recent_chooser_error_get_type ())

/* enumerations from "btkrecentfilter.h" */
GType btk_recent_filter_flags_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_RECENT_FILTER_FLAGS (btk_recent_filter_flags_get_type ())

/* enumerations from "btkrecentmanager.h" */
GType btk_recent_manager_error_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_RECENT_MANAGER_ERROR (btk_recent_manager_error_get_type ())

/* enumerations from "btksizegroup.h" */
GType btk_size_group_mode_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_SIZE_GROUP_MODE (btk_size_group_mode_get_type ())

/* enumerations from "btkspinbutton.h" */
GType btk_spin_button_update_policy_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_SPIN_BUTTON_UPDATE_POLICY (btk_spin_button_update_policy_get_type ())
GType btk_spin_type_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_SPIN_TYPE (btk_spin_type_get_type ())

/* enumerations from "btktextbuffer.h" */
GType btk_text_buffer_target_info_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_TEXT_BUFFER_TARGET_INFO (btk_text_buffer_target_info_get_type ())

/* enumerations from "btktextiter.h" */
GType btk_text_search_flags_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_TEXT_SEARCH_FLAGS (btk_text_search_flags_get_type ())

/* enumerations from "btktextview.h" */
GType btk_text_window_type_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_TEXT_WINDOW_TYPE (btk_text_window_type_get_type ())

/* enumerations from "btktoolbar.h" */
GType btk_toolbar_child_type_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_TOOLBAR_CHILD_TYPE (btk_toolbar_child_type_get_type ())
GType btk_toolbar_space_style_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_TOOLBAR_SPACE_STYLE (btk_toolbar_space_style_get_type ())

/* enumerations from "btktoolpalette.h" */
GType btk_tool_palette_drag_targets_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_TOOL_PALETTE_DRAG_TARGETS (btk_tool_palette_drag_targets_get_type ())

/* enumerations from "btktree.h" */
GType btk_tree_view_mode_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_TREE_VIEW_MODE (btk_tree_view_mode_get_type ())

/* enumerations from "btktreemodel.h" */
GType btk_tree_model_flags_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_TREE_MODEL_FLAGS (btk_tree_model_flags_get_type ())

/* enumerations from "btktreeview.h" */
GType btk_tree_view_drop_position_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_TREE_VIEW_DROP_POSITION (btk_tree_view_drop_position_get_type ())

/* enumerations from "btktreeviewcolumn.h" */
GType btk_tree_view_column_sizing_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_TREE_VIEW_COLUMN_SIZING (btk_tree_view_column_sizing_get_type ())

/* enumerations from "btkuimanager.h" */
GType btk_ui_manager_item_type_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_UI_MANAGER_ITEM_TYPE (btk_ui_manager_item_type_get_type ())

/* enumerations from "btkwidget.h" */
GType btk_widget_flags_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_WIDGET_FLAGS (btk_widget_flags_get_type ())
GType btk_widget_help_type_get_type (void) B_GNUC_CONST;
#define BTK_TYPE_WIDGET_HELP_TYPE (btk_widget_help_type_get_type ())
B_END_DECLS

#endif /* __BTK_TYPE_BUILTINS_H__ */

/* Generated data ends here */

